:- module(province_fact, []).
province(กรุงเทพมหานคร).
province(อำนาเริญ).
province(อ่างทอง).
province(บึงกาฬ).
province(บุรีรัมย์).
province(ฉะเชิงเทรา).
province(ชัยนาท).
province(ชัยภูมิ).
province(จันทบุรี).
province(เชียงใหม่).
province(เชียงราย).
province(ชลบุรี).
province(ชุมพร).
province(กาฬสินธุ์).
province(กำแพงเพชร).
province(กาญนบุรี).
province(ขอนแก่น).
province(กระบี่).
province(ลำปาง).
province(ลำพูน).
province(เลย).
province(ลพบุรี).
province(แม่ฮ่องสอน).
province(มหาสารคาม).
province(มุกดาหาร).
province(นครนายก).
province(นครปฐม).
province(นครพนม).
province(นครราชสีมา).
province(นครสวรรค์).
province(นครศรีธรรมราช).
province(น่าน).
province(นราธิวาส).
province(หนองบัวลำภู).
province(หนองคาย).
province(นนทบุรี).
province(ปทุมธานี).
province(ปัตตานี).
province(พัทลุง).
province(พะเยา).
province(เพชรบูรณ์).
province(เพชรบุรี).
province(พิิตร).
province(พิษณุโลก).
province(พระนครศรีอยุธยา).
province(แพร่).
province(ภูเก็ต).
province(ปราีนบุรี).
province(ประวบคีรีขันธ์).
province(ระนอง).
province(ราชบุรี).
province(ระยอง).
province(ร้อยเอ็ด).
province(สระแก้ว).
province(สกลนคร).
province(สมุทรสาคร).
province(สมุทรปราการ).
province(สมุทรสงคราม).
province(สระบุรี).
province(สตูล).
province(สิงห์บุรี).
province(ศรีสะเกษ).
province(สงขลา).
province(สุโขทัย).
province(สุพรรณบุรี).
province(สุราษฎร์ธานี).
province(สุรินทร์).
province(ตาก).
province(ตรัง).
province(ตราด).
province(อุบลราชธานี).
province(อุดรธานี).
province(อุทัยธานี).
province(อุตรดิตถ์).
province(ยะลา).
province(ยโสธร).
