:- module(district_class, []).
% is_part_of(districtName,provinceName)
is_part_of(kanlayaniwatthana,chiangmai).
is_part_of(chom_thong,chiangmai).
is_part_of(chai_prakan,chiangmai).
is_part_of(doi_tao,chiangmai).
is_part_of(doi_saket,chiangmai).
is_part_of(fang,chiangmai).
is_part_of(phrao,chiangmai).
is_part_of(mueang_chiang_mai,chiangmai).
is_part_of(mae_chaem,chiangmai).
is_part_of(mae_taeng,chiangmai).
is_part_of(mae_rim,chiangmai).
is_part_of(mae_wang,chiangmai).
is_part_of(mae_on,chiangmai).
is_part_of(mae_ai,chiangmai).
is_part_of(wiang_haeng,chiangmai).
is_part_of(samoeng,chiangmai).
is_part_of(san_kamphaeng,chiangmai).
is_part_of(san_sai,chiangmai).
is_part_of(san_pa_tong,chiangmai).
is_part_of(saraphi,chiangmai).
is_part_of(hang_dong,chiangmai).
is_part_of(omkoi,chiangmai).
is_part_of(hot,chiangmai).
is_part_of(chiang_dao,chiangmai).
is_part_of(doi_lo,chiangmai).
is_part_of(kut_khaopun,ubonratchathani).
is_part_of(khemarat,ubonratchathani).
is_part_of(khueang_nai,ubonratchathani).
is_part_of(khong_chiam,ubonratchathani).
is_part_of(don_mot_daeng,ubonratchathani).
is_part_of(det_udom,ubonratchathani).
is_part_of(trakan_phuet_phon,ubonratchathani).
is_part_of(thung_si_udom,ubonratchathani).
is_part_of(na_chaluai,ubonratchathani).
is_part_of(na_tan,ubonratchathani).
is_part_of(na_yia,ubonratchathani).
is_part_of(nam_khun,ubonratchathani).
is_part_of(nam_yuen,ubonratchathani).
is_part_of(boontharik,ubonratchathani).
is_part_of(phibun_mangsahan,ubonratchathani).
is_part_of(pho_sai,ubonratchathani).
is_part_of(muang_sam_sip,ubonratchathani).
is_part_of(mueang_ubonratchathani,ubonratchathani).
is_part_of(warin_chamrap,ubonratchathani).
is_part_of(si_mueang_mai,ubonratchathani).
is_part_of(sawang_wirawong,ubonratchathani).
is_part_of(samrong,ubonratchathani).
is_part_of(sirindhorn,ubonratchathani).
is_part_of(lao_suea_kok,ubonratchathani).
is_part_of(tan_sum,ubonratchathani).
% suphanburi
is_part_of(don_chedi,suphanburi).
is_part_of(dan_chang,suphanburi).
is_part_of(doem_bang_nang_buat,suphanburi).
is_part_of(bang_pla_ma,suphanburi).
is_part_of(mueang_saphan_buri,suphanburi).
is_part_of(si_prachan,suphanburi).
is_part_of(song_phi_nong,suphanburi).
is_part_of(sam_chuk,suphanburi).
is_part_of(nong_ya_sai,suphanburi).
is_part_of(u_thong,suphanburi).
% surin
is_part_of(mueang_surin,surin).
is_part_of(chumphon_buri,surin).
is_part_of(tha_tum,surin).
is_part_of(chom_phra,surin).
is_part_of(prasat,surin).
is_part_of(kap_choeng,surin).
is_part_of(rattanaburi,surin).
is_part_of(sanom,surin).
is_part_of(sikhoraphum,surin).
is_part_of(sangkha,surin).
is_part_of(lamduan,surin).
is_part_of(samrong_thap,surin).
is_part_of(buachet,surin).
is_part_of(phanom_dong_rak,surin).
is_part_of(si_narong,surin).
is_part_of(khwao_sinarin,surin).
is_part_of(non_narai,surin).