:- module(district_class, []).
% is_part_of(districtName,provinceName)
is_part_of(kanlayaniwatthana,chiangmai).
is_part_of(chom_thong,chiangmai).
is_part_of(chai_prakan,chiangmai).
is_part_of(doi_tao,chiangmai).
is_part_of(doi_saket,chiangmai).
is_part_of(fang,chiangmai).
is_part_of(phrao,chiangmai).
is_part_of(mueang_chiang_mai,chiangmai).
is_part_of(mae_chaem,chiangmai).
is_part_of(mae_taeng,chiangmai).
is_part_of(mae_rim,chiangmai).
is_part_of(mae_wang,chiangmai).
is_part_of(mae_on,chiangmai).
is_part_of(mae_ai,chiangmai).
is_part_of(wiang_haeng,chiangmai).
is_part_of(samoeng,chiangmai).
is_part_of(san_kamphaeng,chiangmai).
is_part_of(san_sai,chiangmai).
is_part_of(san_pa_tong,chiangmai).
is_part_of(saraphi,chiangmai).
is_part_of(hang_dong,chiangmai).
is_part_of(omkoi,chiangmai).
is_part_of(hot,chiangmai).
is_part_of(chiang_dao,chiangmai).
is_part_of(doi_lo,chiangmai).
is_part_of(kut_khaopun,ubon_ratchathani).
is_part_of(khemarat,ubon_ratchathani).
is_part_of(khueang_nai,ubon_ratchathani).
is_part_of(khong_chiam,ubon_ratchathani).
is_part_of(don_mot_daeng,ubon_ratchathani).
is_part_of(det_udom,ubon_ratchathani).
is_part_of(trakan_phuet_phon,ubon_ratchathani).
is_part_of(thung_si_udom,ubon_ratchathani).
is_part_of(na_chaluai,ubon_ratchathani).
is_part_of(na_tan,ubon_ratchathani).
is_part_of(na_yia,ubon_ratchathani).
is_part_of(nam_khun,ubon_ratchathani).
is_part_of(nam_yuen,ubon_ratchathani).
is_part_of(boontharik,ubon_ratchathani).
is_part_of(phibun_mangsahan,ubon_ratchathani).
is_part_of(pho_sai,ubon_ratchathani).
is_part_of(muang_sam_sip,ubon_ratchathani).
is_part_of(mueang_ubon_ratchathani,ubon_ratchathani).
is_part_of(warin_chamrap,ubon_ratchathani).
is_part_of(si_mueang_mai,ubon_ratchathani).
is_part_of(sawang_wirawong,ubon_ratchathani).
is_part_of(samrong,ubon_ratchathani).
is_part_of(sirindhorn,ubon_ratchathani).
is_part_of(lao_suea_kok,ubon_ratchathani).
is_part_of(tan_sum,ubon_ratchathani).