:- module(province_region_fact, []).
has_region(sakon_nakhon,north_east).
has_region(samut_songkhram,central).
has_region(krabi,south).
has_region(sa_kaeo,east).
has_region(roi_et,north_east).
has_region(narathiwat,south).
has_region(chaiyaphum,north_east).
has_region(chonburi,east).
has_region(rayong,east).
has_region(buriram,north_east).
has_region(sukhothai,central).
has_region(udon_thani,north_east).
has_region(khon_kaen,north_east).
has_region(lamphun,north).
has_region(ratchaburi,west).
has_region(uttaradit,north).
has_region(phetchaburi,west).
has_region(nan,north).
has_region(nakhon_ratchasima,north_east).
has_region(lopburi,central).
has_region(saraburi,central).
has_region(nakhon_nayok,central).
has_region(surat_thani,south).
has_region(nakhon_phanom,north_east).
has_region(samut_sakhon,central).
has_region(chachoengsao,east).
has_region(ayutthaya,central).
has_region(uthai_thani,central).
has_region(prachin_buri,east).
has_region(tak,west).
has_region(samut_prakan,central).
has_region(nonthaburi,central).
has_region(phatthalung,south).
has_region(nakhon_si_thammarat,south).
has_region(songkhla,south).
has_region(phitsanulok,central).
has_region(nakhon_pathom,central).
has_region(phichit,central).
has_region(suphan_buri,central).
has_region(sing_buri,central).
has_region(prachuap_khiri_khan,west).
has_region(yala,south).
has_region(nakhon_sawan,central).
has_region(sisaket,north_east).
has_region(kanchanaburi,west).
has_region(trat,east).
has_region(maha_sarakham,north_east).
has_region(surin,north_east).
has_region(bueng_kan,north_east).
has_region(phetchabun,central).
has_region(kamphaeng_phet,central).
has_region(ubon_ratchathani,north_east).
has_region(lampang,north).
has_region(ang_thong,central).
has_region(chiang_mai,north).
has_region(nan,northern).
has_region(amnat_charoen,north_east).
has_region(phayao,north).
has_region(loei,north_east).
has_region(chiang_rai,north).
has_region(bangkok,central).
has_region(phrae,north).
has_region(kalasin,north_east).
has_region(mukdahan,north_east).
has_region(nong_khai,north_east).
has_region(chainat,central).
has_region(trang,south).
has_region(chanthaburi,east).
has_region(pattani,south).
has_region(ranong,south).
has_region(phang_nga,south).
has_region(phuket,south).
has_region(pathum_thani,central).
has_region(satun,south).
has_region(mae_hong_son,north).
has_region(chumphon,south).
has_region(nong_bua_lamphu,north_east).
has_region(yasothon,north_east).
