:- module(province_region_fact, []).
has_region(sakonnakhon,northeast).
has_region(samutsongkhram,central).
has_region(krabi,south).
has_region(sakaeo,east).
has_region(roiet,northeast).
has_region(narathiwat,south).
has_region(chaiyaphum,northeast).
has_region(chonburi,east).
has_region(rayong,east).
has_region(buriram,northeast).
has_region(sukhothai,central).
has_region(udonthani,northeast).
has_region(khonkaen,northeast).
has_region(lamphun,north).
has_region(ratchaburi,west).
has_region(uttaradit,north).
has_region(phetchaburi,west).
has_region(nan,north).
has_region(nakhonratchasima,northeast).
has_region(lopburi,central).
has_region(saraburi,central).
has_region(nakhonnayok,central).
has_region(suratthani,south).
has_region(nakhonphanom,northeast).
has_region(samutsakhon,central).
has_region(chachoengsao,east).
has_region(ayutthaya,central).
has_region(uthaithani,central).
has_region(prachinburi,east).
has_region(tak,west).
has_region(samutprakan,central).
has_region(nonthaburi,central).
has_region(phatthalung,south).
has_region(nakhonsithammarat,south).
has_region(songkhla,south).
has_region(phitsanulok,central).
has_region(nakhonpathom,central).
has_region(phichit,central).
has_region(suphanburi,central).
has_region(singburi,central).
has_region(prachuapkhirikhan,west).
has_region(yala,south).
has_region(nakhonsawan,central).
has_region(sisaket,northeast).
has_region(kanchanaburi,west).
has_region(trat,east).
has_region(mahasarakham,northeast).
has_region(surin,northeast).
has_region(buengkan,northeast).
has_region(phetchabun,central).
has_region(kamphaengphet,central).
has_region(ubonratchathani,northeast).
has_region(lampang,north).
has_region(angthong,central).
has_region(chiangmai,north).
has_region(amnatcharoen,northeast).
has_region(phayao,north).
has_region(loei,northeast).
has_region(chiangrai,north).
has_region(bangkok,central).
has_region(phrae,north).
has_region(kalasin,northeast).
has_region(mukdahan,northeast).
has_region(nongkhai,northeast).
has_region(chainat,central).
has_region(trang,south).
has_region(chanthaburi,east).
has_region(pattani,south).
has_region(ranong,south).
has_region(phangnga,south).
has_region(phuket,south).
has_region(pathumthani,central).
has_region(satun,south).
has_region(maehongson,north).
has_region(chumphon,south).
has_region(nongbualamphu,northeast).
has_region(phranakhonsiayutthaya,central).
has_region(yasothon,northeast).
