:- module(province_fact, []).
province(bangkok).
province(amnat_charoen).
province(ang_thong).
province(bueng_kan).
province(buriram).
province(chachoengsao).
province(chainat).
province(chaiyaphum).
province(chanthaburi).
province(chiang_mai).
province(chiang_rai).
province(chonburi).
province(chumphon).
province(kalasin).
province(kamphaeng_phet).
province(kanchanaburi).
province(khon_kaen).
province(krabi).
province(lampang).
province(lamphun).
province(loei_province).
province(lopburi_province).
province(mae_hong_son).
province(maha_sarakham).
province(mukdahan).
province(nakhon_nayok).
province(nakhon_pathom).
province(nakhon_phanom).
province(nakhon_ratchasima).
province(nakhon_sawan).
province(nakhon_si_thammarat_province).
province(nan).
province(narathiwat).
province(nong_bua_lamphu).
province(nong_khai).
province(nonthaburi).
province(pathum_thani).
province(pattani).
province(phang_nga).
province(phatthalung).
province(phayao).
province(phetchabun).
province(phetchaburi).
province(phichit).
province(phitsanulok).
province(phra_nakhon_si_ayutthaya).
province(phrae).
province(phuket).
province(prachinburi).
province(prachuap_khiri_khan).
province(ranong).
province(ratchaburi).
province(rayong).
province(roi_et).
province(sa_kaeo).
province(sakon_nakhon).
province(samut_prakan).
province(samut_sakhon).
province(samut_songkhram).
province(saraburi).
province(satun).
province(sing_buri).
province(sisaket).
province(songkhla).
province(sukhothai).
province(suphan_buri).
province(surat_thani).
province(surin).
province(tak).
province(trang).
province(trat).
province(ubon_ratchathani).
province(udon_thani).
province(uthai_thani).
province(uttaradit).
province(yala).
province(yasothon).
