:- module(province_fact, []).
province(bangkok).
province(amnatcharoen).
province(angthong).
province(buengkan).
province(buriram).
province(chachoengsao).
province(chainat).
province(chaiyaphum).
province(chanthaburi).
province(chiangmai).
province(chiangrai).
province(chonburi).
province(chumphon).
province(kalasin).
province(kamphaengphet).
province(kanchanaburi).
province(khonkaen).
province(krabi).
province(lampang).
province(lamphun).
province(loei).
province(lopburi).
province(maehongson).
province(mahasarakham).
province(mukdahan).
province(nakhonnayok).
province(nakhonpathom).
province(nakhonphanom).
province(nakhonratchasima).
province(nakhonsawan).
province(nakhonsithammarat).
province(nan).
province(narathiwat).
province(nongbualamphu).
province(nongkhai).
province(nonthaburi).
province(pathumthani).
province(pattani).
province(phangnga).
province(phatthalung).
province(phayao).
province(phetchabun).
province(phetchaburi).
province(phichit).
province(phitsanulok).
province(phranakhonsiayutthaya).
province(phrae).
province(phuket).
province(prachinburi).
province(prachuapkhirikhan).
province(ranong).
province(ratchaburi).
province(rayong).
province(roiet).
province(sakaeo).
province(sakonnakhon).
province(samutprakan).
province(samutsakhon).
province(samutsongkhram).
province(saraburi).
province(satun).
province(singburi).
province(sisaket).
province(songkhla).
province(sukhothai).
province(suphanburi).
province(suratthani).
province(surin).
province(tak).
province(trang).
province(trat).
province(ubonratchathani).
province(udonthani).
province(uthaithani).
province(uttaradit).
province(yala).
province(yasothon).
