:- module(rice_region_fact, []).
grow_in(rd5,northeast).
grow_in(rd5,central).
grow_in(rd5,south).
grow_in(rd5,west).
grow_in(rd5,north).
grow_in(rd5,east).
grow_in(rd13,none).
grow_in(rd15,northeast).
grow_in(rd27,central).
grow_in(rd35,northeast).
grow_in(rd51,northeast).
grow_in(rd51,north).
grow_in(rd59,north).
grow_in(gowruang88,central).
grow_in(jasmine105,northeast).
grow_in(jasmine105,north).
grow_in(khaotahhaeng17,central).
grow_in(khaotahhaeng17,north).
grow_in(khaopahkmaw148,central).
grow_in(khaopahkmaw148,northeast).
grow_in(khaojowhawmphitsanulok1,north).
grow_in(khaojowhawmphitsanulok1,central).
grow_in(chiangphatthalung,south).
grow_in(chumpae60,northeast).
grow_in(queen132,south).
grow_in(ms.mons4,central).
grow_in(saguiwater19,northeast).
grow_in(watertaro43,none).
grow_in(pathumthani60,central).
grow_in(pathumthani60,east).
grow_in(pathumthani60,west).
grow_in(puangrai2,south).
grow_in(phattaling60,none).
grow_in(phitsanulok3,north).
grow_in(phitsanulok601,central).
grow_in(phitsanulok80,north).
grow_in(lookdaengpattani,south).
grow_in(lebnokpattani,south).
grow_in(ptnc0900259,south).
grow_in(leuangyai148,north).
grow_in(khemtawngphatthalung,none).
grow_in(khaoluangsanpahtwang,none).
grow_in(gaenjan,south).
grow_in(pttc020191,central).
grow_in(khaogawdiaw35,north).
grow_in(cholung97,south).
grow_in(khaimodrin3,south).
grow_in(rd6,north).
grow_in(rd6,northeast).
grow_in(rd8,northeast).
grow_in(nongkai80,northeast).
grow_in(rd16,north).
grow_in(rd18,northeast).
grow_in(rd18,north).
grow_in(rd20,northeast).
grow_in(gampai15,north).
grow_in(hahngyu71,northeast).
grow_in(mueynawng62m,north).
grow_in(niawdammor37,south).
grow_in(niawkiawngoo8974,north).
grow_in(niawsanpahtawng,north).
grow_in(niawsanpahtawng,northeast).
grow_in(niawubon1,northeast).
grow_in(niawubon2,northeast).
grow_in(leuangpratew123,central).
grow_in(ptnc9600449,south).
grow_in(rd1,northeast).
grow_in(rd1,central).
grow_in(rd1,south).
grow_in(rd1,west).
grow_in(rd1,north).
grow_in(rd1,east).
grow_in(rd3,northeast).
grow_in(rd3,central).
grow_in(rd3,south).
grow_in(rd3,west).
grow_in(rd3,north).
grow_in(rd3,east).
grow_in(rd7,central).
grow_in(rd7,south).
grow_in(rd9,northeast).
grow_in(rd9,central).
grow_in(rd9,south).
grow_in(rd9,west).
grow_in(rd9,north).
grow_in(rd9,east).
grow_in(rd11,northeast).
grow_in(rd11,central).
grow_in(rd11,south).
grow_in(rd11,west).
grow_in(rd11,north).
grow_in(rd11,east).
grow_in(rd21,northeast).
grow_in(rd21,central).
grow_in(rd21,south).
grow_in(rd21,west).
grow_in(rd21,north).
grow_in(rd21,east).
grow_in(rd23,northeast).
grow_in(rd23,central).
grow_in(rd23,south).
grow_in(rd23,west).
grow_in(rd23,north).
grow_in(rd23,east).
grow_in(rd25,northeast).
grow_in(rd25,central).
grow_in(rd25,south).
grow_in(rd25,west).
grow_in(rd25,north).
grow_in(rd25,east).
grow_in(rd29,north).
grow_in(rd29,central).
grow_in(rd31,central).
grow_in(rd33,northeast).
grow_in(rd33,north).
grow_in(rd37,south).
grow_in(rd39,north).
grow_in(rd41,north).
grow_in(rd43,northeast).
grow_in(rd43,central).
grow_in(rd43,south).
grow_in(rd43,west).
grow_in(rd43,north).
grow_in(rd43,east).
grow_in(rd47,north).
grow_in(rd49,northeast).
grow_in(rd49,central).
grow_in(rd49,south).
grow_in(rd49,west).
grow_in(rd49,north).
grow_in(rd49,east).
grow_in(rd53,north).
grow_in(rd55,south).
grow_in(rd57,northeast).
grow_in(rd57,central).
grow_in(rd57,south).
grow_in(rd57,west).
grow_in(rd57,north).
grow_in(rd57,east).
grow_in(rd61,north).
grow_in(rd61,central).
grow_in(rd63,north).
grow_in(rd63,central).
grow_in(rd63,northeast).
grow_in(khaojowhawmkhlongluang1,central).
grow_in(khaojowhawmsuphanburi,central).
grow_in(chainat1,northeast).
grow_in(chainat1,central).
grow_in(chainat1,south).
grow_in(chainat1,west).
grow_in(chainat1,north).
grow_in(chainat1,east).
grow_in(chainat2,north).
grow_in(pathumthani1,central).
grow_in(bangtaen,east).
grow_in(patthalung,south).
grow_in(phitsanulok2,northeast).
grow_in(phitsanulok2,central).
grow_in(phitsanulok2,south).
grow_in(phitsanulok2,west).
grow_in(phitsanulok2,north).
grow_in(phitsanulok2,east).
grow_in(phitsanulok602,central).
grow_in(phitsanulok602,north).
grow_in(suphanburi1,northeast).
grow_in(suphanburi1,central).
grow_in(suphanburi1,south).
grow_in(suphanburi1,west).
grow_in(suphanburi1,north).
grow_in(suphanburi1,east).
grow_in(suphanburi2,central).
grow_in(suphanburi2,east).
grow_in(suphanburi2,west).
grow_in(suphanburi3,central).
grow_in(suphanburi60,central).
grow_in(suphanburi60,east).
grow_in(suphanburi60,west).
grow_in(suphanburi90,central).
grow_in(surin1,northeast).
grow_in(rd2,northeast).
grow_in(rd2,central).
grow_in(rd2,south).
grow_in(rd2,west).
grow_in(rd2,north).
grow_in(rd2,east).
grow_in(rd4,north).
grow_in(rd4,northeast).
grow_in(rd10,none).
grow_in(rd14,north).
grow_in(rdmaejo2,north).
grow_in(phrae1,north).
grow_in(phrae1,northeast).
grow_in(sakonnakhon,northeast).
grow_in(sanpahtawng1,north).
grow_in(sanpahtawng1,northeast).
grow_in(tapowgaew161,none).
grow_in(nahngchalawng,central).
grow_in(pingaew56,central).
grow_in(plaingahmprachinburi,central).
grow_in(plaingahmprachinburi,north).
grow_in(lebmeunahng111,central).
grow_in(khaobahnnah432,central).
grow_in(khaobahnnah432,east).
grow_in(rd19,central).
grow_in(rd45,central).
grow_in(rd45,east).
grow_in(hantra60,central).
grow_in(prachinburi1,central).
grow_in(prachinburi1,east).
grow_in(prachinburi1,north).
grow_in(prachinburi2,central).
grow_in(prachinburi2,east).
grow_in(ayutthaya1,central).
grow_in(ayutthaya1,east).
grow_in(ayutthaya1,north).
grow_in(ayutthaya1,central).
grow_in(ayutthaya1,east).
grow_in(ayutthaya1,north).
grow_in(rd17,central).
grow_in(goomeuangluang,south).
grow_in(khaopongkrai,none).
grow_in(jowhaw,central).
grow_in(jowhaw,east).
grow_in(sewmaejan,north).
grow_in(sewmaejan,northeast).
grow_in(dawkpayawm,south).
grow_in(namroo,none).
grow_in(jowlisawsanpahtawng,none).
grow_in(jowkhaochiangmai,north).
grow_in(leumpua,west).
grow_in(r258,north).
grow_in(r258,northeast).
grow_in(redhawnrice,none).
grow_in(sangyodphattalung,south).
grow_in(redroserice,none).
grow_in(khaoyipundoa1,north).
grow_in(khaoyipundoa1,north).
grow_in(khaoyipundoa1,northeast).
grow_in(khaoyipundoa2,north).
grow_in(samerng1,north).
grow_in(samerng2,north).
grow_in(cp304,none).
grow_in(rdh1,central).
grow_in(rdh1,north).
grow_in(rdp3,central).
grow_in(samerng1,north).
grow_in(samerng2,north).
grow_in(phrae60,north).
grow_in(phrae60,northeast).
grow_in(fahng60,north).
grow_in(fahng60,northeast).
