:- module(rice_suitable_with_soilgroup, []).
# suitable_with(riceTypeName,soilGroupName,suitability,regionName).
suitable_with(nonGlutinous,krabi,bad,central).
suitable_with(nonGlutinous,krabi,bad,northeast).
suitable_with(nonGlutinous,krabi,bad,south).
suitable_with(nonGlutinous,krabi,none,north).
suitable_with(nonGlutinous,kantang,good,north).
suitable_with(nonGlutinous,kantang,good,central).
suitable_with(nonGlutinous,kantang,good,northeast).
suitable_with(nonGlutinous,kantang,moderate,south).
suitable_with(nonGlutinous,kabDaeng,bad,south).
suitable_with(nonGlutinous,kabDaeng,none,north).
suitable_with(nonGlutinous,khambong,moderate,northeast).
suitable_with(nonGlutinous,khambong,bad,south).
suitable_with(nonGlutinous,khambong,bad,north).
suitable_with(nonGlutinous,khambong,bad,central).
suitable_with(nonGlutinous,kamphangPet,bad,central).
suitable_with(nonGlutinous,kamphangPet,bad,northeast).
suitable_with(nonGlutinous,kamphangPet,bad,north).
suitable_with(nonGlutinous,kamphaengSaen,bad,central).
suitable_with(nonGlutinous,kamphaengSaen,bad,northeast).
suitable_with(nonGlutinous,kamphaengSaen,bad,north).
suitable_with(nonGlutinous,kulaRonghai,good,central).
suitable_with(nonGlutinous,kulaRonghai,moderate,northeast).
suitable_with(nonGlutinous,koYai,good,central).
suitable_with(nonGlutinous,koYai,good,northeast).
suitable_with(nonGlutinous,koYai,good,south).
suitable_with(nonGlutinous,koYai,good,north).
suitable_with(nonGlutinous,klaeng,good,central).
suitable_with(nonGlutinous,klaeng,good,northeast).
suitable_with(nonGlutinous,klaeng,good,south).
suitable_with(nonGlutinous,klaeng,good,north).
suitable_with(nonGlutinous,khaoKhat,moderate,northeast).
suitable_with(nonGlutinous,khaoKhat,bad,south).
suitable_with(nonGlutinous,khaoKhat,bad,central).
suitable_with(nonGlutinous,khaoKhat,none,north).
suitable_with(nonGlutinous,khaoYoi,good,central).
suitable_with(nonGlutinous,khaoYoi,good,northeast).
suitable_with(nonGlutinous,khaoYoi,good,south).
suitable_with(nonGlutinous,khaoYoi,good,north).
suitable_with(nonGlutinous,khlongKhut,good,central).
suitable_with(nonGlutinous,khlongKhut,good,northeast).
suitable_with(nonGlutinous,khlongKhut,good,south).
suitable_with(nonGlutinous,khlongKhut,good,north).
suitable_with(nonGlutinous,khlongChak,moderate,northeast).
suitable_with(nonGlutinous,khlongChak,bad,central).
suitable_with(nonGlutinous,khlongChak,bad,south).
suitable_with(nonGlutinous,khlongChak,none,north).
suitable_with(nonGlutinous,khlongTeng,bad,central).
suitable_with(nonGlutinous,khlongTeng,bad,south).
suitable_with(nonGlutinous,khlongThom,bad,central).
suitable_with(nonGlutinous,khlongThom,bad,south).
suitable_with(nonGlutinous,khlongNokKrathung,bad,central).
suitable_with(nonGlutinous,khlongNokKrathung,bad,south).
suitable_with(nonGlutinous,khuanKaLong,bad,central).
suitable_with(nonGlutinous,khuanKaLong,bad,south).
suitable_with(nonGlutinous,khoHong,bad,central).
suitable_with(nonGlutinous,khoHong,bad,northeast).
suitable_with(nonGlutinous,khoHong,bad,south).
suitable_with(nonGlutinous,khokKrathiam,good,northeast).
suitable_with(nonGlutinous,khokKrathiam,good,central).
suitable_with(nonGlutinous,khokKrathiam,good,north).
suitable_with(nonGlutinous,khokKloi,bad,central).
suitable_with(nonGlutinous,khokKloi,bad,northeast).
suitable_with(nonGlutinous,khokKloi,bad,south).
suitable_with(nonGlutinous,khokKloi,none,north).
suitable_with(nonGlutinous,khokKhain,good,central).
suitable_with(nonGlutinous,khokKhain,good,northeast).
suitable_with(nonGlutinous,khokKhain,good,south).
suitable_with(nonGlutinous,khokKhain,good,north).
suitable_with(nonGlutinous,korat,bad,central).
suitable_with(nonGlutinous,korat,bad,northeast).
suitable_with(nonGlutinous,korat,bad,north).
suitable_with(nonGlutinous,chatturat,moderate,northeast).
suitable_with(nonGlutinous,chatturat,bad,central).
suitable_with(nonGlutinous,chatturat,bad,north).
suitable_with(nonGlutinous,chakkarat,bad,central).
suitable_with(nonGlutinous,chakkarat,bad,north).
suitable_with(nonGlutinous,chanTuk,bad,central).
suitable_with(nonGlutinous,chanTuk,bad,northeast).
suitable_with(nonGlutinous,chanTuk,bad,north).
suitable_with(nonGlutinous,chalong,bad,central).
suitable_with(nonGlutinous,chalong,bad,south).
suitable_with(nonGlutinous,chachoengsao,good,central).
suitable_with(nonGlutinous,chachoengsao,good,northeast).
suitable_with(nonGlutinous,chachoengsao,good,south).
suitable_with(nonGlutinous,chachoengsao,good,north).
suitable_with(nonGlutinous,chonBuri,good,central).
suitable_with(nonGlutinous,chonBuri,good,northeast).
suitable_with(nonGlutinous,chonBuri,good,south).
suitable_with(nonGlutinous,chonBuri,good,north).
suitable_with(nonGlutinous,chongKae,good,northeast).
suitable_with(nonGlutinous,chongKae,good,central).
suitable_with(nonGlutinous,chongKae,good,north).
suitable_with(nonGlutinous,chaAm,moderate,northeast).
suitable_with(nonGlutinous,chaAm,bad,central).
suitable_with(nonGlutinous,chaAm,none,north).
suitable_with(nonGlutinous,chaiBadan,moderate,northeast).
suitable_with(nonGlutinous,chaiBadan,bad,north).
suitable_with(nonGlutinous,chaiBadan,bad,central).
suitable_with(nonGlutinous,chumphon,moderate,northeast).
suitable_with(nonGlutinous,chumphon,bad,central).
suitable_with(nonGlutinous,chumphon,bad,south).
suitable_with(nonGlutinous,chumphon,none,north).
suitable_with(nonGlutinous,chumphonBuri,moderate,northeast).
suitable_with(nonGlutinous,chumphonBuri,bad,north).
suitable_with(nonGlutinous,chumphonBuri,bad,central).
suitable_with(nonGlutinous,chumPhuang,moderate,northeast).
suitable_with(nonGlutinous,chumPhuang,bad,north).
suitable_with(nonGlutinous,chumPhuang,bad,central).
suitable_with(nonGlutinous,chumsaeng,good,central).
suitable_with(nonGlutinous,chumsaeng,good,northeast).
suitable_with(nonGlutinous,chumsaeng,good,north).
suitable_with(nonGlutinous,chiangKhong,moderate,northeast).
suitable_with(nonGlutinous,chiangKhong,bad,central).
suitable_with(nonGlutinous,chiangKhong,bad,north).
suitable_with(nonGlutinous,chiangKhan,moderate,northeast).
suitable_with(nonGlutinous,chiangKhan,bad,south).
suitable_with(nonGlutinous,chiangKhan,bad,north).
suitable_with(nonGlutinous,chiangKhan,bad,central).
suitable_with(nonGlutinous,chiangRai,good,central).
suitable_with(nonGlutinous,chiangRai,good,northeast).
suitable_with(nonGlutinous,chiangRai,good,south).
suitable_with(nonGlutinous,chiangRai,good,north).
suitable_with(nonGlutinous,chiangSaen,bad,central).
suitable_with(nonGlutinous,chiangSaen,bad,north).
suitable_with(nonGlutinous,chiangMai,moderate,northeast).
suitable_with(nonGlutinous,chiangMai,bad,north).
suitable_with(nonGlutinous,chiangMai,bad,central).
suitable_with(nonGlutinous,chianYai,moderate,central).
suitable_with(nonGlutinous,chianYai,moderate,south).
suitable_with(nonGlutinous,chokChai,moderate,northeast).
suitable_with(nonGlutinous,chokChai,bad,central).
suitable_with(nonGlutinous,chokChai,bad,north).
suitable_with(nonGlutinous,dongTakhian,moderate,northeast).
suitable_with(nonGlutinous,dongTakhian,bad,south).
suitable_with(nonGlutinous,dongTakhian,bad,central).
suitable_with(nonGlutinous,dongTakhian,none,north).
suitable_with(nonGlutinous,dongYangEn,bad,central).
suitable_with(nonGlutinous,dongYangEn,bad,northeast).
suitable_with(nonGlutinous,dongYangEn,bad,north).
suitable_with(nonGlutinous,dongLan,moderate,northeast).
suitable_with(nonGlutinous,dongLan,bad,central).
suitable_with(nonGlutinous,dongLan,bad,north).
suitable_with(nonGlutinous,donChedi,moderate,northeast).
suitable_with(nonGlutinous,donChedi,bad,north).
suitable_with(nonGlutinous,donChedi,bad,central).
suitable_with(nonGlutinous,donMuang,good,south).
suitable_with(nonGlutinous,donMuang,good,central).
suitable_with(nonGlutinous,donMuang,bad,northeast).
suitable_with(nonGlutinous,donRai,bad,central).
suitable_with(nonGlutinous,donRai,bad,northeast).
suitable_with(nonGlutinous,donRai,bad,north).
suitable_with(nonGlutinous,doiPui,bad,central).
suitable_with(nonGlutinous,doiPui,bad,north).
suitable_with(nonGlutinous,danKhunThot,moderate,northeast).
suitable_with(nonGlutinous,danKhunThot,bad,south).
suitable_with(nonGlutinous,danKhunThot,bad,north).
suitable_with(nonGlutinous,danKhunThot,bad,central).
suitable_with(nonGlutinous,danSai,bad,central).
suitable_with(nonGlutinous,danSai,bad,northeast).
suitable_with(nonGlutinous,danSai,bad,north).
suitable_with(nonGlutinous,doemBang,good,central).
suitable_with(nonGlutinous,doemBang,good,south).
suitable_with(nonGlutinous,doemBang,good,north).
suitable_with(nonGlutinous,doemBang,moderate,northeast).
suitable_with(nonGlutinous,thonSai,good,central).
suitable_with(nonGlutinous,thonSai,good,south).
suitable_with(nonGlutinous,trang,bad,central).
suitable_with(nonGlutinous,trang,bad,south).
suitable_with(nonGlutinous,trat,bad,central).
suitable_with(nonGlutinous,trat,bad,south).
suitable_with(nonGlutinous,thakuaThung,moderate,central).
suitable_with(nonGlutinous,thakuaThung,moderate,northeast).
suitable_with(nonGlutinous,thakuaThung,bad,south).
suitable_with(nonGlutinous,taphanHin,bad,central).
suitable_with(nonGlutinous,taphanHin,bad,northeast).
suitable_with(nonGlutinous,taphanHin,bad,north).
suitable_with(nonGlutinous,thaKhun,bad,central).
suitable_with(nonGlutinous,thaKhun,bad,south).
suitable_with(nonGlutinous,takhli,moderate,northeast).
suitable_with(nonGlutinous,takhli,moderate,south).
suitable_with(nonGlutinous,takhli,bad,north).
suitable_with(nonGlutinous,takhli,bad,central).
suitable_with(nonGlutinous,saiKhao,good,north).
suitable_with(nonGlutinous,saiKhao,moderate,central).
suitable_with(nonGlutinous,saiKhao,moderate,northeast).
suitable_with(nonGlutinous,saiKhao,moderate,south).
suitable_with(nonGlutinous,thaKhwang,good,central).
suitable_with(nonGlutinous,thaKhwang,good,northeast).
suitable_with(nonGlutinous,thaKhwang,good,south).
suitable_with(nonGlutinous,thaKhwang,good,north).
suitable_with(nonGlutinous,thaChin,bad,central).
suitable_with(nonGlutinous,thaChin,bad,south).
suitable_with(nonGlutinous,thaChang,moderate,northeast).
suitable_with(nonGlutinous,thaChang,bad,central).
suitable_with(nonGlutinous,thaChang,bad,south).
suitable_with(nonGlutinous,thaChang,none,north).
suitable_with(nonGlutinous,thaSae,bad,central).
suitable_with(nonGlutinous,thaSae,bad,south).
suitable_with(nonGlutinous,thaTum,good,central).
suitable_with(nonGlutinous,thaTum,good,south).
suitable_with(nonGlutinous,thaTum,good,north).
suitable_with(nonGlutinous,thaTum,moderate,northeast).
suitable_with(nonGlutinous,thaPhon,good,central).
suitable_with(nonGlutinous,thaPhon,good,northeast).
suitable_with(nonGlutinous,thaPhon,good,north).
suitable_with(nonGlutinous,thaMuang,moderate,northeast).
suitable_with(nonGlutinous,thaMuang,bad,north).
suitable_with(nonGlutinous,thaMuang,bad,central).
suitable_with(nonGlutinous,thaiMuang,bad,central).
suitable_with(nonGlutinous,thaiMuang,bad,northeast).
suitable_with(nonGlutinous,thaiMuang,bad,south).
suitable_with(nonGlutinous,thaiMuang,none,north).
suitable_with(nonGlutinous,thaYang,bad,central).
suitable_with(nonGlutinous,thaYang,bad,northeast).
suitable_with(nonGlutinous,thaYang,bad,north).
suitable_with(nonGlutinous,thaRua,good,central).
suitable_with(nonGlutinous,thaRua,good,northeast).
suitable_with(nonGlutinous,thaRua,good,north).
suitable_with(nonGlutinous,thaLi,moderate,northeast).
suitable_with(nonGlutinous,thaLi,bad,north).
suitable_with(nonGlutinous,thaLi,bad,central).
suitable_with(nonGlutinous,thaSala,good,central).
suitable_with(nonGlutinous,thaSala,good,northeast).
suitable_with(nonGlutinous,thaSala,good,south).
suitable_with(nonGlutinous,thaSala,good,north).
suitable_with(nonGlutinous,thaMai,bad,central).
suitable_with(nonGlutinous,thaMai,none,north).
suitable_with(nonGlutinous,thaUthen,moderate,north).
suitable_with(nonGlutinous,thaUthen,moderate,central).
suitable_with(nonGlutinous,thaUthen,moderate,northeast).
suitable_with(nonGlutinous,thaUthen,none,south).
suitable_with(nonGlutinous,thungKai,good,central).
suitable_with(nonGlutinous,thungKai,good,northeast).
suitable_with(nonGlutinous,thungKai,good,north).
suitable_with(nonGlutinous,thungKai,moderate,south).
suitable_with(nonGlutinous,thungWa,bad,central).
suitable_with(nonGlutinous,thungWa,bad,northeast).
suitable_with(nonGlutinous,thungWa,bad,south).
suitable_with(nonGlutinous,saiNgam,moderate,northeast).
suitable_with(nonGlutinous,saiNgam,bad,north).
suitable_with(nonGlutinous,saiNgam,bad,central).
suitable_with(nonGlutinous,thanyaburi,good,central).
suitable_with(nonGlutinous,thanyaburi,good,south).
suitable_with(nonGlutinous,thanyaburi,bad,northeast).
suitable_with(nonGlutinous,thatPhanom,bad,central).
suitable_with(nonGlutinous,thatPhanom,bad,northeast).
suitable_with(nonGlutinous,thatPhanom,bad,north).
suitable_with(nonGlutinous,nakhonPathom,good,central).
suitable_with(nonGlutinous,nakhonPathom,good,south).
suitable_with(nonGlutinous,nakhonPathom,good,north).
suitable_with(nonGlutinous,nakhonPathom,moderate,northeast).
suitable_with(nonGlutinous,nakhonPhanom,good,central).
suitable_with(nonGlutinous,nakhonPhanom,good,northeast).
suitable_with(nonGlutinous,nakhonPhanom,good,south).
suitable_with(nonGlutinous,nakhonPhanom,good,north).
suitable_with(nonGlutinous,nakhonSawan,moderate,northeast).
suitable_with(nonGlutinous,nakhonSawan,bad,north).
suitable_with(nonGlutinous,nakhonSawan,bad,central).
suitable_with(nonGlutinous,narathiwat,bad,south).
suitable_with(nonGlutinous,naThawi,bad,central).
suitable_with(nonGlutinous,naThawi,bad,northeast).
suitable_with(nonGlutinous,naThawi,bad,south).
suitable_with(nonGlutinous,naThon,bad,central).
suitable_with(nonGlutinous,naThon,bad,south).
suitable_with(nonGlutinous,naTham,bad,central).
suitable_with(nonGlutinous,naTham,bad,south).
suitable_with(nonGlutinous,nan,good,central).
suitable_with(nonGlutinous,nan,good,northeast).
suitable_with(nonGlutinous,nan,good,north).
suitable_with(nonGlutinous,namKrachi,good,central).
suitable_with(nonGlutinous,namKrachi,good,northeast).
suitable_with(nonGlutinous,namKrachi,good,south).
suitable_with(nonGlutinous,namKrachi,good,north).
suitable_with(nonGlutinous,namChun,bad,central).
suitable_with(nonGlutinous,namChun,bad,northeast).
suitable_with(nonGlutinous,namChun,bad,north).
suitable_with(nonGlutinous,namDuk,bad,central).
suitable_with(nonGlutinous,namDuk,bad,northeast).
suitable_with(nonGlutinous,namDuk,bad,north).
suitable_with(nonGlutinous,namPhong,bad,central).
suitable_with(nonGlutinous,namPhong,bad,northeast).
suitable_with(nonGlutinous,namPhong,bad,north).
suitable_with(nonGlutinous,namLen,moderate,northeast).
suitable_with(nonGlutinous,namLen,bad,central).
suitable_with(nonGlutinous,namLen,bad,north).
suitable_with(nonGlutinous,borabu,moderate,northeast).
suitable_with(nonGlutinous,borabu,bad,north).
suitable_with(nonGlutinous,borabu,bad,central).
suitable_with(nonGlutinous,boThai,bad,central).
suitable_with(nonGlutinous,boThai,bad,northeast).
suitable_with(nonGlutinous,boThai,bad,north).
suitable_with(nonGlutinous,bangkok,good,central).
suitable_with(nonGlutinous,bangkok,good,northeast).
suitable_with(nonGlutinous,bangkok,good,south).
suitable_with(nonGlutinous,bangkok,good,north).
suitable_with(nonGlutinous,bangKhen,good,central).
suitable_with(nonGlutinous,bangKhen,good,northeast).
suitable_with(nonGlutinous,bangKhen,good,south).
suitable_with(nonGlutinous,bangKhen,good,north).
suitable_with(nonGlutinous,bangNara,good,central).
suitable_with(nonGlutinous,bangNara,good,northeast).
suitable_with(nonGlutinous,bangNara,good,south).
suitable_with(nonGlutinous,bangNara,good,north).
suitable_with(nonGlutinous,bangnamPrieo,good,central).
suitable_with(nonGlutinous,bangnamPrieo,good,northeast).
suitable_with(nonGlutinous,bangnamPrieo,good,south).
suitable_with(nonGlutinous,bangnamPrieo,good,north).
suitable_with(nonGlutinous,bangPakong,moderate,central).
suitable_with(nonGlutinous,bangPakong,moderate,northeast).
suitable_with(nonGlutinous,bangPakong,bad,south).
suitable_with(nonGlutinous,bangPhae,good,central).
suitable_with(nonGlutinous,bangPhae,good,northeast).
suitable_with(nonGlutinous,bangPhae,good,south).
suitable_with(nonGlutinous,bangPhae,good,north).
suitable_with(nonGlutinous,bangMunNak,good,central).
suitable_with(nonGlutinous,bangMunNak,good,northeast).
suitable_with(nonGlutinous,bangMunNak,good,north).
suitable_with(nonGlutinous,bangLen,good,central).
suitable_with(nonGlutinous,bangLen,good,northeast).
suitable_with(nonGlutinous,bangLen,good,south).
suitable_with(nonGlutinous,bangLen,good,north).
suitable_with(nonGlutinous,bacho,moderate,northeast).
suitable_with(nonGlutinous,bacho,bad,south).
suitable_with(nonGlutinous,bacho,bad,central).
suitable_with(nonGlutinous,bacho,none,north).
suitable_with(nonGlutinous,banChong,moderate,northeast).
suitable_with(nonGlutinous,banChong,bad,north).
suitable_with(nonGlutinous,banChong,bad,central).
suitable_with(nonGlutinous,banThon,bad,central).
suitable_with(nonGlutinous,banThon,bad,northeast).
suitable_with(nonGlutinous,banThon,bad,south).
suitable_with(nonGlutinous,banBung,moderate,north).
suitable_with(nonGlutinous,banBung,moderate,central).
suitable_with(nonGlutinous,banBung,moderate,northeast).
suitable_with(nonGlutinous,banBung,none,south).
suitable_with(nonGlutinous,banPhai,moderate,northeast).
suitable_with(nonGlutinous,banPhai,bad,central).
suitable_with(nonGlutinous,banPhai,bad,south).
suitable_with(nonGlutinous,banPhai,bad,north).
suitable_with(nonGlutinous,banPhot,good,northeast).
suitable_with(nonGlutinous,banPhot,good,central).
suitable_with(nonGlutinous,banPhot,good,north).
suitable_with(nonGlutinous,banMi,good,northeast).
suitable_with(nonGlutinous,banMi,good,central).
suitable_with(nonGlutinous,banMi,good,north).
suitable_with(nonGlutinous,bungChanang,moderate,northeast).
suitable_with(nonGlutinous,bungChanang,moderate,south).
suitable_with(nonGlutinous,bungChanang,bad,central).
suitable_with(nonGlutinous,bungChanang,bad,north).
suitable_with(nonGlutinous,bunthrik,good,central).
suitable_with(nonGlutinous,bunthrik,good,northeast).
suitable_with(nonGlutinous,bunthrik,good,south).
suitable_with(nonGlutinous,bunthrik,good,north).
suitable_with(nonGlutinous,buriRam,moderate,northeast).
suitable_with(nonGlutinous,buriRam,bad,central).
suitable_with(nonGlutinous,buriRam,bad,north).
suitable_with(nonGlutinous,padangBesar,bad,central).
suitable_with(nonGlutinous,padangBesar,bad,south).
suitable_with(nonGlutinous,pathiu,bad,central).
suitable_with(nonGlutinous,pathiu,bad,northeast).
suitable_with(nonGlutinous,pathiu,bad,south).
suitable_with(nonGlutinous,pathiu,none,north).
suitable_with(nonGlutinous,pakChan,bad,central).
suitable_with(nonGlutinous,pakChan,bad,northeast).
suitable_with(nonGlutinous,pakChan,bad,south).
suitable_with(nonGlutinous,pakChan,none,north).
suitable_with(nonGlutinous,pakChong,moderate,northeast).
suitable_with(nonGlutinous,pakChong,bad,central).
suitable_with(nonGlutinous,pakChong,bad,north).
suitable_with(nonGlutinous,pakTho,good,central).
suitable_with(nonGlutinous,pakTho,good,northeast).
suitable_with(nonGlutinous,pakTho,good,south).
suitable_with(nonGlutinous,pakTho,good,north).
suitable_with(nonGlutinous,pongThong,moderate,northeast).
suitable_with(nonGlutinous,pongThong,bad,central).
suitable_with(nonGlutinous,pongThong,bad,south).
suitable_with(nonGlutinous,pongThong,bad,north).
suitable_with(nonGlutinous,pongNamRon,moderate,northeast).
suitable_with(nonGlutinous,pongNamRon,bad,north).
suitable_with(nonGlutinous,pongNamRon,bad,central).
suitable_with(nonGlutinous,phakKat,good,south).
suitable_with(nonGlutinous,phakKat,good,north).
suitable_with(nonGlutinous,phakKat,good,central).
suitable_with(nonGlutinous,phakKat,moderate,northeast).
suitable_with(nonGlutinous,fangDaeng,bad,central).
suitable_with(nonGlutinous,fangDaeng,bad,south).
suitable_with(nonGlutinous,phato,bad,central).
suitable_with(nonGlutinous,phato,bad,northeast).
suitable_with(nonGlutinous,phato,bad,south).
suitable_with(nonGlutinous,phato,none,north).
suitable_with(nonGlutinous,phayomNgam,good,north).
suitable_with(nonGlutinous,phayomNgam,good,central).
suitable_with(nonGlutinous,phayomNgam,good,northeast).
suitable_with(nonGlutinous,phayomNgam,moderate,south).
suitable_with(nonGlutinous,phayao,bad,central).
suitable_with(nonGlutinous,phayao,bad,northeast).
suitable_with(nonGlutinous,phayao,bad,north).
suitable_with(nonGlutinous,phawong,good,central).
suitable_with(nonGlutinous,phawong,good,northeast).
suitable_with(nonGlutinous,phawong,good,south).
suitable_with(nonGlutinous,phawong,good,north).
suitable_with(nonGlutinous,pga,bad,central).
suitable_with(nonGlutinous,pga,bad,northeast).
suitable_with(nonGlutinous,pga,bad,south).
suitable_with(nonGlutinous,pga,none,north).
suitable_with(nonGlutinous,patthaya,moderate,northeast).
suitable_with(nonGlutinous,patthaya,bad,south).
suitable_with(nonGlutinous,patthaya,bad,central).
suitable_with(nonGlutinous,patthaya,none,north).
suitable_with(nonGlutinous,phatthalung,good,central).
suitable_with(nonGlutinous,phatthalung,good,northeast).
suitable_with(nonGlutinous,phatthalung,good,south).
suitable_with(nonGlutinous,phatthalung,good,north).
suitable_with(nonGlutinous,phan,good,south).
suitable_with(nonGlutinous,phan,good,north).
suitable_with(nonGlutinous,phan,good,central).
suitable_with(nonGlutinous,phan,moderate,northeast).
suitable_with(nonGlutinous,phanThong,good,central).
suitable_with(nonGlutinous,phanThong,good,northeast).
suitable_with(nonGlutinous,phanThong,good,south).
suitable_with(nonGlutinous,phanThong,good,north).
suitable_with(nonGlutinous,phimai,good,central).
suitable_with(nonGlutinous,phimai,good,northeast).
suitable_with(nonGlutinous,phimai,good,north).
suitable_with(nonGlutinous,phetchaburi,good,central).
suitable_with(nonGlutinous,phetchaburi,good,northeast).
suitable_with(nonGlutinous,phetchaburi,good,north).
suitable_with(nonGlutinous,phetchabun,moderate,northeast).
suitable_with(nonGlutinous,phetchabun,bad,north).
suitable_with(nonGlutinous,phetchabun,bad,central).
suitable_with(nonGlutinous,phen,good,central).
suitable_with(nonGlutinous,phen,good,northeast).
suitable_with(nonGlutinous,phen,good,north).
suitable_with(nonGlutinous,phen,moderate,south).
suitable_with(nonGlutinous,phonNgam,moderate,northeast).
suitable_with(nonGlutinous,phonNgam,bad,north).
suitable_with(nonGlutinous,phonNgam,bad,central).
suitable_with(nonGlutinous,phonPhisai,moderate,northeast).
suitable_with(nonGlutinous,phonPhisai,bad,central).
suitable_with(nonGlutinous,phonPhisai,bad,north).
suitable_with(nonGlutinous,phuket,bad,central).
suitable_with(nonGlutinous,phuket,bad,northeast).
suitable_with(nonGlutinous,phuket,bad,south).
suitable_with(nonGlutinous,phuket,none,north).
suitable_with(nonGlutinous,phuSana,moderate,northeast).
suitable_with(nonGlutinous,phuSana,bad,north).
suitable_with(nonGlutinous,phuSana,bad,central).
suitable_with(nonGlutinous,manorom,good,central).
suitable_with(nonGlutinous,manorom,good,northeast).
suitable_with(nonGlutinous,manorom,good,south).
suitable_with(nonGlutinous,manorom,good,north).
suitable_with(nonGlutinous,muakLek,moderate,northeast).
suitable_with(nonGlutinous,muakLek,bad,central).
suitable_with(nonGlutinous,muakLek,bad,north).
suitable_with(nonGlutinous,mahaPhot,good,central).
suitable_with(nonGlutinous,mahaPhot,good,northeast).
suitable_with(nonGlutinous,mahaPhot,good,south).
suitable_with(nonGlutinous,mahaPhot,good,north).
suitable_with(nonGlutinous,mahaSarakham,moderate,northeast).
suitable_with(nonGlutinous,mahaSarakham,bad,south).
suitable_with(nonGlutinous,mahaSarakham,bad,north).
suitable_with(nonGlutinous,mahaSarakham,bad,central).
suitable_with(nonGlutinous,makham,good,central).
suitable_with(nonGlutinous,makham,good,northeast).
suitable_with(nonGlutinous,makham,good,north).
suitable_with(nonGlutinous,munoh,moderate,central).
suitable_with(nonGlutinous,munoh,moderate,south).
suitable_with(nonGlutinous,maeTaeng,moderate,northeast).
suitable_with(nonGlutinous,maeTaeng,bad,north).
suitable_with(nonGlutinous,maeTaeng,bad,central).
suitable_with(nonGlutinous,maeTha,good,central).
suitable_with(nonGlutinous,maeTha,good,northeast).
suitable_with(nonGlutinous,maeTha,good,north).
suitable_with(nonGlutinous,maeRim,bad,central).
suitable_with(nonGlutinous,maeRim,bad,northeast).
suitable_with(nonGlutinous,maeRim,bad,north).
suitable_with(nonGlutinous,maeSai,good,central).
suitable_with(nonGlutinous,maeSai,good,northeast).
suitable_with(nonGlutinous,maeSai,good,north).
suitable_with(nonGlutinous,maiKhao,moderate,northeast).
suitable_with(nonGlutinous,maiKhao,bad,south).
suitable_with(nonGlutinous,maiKhao,bad,central).
suitable_with(nonGlutinous,maiKhao,none,north).
suitable_with(nonGlutinous,yasothon,bad,central).
suitable_with(nonGlutinous,yasothon,bad,northeast).
suitable_with(nonGlutinous,yasothon,bad,north).
suitable_with(nonGlutinous,yala,moderate,northeast).
suitable_with(nonGlutinous,yala,bad,south).
suitable_with(nonGlutinous,yala,bad,central).
suitable_with(nonGlutinous,yala,none,north).
suitable_with(nonGlutinous,yangTalat,moderate,northeast).
suitable_with(nonGlutinous,yangTalat,bad,north).
suitable_with(nonGlutinous,yangTalat,bad,central).
suitable_with(nonGlutinous,yanTaKao,good,central).
suitable_with(nonGlutinous,yanTaKao,good,northeast).
suitable_with(nonGlutinous,yanTaKao,good,north).
suitable_with(nonGlutinous,yanTaKao,moderate,south).
suitable_with(nonGlutinous,yi_ngo,moderate,south).
suitable_with(nonGlutinous,yi_ngo,bad,central).
suitable_with(nonGlutinous,roiEt,good,central).
suitable_with(nonGlutinous,roiEt,good,northeast).
suitable_with(nonGlutinous,roiEt,good,south).
suitable_with(nonGlutinous,roiEt,good,north).
suitable_with(nonGlutinous,rangae,good,central).
suitable_with(nonGlutinous,rangae,good,south).
suitable_with(nonGlutinous,ranong,moderate,south).
suitable_with(nonGlutinous,ranong,bad,central).
suitable_with(nonGlutinous,rayong,moderate,south).
suitable_with(nonGlutinous,rayong,bad,central).
suitable_with(nonGlutinous,rangsit,good,central).
suitable_with(nonGlutinous,rangsit,good,south).
suitable_with(nonGlutinous,rangsit,bad,northeast).
suitable_with(nonGlutinous,ratchaburi,good,central).
suitable_with(nonGlutinous,ratchaburi,good,northeast).
suitable_with(nonGlutinous,ratchaburi,good,north).
suitable_with(nonGlutinous,ruso,bad,central).
suitable_with(nonGlutinous,ruso,bad,south).
suitable_with(nonGlutinous,renu,good,central).
suitable_with(nonGlutinous,renu,good,northeast).
suitable_with(nonGlutinous,renu,good,south).
suitable_with(nonGlutinous,renu,good,north).
suitable_with(nonGlutinous,lopBuri,moderate,northeast).
suitable_with(nonGlutinous,lopBuri,bad,central).
suitable_with(nonGlutinous,lopBuri,bad,north).
suitable_with(nonGlutinous,laNgu,good,central).
suitable_with(nonGlutinous,laNgu,good,south).
suitable_with(nonGlutinous,laNgu,good,north).
suitable_with(nonGlutinous,laNgu,moderate,northeast).
suitable_with(nonGlutinous,lahan,bad,central).
suitable_with(nonGlutinous,lahan,bad,south).
suitable_with(nonGlutinous,latYa,moderate,northeast).
suitable_with(nonGlutinous,latYa,bad,central).
suitable_with(nonGlutinous,latYa,bad,north).
suitable_with(nonGlutinous,lamKaen,bad,central).
suitable_with(nonGlutinous,lamKaen,bad,south).
suitable_with(nonGlutinous,kamNarai,bad,central).
suitable_with(nonGlutinous,kamNarai,bad,northeast).
suitable_with(nonGlutinous,kamNarai,bad,north).
suitable_with(nonGlutinous,lampang,good,central).
suitable_with(nonGlutinous,lampang,good,northeast).
suitable_with(nonGlutinous,lampang,good,south).
suitable_with(nonGlutinous,lampang,good,north).
suitable_with(nonGlutinous,lamPhuLa,bad,central).
suitable_with(nonGlutinous,lamPhuLa,bad,northeast).
suitable_with(nonGlutinous,lamPhuLa,bad,south).
suitable_with(nonGlutinous,lamPhuLa,none,north).
suitable_with(nonGlutinous,lamSonthi,bad,central).
suitable_with(nonGlutinous,lamSonthi,bad,northeast).
suitable_with(nonGlutinous,lamSonthi,bad,north).
suitable_with(nonGlutinous,li,moderate,northeast).
suitable_with(nonGlutinous,li,bad,central).
suitable_with(nonGlutinous,li,bad,north).
suitable_with(nonGlutinous,loei,moderate,northeast).
suitable_with(nonGlutinous,loei,bad,central).
suitable_with(nonGlutinous,loei,bad,north).
suitable_with(nonGlutinous,wangChomphu,moderate,northeast).
suitable_with(nonGlutinous,wangChomphu,bad,central).
suitable_with(nonGlutinous,wangChomphu,bad,north).
suitable_with(nonGlutinous,wangTong,good,central).
suitable_with(nonGlutinous,wangTong,good,northeast).
suitable_with(nonGlutinous,wangTong,good,south).
suitable_with(nonGlutinous,wangTong,good,north).
suitable_with(nonGlutinous,wangSaphung,moderate,northeast).
suitable_with(nonGlutinous,wangSaphung,bad,north).
suitable_with(nonGlutinous,wangSaphung,bad,central).
suitable_with(nonGlutinous,wangHai,moderate,northeast).
suitable_with(nonGlutinous,wangHai,bad,north).
suitable_with(nonGlutinous,wangHai,bad,central).
suitable_with(nonGlutinous,watthana,good,northeast).
suitable_with(nonGlutinous,watthana,good,central).
suitable_with(nonGlutinous,watthana,good,north).
suitable_with(nonGlutinous,wanPriang,good,north).
suitable_with(nonGlutinous,wanPriang,moderate,central).
suitable_with(nonGlutinous,wanPriang,moderate,northeast).
suitable_with(nonGlutinous,wanPriang,moderate,south).
suitable_with(nonGlutinous,warin,bad,central).
suitable_with(nonGlutinous,warin,bad,northeast).
suitable_with(nonGlutinous,warin,bad,north).
suitable_with(nonGlutinous,wichianBuri,good,central).
suitable_with(nonGlutinous,wichianBuri,good,northeast).
suitable_with(nonGlutinous,wichianBuri,good,north).
suitable_with(nonGlutinous,visai,good,central).
suitable_with(nonGlutinous,visai,good,northeast).
suitable_with(nonGlutinous,visai,good,south).
suitable_with(nonGlutinous,visai,good,north).
suitable_with(nonGlutinous,siThep,good,central).
suitable_with(nonGlutinous,siThep,good,northeast).
suitable_with(nonGlutinous,siThep,good,south).
suitable_with(nonGlutinous,siThep,good,north).
suitable_with(nonGlutinous,siSongKhram,good,central).
suitable_with(nonGlutinous,siSongKhram,good,northeast).
suitable_with(nonGlutinous,siSongKhram,good,south).
suitable_with(nonGlutinous,siSongKhram,good,north).
suitable_with(nonGlutinous,sakon,moderate,northeast).
suitable_with(nonGlutinous,sakon,bad,north).
suitable_with(nonGlutinous,sakon,bad,central).
suitable_with(nonGlutinous,songkhla,good,central).
suitable_with(nonGlutinous,songkhla,good,northeast).
suitable_with(nonGlutinous,songkhla,good,south).
suitable_with(nonGlutinous,songkhla,good,north).
suitable_with(nonGlutinous,satuk,bad,central).
suitable_with(nonGlutinous,satuk,bad,northeast).
suitable_with(nonGlutinous,satuk,bad,north).
suitable_with(nonGlutinous,satun,good,central).
suitable_with(nonGlutinous,satun,good,northeast).
suitable_with(nonGlutinous,satun,good,south).
suitable_with(nonGlutinous,satun,good,north).
suitable_with(nonGlutinous,sopPrap,moderate,northeast).
suitable_with(nonGlutinous,sopPrap,bad,central).
suitable_with(nonGlutinous,sopPrap,bad,north).
suitable_with(nonGlutinous,samoThod,moderate,northeast).
suitable_with(nonGlutinous,samoThod,bad,north).
suitable_with(nonGlutinous,samoThod,bad,central).
suitable_with(nonGlutinous,samutPrakan,good,central).
suitable_with(nonGlutinous,samutPrakan,good,northeast).
suitable_with(nonGlutinous,samutPrakan,good,south).
suitable_with(nonGlutinous,samutPrakan,good,north).
suitable_with(nonGlutinous,sapphaya,good,central).
suitable_with(nonGlutinous,sapphaya,good,northeast).
suitable_with(nonGlutinous,sapphaya,good,north).
suitable_with(nonGlutinous,saraburi,good,central).
suitable_with(nonGlutinous,saraburi,good,northeast).
suitable_with(nonGlutinous,saraburi,good,north).
suitable_with(nonGlutinous,sawi,bad,central).
suitable_with(nonGlutinous,sawi,bad,northeast).
suitable_with(nonGlutinous,sawi,bad,south).
suitable_with(nonGlutinous,sawi,none,north).
suitable_with(nonGlutinous,sadao,bad,central).
suitable_with(nonGlutinous,sadao,bad,northeast).
suitable_with(nonGlutinous,sadao,bad,south).
suitable_with(nonGlutinous,saThon,good,central).
suitable_with(nonGlutinous,saThon,good,northeast).
suitable_with(nonGlutinous,saThon,good,north).
suitable_with(nonGlutinous,saThon,moderate,south).
suitable_with(nonGlutinous,sattahip,moderate,northeast).
suitable_with(nonGlutinous,sattahip,bad,south).
suitable_with(nonGlutinous,sattahip,bad,central).
suitable_with(nonGlutinous,sattahip,none,north).
suitable_with(nonGlutinous,sanSai,good,central).
suitable_with(nonGlutinous,sanSai,good,northeast).
suitable_with(nonGlutinous,sanSai,good,south).
suitable_with(nonGlutinous,sanSai,good,north).
suitable_with(nonGlutinous,sanPaTong,moderate,northeast).
suitable_with(nonGlutinous,sanPaTong,bad,central).
suitable_with(nonGlutinous,sanPaTong,bad,north).
suitable_with(nonGlutinous,saiBuri,good,central).
suitable_with(nonGlutinous,saiBuri,good,northeast).
suitable_with(nonGlutinous,saiBuri,good,south).
suitable_with(nonGlutinous,saiBuri,good,north).
suitable_with(nonGlutinous,singBuri,good,central).
suitable_with(nonGlutinous,singBuri,good,northeast).
suitable_with(nonGlutinous,singBuri,good,north).
suitable_with(nonGlutinous,siKhiu,moderate,northeast).
suitable_with(nonGlutinous,siKhiu,bad,north).
suitable_with(nonGlutinous,siKhiu,bad,central).
suitable_with(nonGlutinous,siThon,good,central).
suitable_with(nonGlutinous,siThon,good,northeast).
suitable_with(nonGlutinous,siThon,good,south).
suitable_with(nonGlutinous,siThon,good,north).
suitable_with(nonGlutinous,surin,moderate,northeast).
suitable_with(nonGlutinous,surin,bad,south).
suitable_with(nonGlutinous,surin,bad,north).
suitable_with(nonGlutinous,surin,bad,central).
suitable_with(nonGlutinous,sungaiGolok,good,central).
suitable_with(nonGlutinous,sungaiGolok,good,northeast).
suitable_with(nonGlutinous,sungaiGolok,good,south).
suitable_with(nonGlutinous,sungaiGolok,good,north).
suitable_with(nonGlutinous,sungaiPadi,good,central).
suitable_with(nonGlutinous,sungaiPadi,good,northeast).
suitable_with(nonGlutinous,sungaiPadi,good,south).
suitable_with(nonGlutinous,sungaiPadi,good,north).
suitable_with(nonGlutinous,sungNoen,moderate,northeast).
suitable_with(nonGlutinous,sungNoen,bad,central).
suitable_with(nonGlutinous,sungNoen,bad,north).
suitable_with(nonGlutinous,sena,good,central).
suitable_with(nonGlutinous,sena,good,south).
suitable_with(nonGlutinous,sena,bad,northeast).
suitable_with(nonGlutinous,nongKae,good,central).
suitable_with(nonGlutinous,nongKae,moderate,northeast).
suitable_with(nonGlutinous,nongKhla,moderate,northeast).
suitable_with(nonGlutinous,nongKhla,bad,south).
suitable_with(nonGlutinous,nongKhla,bad,central).
suitable_with(nonGlutinous,nongKhla,none,north).
suitable_with(nonGlutinous,nongBon,bad,central).
suitable_with(nonGlutinous,nongBon,none,north).
suitable_with(nonGlutinous,nongMot,moderate,northeast).
suitable_with(nonGlutinous,nongMot,bad,central).
suitable_with(nonGlutinous,nongMot,bad,north).
suitable_with(nonGlutinous,lomKao,good,central).
suitable_with(nonGlutinous,lomKao,good,northeast).
suitable_with(nonGlutinous,lomKao,good,south).
suitable_with(nonGlutinous,lomKao,good,north).
suitable_with(nonGlutinous,lomSak,good,central).
suitable_with(nonGlutinous,lomSak,good,northeast).
suitable_with(nonGlutinous,lomSak,good,north).
suitable_with(nonGlutinous,langSuan,moderate,northeast).
suitable_with(nonGlutinous,langSuan,bad,south).
suitable_with(nonGlutinous,langSuan,bad,central).
suitable_with(nonGlutinous,langSuan,none,north).
suitable_with(nonGlutinous,huaiPong,bad,central).
suitable_with(nonGlutinous,huaiPong,bad,northeast).
suitable_with(nonGlutinous,huaiPong,bad,south).
suitable_with(nonGlutinous,huaiPong,none,north).
suitable_with(nonGlutinous,huaiYot,moderate,south).
suitable_with(nonGlutinous,huaiYot,bad,central).
suitable_with(nonGlutinous,huaHin,moderate,northeast).
suitable_with(nonGlutinous,huaHin,bad,central).
suitable_with(nonGlutinous,huaHin,bad,south).
suitable_with(nonGlutinous,huaHin,none,north).
suitable_with(nonGlutinous,hangChat,moderate,northeast).
suitable_with(nonGlutinous,hangChat,bad,north).
suitable_with(nonGlutinous,hangChat,bad,central).
suitable_with(nonGlutinous,hangDong,good,central).
suitable_with(nonGlutinous,hangDong,good,south).
suitable_with(nonGlutinous,hangDong,good,north).
suitable_with(nonGlutinous,hangDong,moderate,northeast).
suitable_with(nonGlutinous,hatYai,moderate,northeast).
suitable_with(nonGlutinous,hatYai,bad,south).
suitable_with(nonGlutinous,hatYai,bad,central).
suitable_with(nonGlutinous,hatYai,none,north).
suitable_with(nonGlutinous,hinKong,good,central).
suitable_with(nonGlutinous,hinKong,good,northeast).
suitable_with(nonGlutinous,hinKong,good,south).
suitable_with(nonGlutinous,hinKong,good,north).
suitable_with(nonGlutinous,hupKrapong,moderate,northeast).
suitable_with(nonGlutinous,hupKrapong,bad,north).
suitable_with(nonGlutinous,hupKrapong,bad,central).
suitable_with(nonGlutinous,ongkharak,moderate,central).
suitable_with(nonGlutinous,ongkharak,moderate,south).
suitable_with(nonGlutinous,on,good,central).
suitable_with(nonGlutinous,on,good,northeast).
suitable_with(nonGlutinous,on,good,north).
suitable_with(nonGlutinous,on,moderate,south).
suitable_with(nonGlutinous,ayutthaya,good,central).
suitable_with(nonGlutinous,ayutthaya,good,northeast).
suitable_with(nonGlutinous,ayutthaya,good,south).
suitable_with(nonGlutinous,ayutthaya,good,north).
suitable_with(nonGlutinous,aoLuk,bad,central).
suitable_with(nonGlutinous,aoLuk,bad,northeast).
suitable_with(nonGlutinous,aoLuk,bad,south).
suitable_with(nonGlutinous,aoLuk,none,north).
suitable_with(nonGlutinous,udon,good,central).
suitable_with(nonGlutinous,udon,moderate,northeast).
suitable_with(nonGlutinous,uttaradit,good,south).
suitable_with(nonGlutinous,uttaradit,good,north).
suitable_with(nonGlutinous,uttaradit,good,central).
suitable_with(nonGlutinous,uttaradit,moderate,northeast).
suitable_with(nonGlutinous,ubon,moderate,north).
suitable_with(nonGlutinous,ubon,moderate,central).
suitable_with(nonGlutinous,ubon,moderate,northeast).
suitable_with(nonGlutinous,ubon,none,south).
suitable_with(nonGlutinous,oLamChiak,bad,central).
suitable_with(nonGlutinous,oLamChiak,bad,south).