:- module(rice_growth, []).
% grows_well_in(sub_district,rice_species,harvesting_season).
grows_well_in(niawsan_pah_tawng,chaem_luang,inSeason).
grows_well_in(rd6,khuang_pao,inSeason).
grows_well_in(jasmine105,khuang_pao,inSeason).
grows_well_in(niawsan_pah_tawng,khuang_pao,inSeason).
grows_well_in(rd6,doi_kaeo,inSeason).
grows_well_in(jasmine105,doi_kaeo,inSeason).
grows_well_in(niawsan_pah_tawng,doi_kaeo,inSeason).
grows_well_in(san_pah_tawng1,ban_pae,inSeason).
grows_well_in(rd6,ban_pae,inSeason).
grows_well_in(jasmine105,ban_pae,inSeason).
grows_well_in(rd6,ban_luang,inSeason).
grows_well_in(jasmine105,ban_luang,inSeason).
grows_well_in(niawsan_pah_tawng,ban_luang,inSeason).
grows_well_in(san_pah_tawng1,mae_soi,inSeason).
grows_well_in(rd6,mae_soi,inSeason).
grows_well_in(jasmine105,mae_soi,inSeason).
grows_well_in(san_pah_tawng1,sop_tia,inSeason).
grows_well_in(rd6,sop_tia,inSeason).
grows_well_in(jasmine105,sop_tia,inSeason).
grows_well_in(san_pah_tawng1,chiang_dao,inSeason).
grows_well_in(rd6,chiang_dao,inSeason).
grows_well_in(jasmine105,chiang_dao,inSeason).
grows_well_in(san_pah_tawng1,thung_khao_phuang,inSeason).
grows_well_in(rd7,thung_khao_phuang,inSeason).
grows_well_in(jasmine105,thung_khao_phuang,inSeason).
grows_well_in(jowhaw,ping_khong,inSeason).
grows_well_in(san_pah_tawng1,ping_khong,inSeason).
grows_well_in(jasmine105,ping_khong,inSeason).
grows_well_in(san_pah_tawng1,mueang_khong,inSeason).
grows_well_in(rd6,mueang_khong,inSeason).
grows_well_in(mueynawng62m,mueang_khong,inSeason).
grows_well_in(san_pah_tawng1,mueang_ngai,inSeason).
grows_well_in(rd6,mueang_ngai,inSeason).
grows_well_in(jasmine105,mueang_ngai,inSeason).
grows_well_in(jowhaw,mueang_na,inSeason).
grows_well_in(san_pah_tawng1,mueang_na,inSeason).
grows_well_in(jasmine105,mueang_na,inSeason).
grows_well_in(san_pah_tawng1,mae_na,inSeason).
grows_well_in(rd6,mae_na,inSeason).
grows_well_in(jasmine105,mae_na,inSeason).
grows_well_in(san_pah_tawng1,pong_tam,inSeason).
grows_well_in(rd6,pong_tam,inSeason).
grows_well_in(rd15,pong_tam,inSeason).
grows_well_in(san_pah_tawng1,mae_thalop,inSeason).
grows_well_in(rd6,mae_thalop,inSeason).
grows_well_in(san_pah_tawng1,si_dong_yen,inSeason).
grows_well_in(rd6,si_dong_yen,inSeason).
grows_well_in(jasmine105,si_dong_yen,inSeason).
grows_well_in(san_pah_tawng1,nong_bua,inSeason).
grows_well_in(rd6,nong_bua,inSeason).
grows_well_in(jasmine105,nong_bua,inSeason).
grows_well_in(san_pah_tawng1,doi_tao,inSeason).
grows_well_in(rd6,doi_tao,inSeason).
grows_well_in(san_pah_tawng1,tha_duea,inSeason).
grows_well_in(rd6,tha_duea,inSeason).
grows_well_in(jasmine105,tha_duea,inSeason).
grows_well_in(san_pah_tawng1,tha_duea,inSeason).
grows_well_in(rd6,tha_duea,inSeason).
grows_well_in(rd10,tha_duea,inSeason).
grows_well_in(jasmine105,ban_aen,inSeason).
grows_well_in(san_pah_tawng1,pong_thung,inSeason).
grows_well_in(rd6,pong_thung,inSeason).
grows_well_in(jasmine105,pong_thung,inSeason).
grows_well_in(san_pah_tawng1,muet_ka,inSeason).
grows_well_in(rd6,muet_ka,inSeason).
grows_well_in(jasmine105,muet_ka,inSeason).
grows_well_in(san_pah_tawng1,choeng_doi,inSeason).
grows_well_in(rd6,choeng_doi,inSeason).
grows_well_in(jasmine105,choeng_doi,inSeason).
grows_well_in(jasmine105,talat_khwan,inSeason).
grows_well_in(san_pah_tawng1,talat_khwan,inSeason).
grows_well_in(pathumthani1,talat_khwan,inSeason).
grows_well_in(jasmine105,talat_yai,inSeason).
grows_well_in(san_pah_tawng1,talat_yai,inSeason).
grows_well_in(phitsanulok2,talat_yai,inSeason).
grows_well_in(rd21,thep_sadet,inSeason).
grows_well_in(sewmaejan,thep_sadet,inSeason).
grows_well_in(jasmine105,pa_pong,inSeason).
grows_well_in(san_pah_tawng1,pa_pong,inSeason).
grows_well_in(rd6,pa_pong,inSeason).
grows_well_in(san_pah_tawng1,pa_miang,inSeason).
grows_well_in(rd6,pa_miang,inSeason).
grows_well_in(jasmine105,pa_lan,inSeason).
grows_well_in(san_pah_tawng1,pa_lan,inSeason).
grows_well_in(rd6,pa_lan,inSeason).
grows_well_in(jasmine105,mae_khue,inSeason).
grows_well_in(san_pah_tawng1,mae_khue,inSeason).
grows_well_in(phitsanulok2,mae_khue,inSeason).
grows_well_in(jasmine105,mae_pong,inSeason).
grows_well_in(san_pah_tawng1,mae_pong,inSeason).
grows_well_in(rd6,mae_pong,inSeason).
grows_well_in(jasmine105,mae_hoi_ngoen,inSeason).
grows_well_in(san_pah_tawng1,mae_hoi_ngoen,inSeason).
grows_well_in(rd6,mae_hoi_ngoen,inSeason).
grows_well_in(jasmine105,luang_nuea,inSeason).
grows_well_in(san_pah_tawng1,luang_nuea,inSeason).
grows_well_in(rd6,luang_nuea,inSeason).
grows_well_in(jasmine105,sa_nga_ban,inSeason).
grows_well_in(san_pah_tawng1,sa_nga_ban,inSeason).
grows_well_in(phitsanulok2,sa_nga_ban,inSeason).
grows_well_in(jasmine105,san_pu_loei,inSeason).
grows_well_in(san_pah_tawng1,san_pu_loei,inSeason).
grows_well_in(suphanburi3,san_pu_loei,inSeason).
grows_well_in(jasmine105,samran_rat,inSeason).
grows_well_in(san_pah_tawng1,samran_rat,inSeason).
grows_well_in(rd6,samran_rat,inSeason).
grows_well_in(jasmine105,doi_lo,inSeason).
grows_well_in(san_pah_tawng1,doi_lo,inSeason).
grows_well_in(rd6,doi_lo,inSeason).
grows_well_in(jasmine105,yang_khram,inSeason).
grows_well_in(san_pah_tawng1,yang_khram,inSeason).
grows_well_in(rd6,yang_khram,inSeason).
grows_well_in(san_pah_tawng1,song_khwae,inSeason).
grows_well_in(rd1,song_khwae,inSeason).
grows_well_in(pathumthani1,song_khwae,inSeason).
grows_well_in(jasmine105,santi_suk,inSeason).
grows_well_in(san_pah_tawng1,santi_suk,inSeason).
grows_well_in(rd6,santi_suk,inSeason).
grows_well_in(san_pah_tawng1,pong_nam_ron,inSeason).
grows_well_in(rd6,pong_nam_ron,inSeason).
grows_well_in(rd1,pong_nam_ron,inSeason).
grows_well_in(san_pah_tawng1,mon_pin,inSeason).
grows_well_in(rd6,mon_pin,inSeason).
grows_well_in(jowhaw,mon_pin,inSeason).
grows_well_in(san_pah_tawng1,mae_kha,inSeason).
grows_well_in(rd6,mae_kha,inSeason).
grows_well_in(jowhaw,mae_kha,inSeason).
grows_well_in(san_pah_tawng1,mae_kha,inSeason).
grows_well_in(rd6,mae_kha,inSeason).
grows_well_in(jowhaw,mae_kha,inSeason).
grows_well_in(san_pah_tawng1,mae_ngon,inSeason).
grows_well_in(rd6,mae_ngon,inSeason).
grows_well_in(rd15,mae_ngon,inSeason).
grows_well_in(san_pah_tawng1,mae_sun,inSeason).
grows_well_in(rd6,mae_sun,inSeason).
grows_well_in(rd15,mae_sun,inSeason).
grows_well_in(jasmine105,wiang,inSeason).
grows_well_in(san_pah_tawng1,wiang,inSeason).
grows_well_in(rd6,wiang,inSeason).
grows_well_in(san_pah_tawng1,san_sai,inSeason).
grows_well_in(rd6,san_sai,inSeason).
grows_well_in(rd15,san_sai,inSeason).
grows_well_in(jasmine105,khuean_phak,inSeason).
grows_well_in(san_pah_tawng1,khuean_phak,inSeason).
grows_well_in(rd6,khuean_phak,inSeason).
grows_well_in(jasmine105,thung_luang,inSeason).
grows_well_in(san_pah_tawng1,thung_luang,inSeason).
grows_well_in(jasmine105,nam_phrae,inSeason).
grows_well_in(san_pah_tawng1,nam_phrae,inSeason).
grows_well_in(rd6,nam_phrae,inSeason).
grows_well_in(jasmine105,ban_pong,inSeason).
grows_well_in(san_pah_tawng1,ban_pong,inSeason).
grows_well_in(rd6,ban_pong,inSeason).
grows_well_in(jasmine105,pa_tum,inSeason).
grows_well_in(san_pah_tawng1,pa_tum,inSeason).
grows_well_in(rd6,pa_tum,inSeason).
grows_well_in(jasmine105,pa_nai,inSeason).
grows_well_in(san_pah_tawng1,pa_nai,inSeason).
grows_well_in(jasmine105,mae_pang,inSeason).
grows_well_in(san_pah_tawng1,mae_pang,inSeason).
grows_well_in(jasmine105,mae_waen,inSeason).
grows_well_in(san_pah_tawng1,mae_waen,inSeason).
grows_well_in(jasmine105,wiang,inSeason).
grows_well_in(san_pah_tawng1,wiang,inSeason).
grows_well_in(rd6,wiang,inSeason).
grows_well_in(jasmine105,san_sai,inSeason).
grows_well_in(rd6,san_sai,inSeason).
grows_well_in(jasmine105,long_khot,inSeason).
grows_well_in(san_pah_tawng1,long_khot,inSeason).
grows_well_in(rd6,long_khot,inSeason).
grows_well_in(pathumthani1,tha_sala,inSeason).
grows_well_in(san_pah_tawng1,tha_sala,inSeason).
grows_well_in(rd6,tha_sala,inSeason).
grows_well_in(jasmine105,pa_daet,inSeason).
grows_well_in(san_pah_tawng1,pa_daet,inSeason).
grows_well_in(rd6,pa_daet,inSeason).
grows_well_in(pathumthani1,mae_hia,inSeason).
grows_well_in(jasmine105,mae_hia,inSeason).
grows_well_in(rd6,mae_hia,inSeason).
grows_well_in(pathumthani1,san_phisuea,inSeason).
grows_well_in(san_pah_tawng1,san_phisuea,inSeason).
grows_well_in(rd6,san_phisuea,inSeason).
grows_well_in(jasmine105,suthep,inSeason).
grows_well_in(san_pah_tawng1,nong_hoi,inSeason).
grows_well_in(namroo,kong_khaek,inSeason).
grows_well_in(jowhaw,kong_khaek,inSeason).
grows_well_in(khaoluangsan_pah_twang,kong_khaek,inSeason).
grows_well_in(san_pah_tawng1,chang_khoeng,inSeason).
grows_well_in(namroo,chang_khoeng,inSeason).
grows_well_in(rd6,chang_khoeng,inSeason).
grows_well_in(san_pah_tawng1,tha_pha,inSeason).
grows_well_in(namroo,tha_pha,inSeason).
grows_well_in(jowhaw,tha_pha,inSeason).
grows_well_in(namroo,ban_thap,inSeason).
grows_well_in(jowhaw,ban_thap,inSeason).
grows_well_in(khaoluangsan_pah_twang,ban_thap,inSeason).
grows_well_in(namroo,pang_hin_fon,inSeason).
grows_well_in(jowhaw,pang_hin_fon,inSeason).
grows_well_in(khaoluangsan_pah_twang,pang_hin_fon,inSeason).
grows_well_in(san_pah_tawng1,mae_na_chon,inSeason).
grows_well_in(namroo,mae_na_chon,inSeason).
grows_well_in(namroo,mae_suek,inSeason).
grows_well_in(jowhaw,mae_suek,inSeason).
grows_well_in(san_pah_tawng1,kuet_chang,inSeason).
grows_well_in(jasmine105,khi_lek,inSeason).
grows_well_in(san_pah_tawng1,khi_lek,inSeason).
grows_well_in(rd6,khi_lek,inSeason).
grows_well_in(jasmine105,cho_lae,inSeason).
grows_well_in(san_pah_tawng1,cho_lae,inSeason).
grows_well_in(rd6,cho_lae,inSeason).
grows_well_in(san_pah_tawng1,ban_chang,inSeason).
grows_well_in(rd6,ban_pao,inSeason).
grows_well_in(san_pah_tawng1,ban_pao,inSeason).
grows_well_in(san_pah_tawng1,pa_pae,inSeason).
grows_well_in(jowhaw,mueang_kai,inSeason).
grows_well_in(jasmine105,mae_taeng,inSeason).
grows_well_in(san_pah_tawng1,mae_taeng,inSeason).
grows_well_in(rd6,mae_taeng,inSeason).
grows_well_in(rd6,mae_ho_phra,inSeason).
grows_well_in(san_pah_tawng1,mae_ho_phra,inSeason).
grows_well_in(jasmine105,sop_poeng,inSeason).
grows_well_in(san_pah_tawng1,sop_poeng,inSeason).
grows_well_in(rd6,sop_poeng,inSeason).
grows_well_in(jasmine105,san_pa_yang,inSeason).
grows_well_in(san_pah_tawng1,san_pa_yang,inSeason).
grows_well_in(rd6,san_pa_yang,inSeason).
grows_well_in(jasmine105,san_mahaphon,inSeason).
grows_well_in(san_pah_tawng1,san_mahaphon,inSeason).
grows_well_in(rd6,san_mahaphon,inSeason).
grows_well_in(jasmine105,inthakhin,inSeason).
grows_well_in(san_pah_tawng1,inthakhin,inSeason).
grows_well_in(rd6,inthakhin,inSeason).
grows_well_in(jasmine105,khi_lek,inSeason).
grows_well_in(san_pah_tawng1,khi_lek,inSeason).
grows_well_in(rd6,khi_lek,inSeason).
grows_well_in(san_pah_tawng1,don_kaeo,inSeason).
grows_well_in(suphanburi3,don_kaeo,inSeason).
grows_well_in(sewmaejan,pong_yaeng,inSeason).
grows_well_in(san_pah_tawng1,pong_yaeng,inSeason).
grows_well_in(san_pah_tawng1,mae_raem,inSeason).
grows_well_in(jasmine105,mae_raem,inSeason).
grows_well_in(san_pah_tawng1,mae_sa,inSeason).
grows_well_in(jasmine105,mae_sa,inSeason).
grows_well_in(pathumthani1,mae_sa,inSeason).
grows_well_in(san_pah_tawng1,rim_tai,inSeason).
grows_well_in(jasmine105,rim_tai,inSeason).
grows_well_in(pathumthani1,rim_tai,inSeason).
grows_well_in(san_pah_tawng1,rim_nuea,inSeason).
grows_well_in(jasmine105,rim_nuea,inSeason).
grows_well_in(pathumthani1,rim_nuea,inSeason).
grows_well_in(san_pah_tawng1,saluang,inSeason).
grows_well_in(jasmine105,saluang,inSeason).
grows_well_in(jasmine105,san_pong,inSeason).
grows_well_in(san_pah_tawng1,san_pong,inSeason).
grows_well_in(rd6,san_pong,inSeason).
grows_well_in(jasmine105,huai_sai,inSeason).
grows_well_in(san_pah_tawng1,huai_sai,inSeason).
grows_well_in(rd6,huai_sai,inSeason).
grows_well_in(pathumthani1,mueang_kaeo,inSeason).
grows_well_in(san_pah_tawng1,mueang_kaeo,inSeason).
grows_well_in(rd6,mueang_kaeo,inSeason).
grows_well_in(jasmine105,don_pao,inSeason).
grows_well_in(san_pah_tawng1,don_pao,inSeason).
grows_well_in(rd10,don_pao,inSeason).
grows_well_in(san_pah_tawng1,thung_pi,inSeason).
grows_well_in(rd6,thung_pi,inSeason).
grows_well_in(rd10,thung_pi,inSeason).
grows_well_in(san_pah_tawng1,thung_ruang_thong,inSeason).
grows_well_in(rd6,thung_ruang_thong,inSeason).
grows_well_in(niawsan_pah_tawng,thung_ruang_thong,inSeason).
grows_well_in(san_pah_tawng1,ban_kat,inSeason).
grows_well_in(pathumthani1,ban_kat,inSeason).
grows_well_in(rd10,ban_kat,inSeason).
grows_well_in(rd7,mae_win,inSeason).
grows_well_in(san_pah_tawng1,mae_win,inSeason).
grows_well_in(jasmine105,tha_nuea,inSeason).
grows_well_in(san_pah_tawng1,tha_nuea,inSeason).
grows_well_in(rd6,tha_nuea,inSeason).
grows_well_in(jasmine105,ban_sahakon,inSeason).
grows_well_in(san_pah_tawng1,ban_sahakon,inSeason).
grows_well_in(pathumthani1,ban_sahakon,inSeason).
grows_well_in(jasmine105,mae_tha,inSeason).
grows_well_in(san_pah_tawng1,mae_tha,inSeason).
grows_well_in(pathumthani1,mae_tha,inSeason).
grows_well_in(jasmine105,huai_kaeo,inSeason).
grows_well_in(san_pah_tawng1,huai_kaeo,inSeason).
grows_well_in(rd6,huai_kaeo,inSeason).
grows_well_in(jasmine105,on_klang,inSeason).
grows_well_in(san_pah_tawng1,on_klang,inSeason).
grows_well_in(rd6,on_klang,inSeason).
grows_well_in(jasmine105,on_nuea,inSeason).
grows_well_in(san_pah_tawng1,on_nuea,inSeason).
grows_well_in(rd6,on_nuea,inSeason).
grows_well_in(rd6,tha_ton,inSeason).
grows_well_in(rd15,tha_ton,inSeason).
grows_well_in(rd6,ban_luang,inSeason).
grows_well_in(san_pah_tawng1,ban_luang,inSeason).
grows_well_in(rd6,malika,inSeason).
grows_well_in(rd15,malika,inSeason).
grows_well_in(san_pah_tawng1,mae_na_wang,inSeason).
grows_well_in(rd6,mae_na_wang,inSeason).
grows_well_in(rd6,mae_sao,inSeason).
grows_well_in(rd15,mae_sao,inSeason).
grows_well_in(jasmine105,mae_sao,inSeason).
grows_well_in(rd6,mae_ai,inSeason).
grows_well_in(rd15,mae_ai,inSeason).
grows_well_in(jasmine105,mae_ai,inSeason).
grows_well_in(san_pah_tawng1,san_ton_mue,inSeason).
grows_well_in(rd6,san_ton_mue,inSeason).
grows_well_in(jasmine105,san_ton_mue,inSeason).
grows_well_in(san_pah_tawng1,piang_luang,inSeason).
grows_well_in(rd6,piang_luang,inSeason).
grows_well_in(san_pah_tawng1,mueang_haeng,inSeason).
grows_well_in(rd6,mueang_haeng,inSeason).
grows_well_in(san_pah_tawng1,saen_hai,inSeason).
grows_well_in(rd6,saen_hai,inSeason).
grows_well_in(rd7,bo_kaeo,inSeason).
grows_well_in(pathumthani1,bo_kaeo,inSeason).
grows_well_in(rd6,mae_sap,inSeason).
grows_well_in(san_pah_tawng1,yung_moen,inSeason).
grows_well_in(rd6,yung_moen,inSeason).
grows_well_in(san_pah_tawng1,samoeng_tai,inSeason).
grows_well_in(rd6,samoeng_tai,inSeason).
grows_well_in(san_pah_tawng1,samoeng_nuea,inSeason).
grows_well_in(rd6,samoeng_nuea,inSeason).
grows_well_in(san_pah_tawng1,chae_chang,inSeason).
grows_well_in(jasmine105,chae_chang,inSeason).
grows_well_in(pathumthani1,chae_chang,inSeason).
grows_well_in(suphanburi1,ton_pao,inSeason).
grows_well_in(phitsanulok2,ton_pao,inSeason).
grows_well_in(san_pah_tawng1,ton_pao,inSeason).
grows_well_in(san_pah_tawng1,sai_mun,inSeason).
grows_well_in(jasmine105,sai_mun,inSeason).
grows_well_in(pathumthani1,sai_mun,inSeason).
grows_well_in(suphanburi1,buak_khang,inSeason).
grows_well_in(phitsanulok2,buak_khang,inSeason).
grows_well_in(san_pah_tawng1,buak_khang,inSeason).
grows_well_in(san_pah_tawng1,mae_pu_kha,inSeason).
grows_well_in(jasmine105,mae_pu_kha,inSeason).
grows_well_in(phitsanulok2,mae_pu_kha,inSeason).
grows_well_in(san_pah_tawng1,rong_wua_daeng,inSeason).
grows_well_in(jasmine105,rong_wua_daeng,inSeason).
grows_well_in(pathumthani1,rong_wua_daeng,inSeason).
grows_well_in(san_pah_tawng1,san_klang,inSeason).
grows_well_in(jasmine105,san_klang,inSeason).
grows_well_in(phitsanulok2,san_klang,inSeason).
grows_well_in(phitsanulok2,san_kamphaeng,inSeason).
grows_well_in(suphanburi3,san_kamphaeng,inSeason).
grows_well_in(san_pah_tawng1,san_kamphaeng,inSeason).
grows_well_in(jasmine105,huai_sai,inSeason).
grows_well_in(rd6,huai_sai,inSeason).
grows_well_in(pathumthani1,on_tai,inSeason).
grows_well_in(jasmine105,pa_phai,inSeason).
grows_well_in(san_pah_tawng1,pa_phai,inSeason).
grows_well_in(rd6,pa_phai,inSeason).
grows_well_in(jasmine105,mueang_len,inSeason).
grows_well_in(san_pah_tawng1,mueang_len,inSeason).
grows_well_in(phitsanulok2,mueang_len,inSeason).
grows_well_in(san_pah_tawng1,mae_faek,inSeason).
grows_well_in(suphanburi1,mae_faek,inSeason).
grows_well_in(pathumthani1,mae_faek,inSeason).
grows_well_in(san_pah_tawng1,mae_faek_mai,inSeason).
grows_well_in(suphanburi1,mae_faek_mai,inSeason).
grows_well_in(pathumthani1,mae_faek_mai,inSeason).
grows_well_in(jasmine105,san_sai_noi,inSeason).
grows_well_in(san_pah_tawng1,san_sai_noi,inSeason).
grows_well_in(rd6,san_sai_noi,inSeason).
grows_well_in(jasmine105,san_sai_luang,inSeason).
grows_well_in(san_pah_tawng1,san_sai_luang,inSeason).
grows_well_in(pathumthani1,san_sai_luang,inSeason).
grows_well_in(jasmine105,san_na_meng,inSeason).
grows_well_in(rd6,san_na_meng,inSeason).
grows_well_in(pathumthani1,san_na_meng,inSeason).
grows_well_in(jasmine105,san_pa_pao,inSeason).
grows_well_in(san_pah_tawng1,san_pa_pao,inSeason).
grows_well_in(pathumthani1,san_pa_pao,inSeason).
grows_well_in(jasmine105,san_phranet,inSeason).
grows_well_in(san_pah_tawng1,san_phranet,inSeason).
grows_well_in(pathumthani1,san_phranet,inSeason).
grows_well_in(jasmine105,nong_chom,inSeason).
grows_well_in(san_pah_tawng1,nong_chom,inSeason).
grows_well_in(pathumthani1,nong_chom,inSeason).
grows_well_in(jasmine105,nong_han,inSeason).
grows_well_in(san_pah_tawng1,nong_han,inSeason).
grows_well_in(pathumthani1,nong_han,inSeason).
grows_well_in(jasmine105,nong_yaeng,inSeason).
grows_well_in(san_pah_tawng1,nong_yaeng,inSeason).
grows_well_in(rd6,nong_yaeng,inSeason).
grows_well_in(jasmine105,tha_wang_phrao,inSeason).
grows_well_in(san_pah_tawng1,tha_wang_phrao,inSeason).
grows_well_in(rd6,tha_wang_phrao,inSeason).
grows_well_in(jasmine105,tung_tom,inSeason).
grows_well_in(san_pah_tawng1,tung_tom,inSeason).
grows_well_in(rd6,tung_tom,inSeason).
grows_well_in(san_pah_tawng1,thung_satok,inSeason).
grows_well_in(rd6,thung_satok,inSeason).
grows_well_in(jasmine105,nam_bo_luang,inSeason).
grows_well_in(san_pah_tawng1,nam_bo_luang,inSeason).
grows_well_in(suphanburi3,nam_bo_luang,inSeason).
grows_well_in(jasmine105,ban_klang,inSeason).
grows_well_in(san_pah_tawng1,ban_klang,inSeason).
grows_well_in(rd6,ban_klang,inSeason).
grows_well_in(jasmine105,ban_mae,inSeason).
grows_well_in(san_pah_tawng1,ban_mae,inSeason).
grows_well_in(rd6,ban_mae,inSeason).
grows_well_in(jasmine105,makham_luang,inSeason).
grows_well_in(san_pah_tawng1,makham_luang,inSeason).
grows_well_in(rd6,makham_luang,inSeason).
grows_well_in(jasmine105,makhun_wan,inSeason).
grows_well_in(san_pah_tawng1,makhun_wan,inSeason).
grows_well_in(rd6,makhun_wan,inSeason).
grows_well_in(jasmine105,mae_ka,inSeason).
grows_well_in(san_pah_tawng1,mae_ka,inSeason).
grows_well_in(rd6,mae_ka,inSeason).
grows_well_in(jasmine105,yu_wa,inSeason).
grows_well_in(san_pah_tawng1,yu_wa,inSeason).
grows_well_in(rd6,yu_wa,inSeason).
grows_well_in(jasmine105,san_klang,inSeason).
grows_well_in(san_pah_tawng1,san_klang,inSeason).
grows_well_in(rd6,san_klang,inSeason).
grows_well_in(jasmine105,khua_mung,inSeason).
grows_well_in(san_pah_tawng1,khua_mung,inSeason).
grows_well_in(rd6,khua_mung,inSeason).
grows_well_in(san_pah_tawng1,chomphu,inSeason).
grows_well_in(suphanburi1,chomphu,inSeason).
grows_well_in(phitsanulok2,chomphu,inSeason).
grows_well_in(san_pah_tawng1,chaiya_sathan,inSeason).
grows_well_in(suphanburi1,chaiya_sathan,inSeason).
grows_well_in(phitsanulok2,chaiya_sathan,inSeason).
grows_well_in(rd6,don_kaeo,inSeason).
grows_well_in(san_pah_tawng1,don_kaeo,inSeason).
grows_well_in(pathumthani1,don_kaeo,inSeason).
grows_well_in(pathumthani1,tha_wang_tan,inSeason).
grows_well_in(jasmine105,tha_wang_tan,inSeason).
grows_well_in(suphanburi1,tha_wang_tan,inSeason).
grows_well_in(san_pah_tawng1,pa_bong,inSeason).
grows_well_in(suphanburi1,pa_bong,inSeason).
grows_well_in(pathumthani1,pa_bong,inSeason).
grows_well_in(jasmine105,yang_noeng,inSeason).
grows_well_in(san_pah_tawng1,yang_noeng,inSeason).
grows_well_in(rd6,yang_noeng,inSeason).
grows_well_in(phitsanulok2,saraphi,inSeason).
grows_well_in(suphanburi1,saraphi,inSeason).
grows_well_in(jasmine105,saraphi,inSeason).
grows_well_in(san_pah_tawng1,nong_phueng,inSeason).
grows_well_in(phitsanulok2,nong_phueng,inSeason).
grows_well_in(pathumthani1,nong_phueng,inSeason).
grows_well_in(phitsanulok2,nong_faek,inSeason).
grows_well_in(suphanburi1,nong_faek,inSeason).
grows_well_in(pathumthani1,nong_faek,inSeason).
grows_well_in(jasmine105,khun_khong,inSeason).
grows_well_in(san_pah_tawng1,khun_khong,inSeason).
grows_well_in(rd6,khun_khong,inSeason).
grows_well_in(jasmine105,nam_phrae,inSeason).
grows_well_in(san_pah_tawng1,nam_phrae,inSeason).
grows_well_in(rd6,nam_phrae,inSeason).
grows_well_in(san_pah_tawng1,ban_pong,inSeason).
grows_well_in(rd6,ban_pong,inSeason).
grows_well_in(jasmine105,ban_waen,inSeason).
grows_well_in(san_pah_tawng1,ban_waen,inSeason).
grows_well_in(rd6,ban_waen,inSeason).
grows_well_in(jasmine105,sop_mae_kha,inSeason).
grows_well_in(san_pah_tawng1,sop_mae_kha,inSeason).
grows_well_in(rd39,sop_mae_kha,inSeason).
grows_well_in(jasmine105,san_phak_wan,inSeason).
grows_well_in(pathumthani1,san_phak_wan,inSeason).
grows_well_in(rd6,san_phak_wan,inSeason).
grows_well_in(san_pah_tawng1,nong_kaeo,inSeason).
grows_well_in(rd6,nong_kaeo,inSeason).
grows_well_in(jasmine105,nong_kaeo,inSeason).
grows_well_in(jasmine105,nong_khwai,inSeason).
grows_well_in(rd6,nong_khwai,inSeason).
grows_well_in(pathumthani1,nong_khwai,inSeason).
grows_well_in(san_pah_tawng1,nong_tong,inSeason).
grows_well_in(rd6,nong_tong,inSeason).
grows_well_in(jasmine105,nong_tong,inSeason).
grows_well_in(jasmine105,hang_dong,inSeason).
grows_well_in(rd6,hang_dong,inSeason).
grows_well_in(suphanburi1,hang_dong,inSeason).
grows_well_in(jasmine105,han_kaeo,inSeason).
grows_well_in(rd6,han_kaeo,inSeason).
grows_well_in(chainat1,han_kaeo,inSeason).
grows_well_in(san_pah_tawng1,na_kian,inSeason).
grows_well_in(san_pah_tawng1,mon_chong,inSeason).
grows_well_in(rd7,mon_chong,inSeason).
grows_well_in(khaojowhawmsuphanburi,mon_chong,inSeason).
grows_well_in(san_pah_tawng1,mae_tuen,inSeason).
grows_well_in(rd7,mae_tuen,inSeason).
grows_well_in(khaojowhawmsuphanburi,mae_tuen,inSeason).
grows_well_in(puen_muang,yang_piang,inSeason).
grows_well_in(rd6,yang_piang,inSeason).
grows_well_in(san_pah_tawng1,yang_piang,inSeason).
grows_well_in(san_pah_tawng1,sop_khong,inSeason).
grows_well_in(san_pah_tawng1,omkoi,inSeason).
grows_well_in(rd6,omkoi,inSeason).
grows_well_in(san_pah_tawng1,bo_sali,inSeason).
grows_well_in(rd10,bo_sali,inSeason).
grows_well_in(jowhaw,bo_luang,inSeason).
grows_well_in(san_pah_tawng1,bo_luang,inSeason).
grows_well_in(rd21,bo_luang,inSeason).
grows_well_in(san_pah_tawng1,ban_tan,inSeason).
grows_well_in(rd6,ban_tan,inSeason).
grows_well_in(rd15,ban_tan,inSeason).
grows_well_in(san_pah_tawng1,hang_dong,inSeason).
grows_well_in(rd6,hang_dong,inSeason).
grows_well_in(jasmine105,hang_dong,inSeason).
grows_well_in(rd15,hot,inSeason).
grows_well_in(rd21,hot,inSeason).
grows_well_in(pathumthani1,khuang_pao,doubleCrop).
grows_well_in(rd10,khuang_pao,doubleCrop).
grows_well_in(san_pah_tawng1,khuang_pao,doubleCrop).
grows_well_in(pathumthani1,doi_kaeo,doubleCrop).
grows_well_in(rd10,doi_kaeo,doubleCrop).
grows_well_in(san_pah_tawng1,doi_kaeo,doubleCrop).
grows_well_in(pathumthani1,ban_pae,doubleCrop).
grows_well_in(rd10,ban_pae,doubleCrop).
grows_well_in(san_pah_tawng1,ban_pae,doubleCrop).
grows_well_in(pathumthani1,ban_luang,doubleCrop).
grows_well_in(rd10,ban_luang,doubleCrop).
grows_well_in(san_pah_tawng1,ban_luang,doubleCrop).
grows_well_in(pathumthani1,mae_soi,doubleCrop).
grows_well_in(rd10,mae_soi,doubleCrop).
grows_well_in(san_pah_tawng1,mae_soi,doubleCrop).
grows_well_in(pathumthani1,sop_tia,doubleCrop).
grows_well_in(rd10,sop_tia,doubleCrop).
grows_well_in(san_pah_tawng1,sop_tia,doubleCrop).
grows_well_in(pathumthani1,chiang_dao,doubleCrop).
grows_well_in(rd10,chiang_dao,doubleCrop).
grows_well_in(san_pah_tawng1,chiang_dao,doubleCrop).
grows_well_in(san_pah_tawng1,mueang_ngai,doubleCrop).
grows_well_in(san_pah_tawng1,mae_na,doubleCrop).
grows_well_in(san_pah_tawng1,pong_tam,doubleCrop).
grows_well_in(san_pah_tawng1,mae_thalop,doubleCrop).
grows_well_in(niawsan_pah_tawng,si_dong_yen,doubleCrop).
grows_well_in(rd10,si_dong_yen,doubleCrop).
grows_well_in(san_pah_tawng1,si_dong_yen,doubleCrop).
grows_well_in(suphanburi1,nong_bua,doubleCrop).
grows_well_in(san_pah_tawng1,nong_bua,doubleCrop).
grows_well_in(san_pah_tawng1,doi_tao,doubleCrop).
grows_well_in(khaojowhawmsuphanburi,doi_tao,doubleCrop).
grows_well_in(pathumthani1,doi_tao,doubleCrop).
grows_well_in(san_pah_tawng1,tha_duea,doubleCrop).
grows_well_in(khaojowhawmsuphanburi,tha_duea,doubleCrop).
grows_well_in(rd10,tha_duea,doubleCrop).
grows_well_in(san_pah_tawng1,bong_tan,doubleCrop).
grows_well_in(pathumthani1,bong_tan,doubleCrop).
grows_well_in(rd10,bong_tan,doubleCrop).
grows_well_in(rd10,ban_aen,doubleCrop).
grows_well_in(san_pah_tawng1,ban_aen,doubleCrop).
grows_well_in(rd21,ban_aen,doubleCrop).
grows_well_in(san_pah_tawng1,muet_ka,doubleCrop).
grows_well_in(phitsanulok2,muet_ka,doubleCrop).
grows_well_in(khaojowhawmsuphanburi,muet_ka,doubleCrop).
grows_well_in(san_pah_tawng1,choeng_doi,doubleCrop).
grows_well_in(phitsanulok2,choeng_doi,doubleCrop).
grows_well_in(pathumthani1,choeng_doi,doubleCrop).
grows_well_in(san_pah_tawng1,talat_khwan,doubleCrop).
grows_well_in(phitsanulok2,talat_khwan,doubleCrop).
grows_well_in(pathumthani1,talat_khwan,doubleCrop).
grows_well_in(san_pah_tawng1,talat_yai,doubleCrop).
grows_well_in(phitsanulok2,talat_yai,doubleCrop).
grows_well_in(pathumthani1,talat_yai,doubleCrop).
grows_well_in(san_pah_tawng1,pa_pong,doubleCrop).
grows_well_in(phitsanulok2,pa_pong,doubleCrop).
grows_well_in(pathumthani1,pa_pong,doubleCrop).
grows_well_in(san_pah_tawng1,pa_miang,doubleCrop).
grows_well_in(san_pah_tawng1,pa_lan,doubleCrop).
grows_well_in(phitsanulok2,pa_lan,doubleCrop).
grows_well_in(san_pah_tawng1,mae_khue,doubleCrop).
grows_well_in(phitsanulok2,mae_khue,doubleCrop).
grows_well_in(pathumthani1,mae_khue,doubleCrop).
grows_well_in(san_pah_tawng1,mae_pong,doubleCrop).
grows_well_in(phitsanulok2,mae_pong,doubleCrop).
grows_well_in(pathumthani1,mae_pong,doubleCrop).
grows_well_in(san_pah_tawng1,mae_hoi_ngoen,doubleCrop).
grows_well_in(phitsanulok2,mae_hoi_ngoen,doubleCrop).
grows_well_in(khaojowhawmphitsanulok1,mae_hoi_ngoen,doubleCrop).
grows_well_in(san_pah_tawng1,luang_nuea,doubleCrop).
grows_well_in(suphanburi1,luang_nuea,doubleCrop).
grows_well_in(pathumthani1,luang_nuea,doubleCrop).
grows_well_in(san_pah_tawng1,sa_nga_ban,doubleCrop).
grows_well_in(phitsanulok2,sa_nga_ban,doubleCrop).
grows_well_in(pathumthani1,sa_nga_ban,doubleCrop).
grows_well_in(san_pah_tawng1,san_pu_loei,doubleCrop).
grows_well_in(suphanburi1,san_pu_loei,doubleCrop).
grows_well_in(pathumthani1,san_pu_loei,doubleCrop).
grows_well_in(san_pah_tawng1,samran_rat,doubleCrop).
grows_well_in(phitsanulok2,samran_rat,doubleCrop).
grows_well_in(suphanburi1,samran_rat,doubleCrop).
grows_well_in(san_pah_tawng1,doi_lo,doubleCrop).
grows_well_in(rd31,doi_lo,doubleCrop).
grows_well_in(phitsanulok2,doi_lo,doubleCrop).
grows_well_in(san_pah_tawng1,yang_khram,doubleCrop).
grows_well_in(rd31,yang_khram,doubleCrop).
grows_well_in(phitsanulok2,yang_khram,doubleCrop).
grows_well_in(san_pah_tawng1,song_khwae,doubleCrop).
grows_well_in(rd31,song_khwae,doubleCrop).
grows_well_in(san_pah_tawng1,santi_suk,doubleCrop).
grows_well_in(rd31,santi_suk,doubleCrop).
grows_well_in(phitsanulok2,santi_suk,doubleCrop).
grows_well_in(san_pah_tawng1,pong_nam_ron,doubleCrop).
grows_well_in(san_pah_tawng1,mon_pin,doubleCrop).
grows_well_in(san_pah_tawng1,mae_kha,doubleCrop).
grows_well_in(pathumthani1,mae_kha,doubleCrop).
grows_well_in(san_pah_tawng1,mae_kha,doubleCrop).
grows_well_in(suphanburi1,mae_kha,doubleCrop).
grows_well_in(pathumthani1,mae_kha,doubleCrop).
grows_well_in(san_pah_tawng1,mae_ngon,doubleCrop).
grows_well_in(san_pah_tawng1,mae_sun,doubleCrop).
grows_well_in(san_pah_tawng1,wiang,doubleCrop).
grows_well_in(suphanburi1,wiang,doubleCrop).
grows_well_in(pathumthani1,wiang,doubleCrop).
grows_well_in(san_pah_tawng1,san_sai,doubleCrop).
grows_well_in(rd10,san_sai,doubleCrop).
grows_well_in(san_pah_tawng1,khuean_phak,doubleCrop).
grows_well_in(suphanburi60,khuean_phak,doubleCrop).
grows_well_in(pathumthani1,khuean_phak,doubleCrop).
grows_well_in(san_pah_tawng1,thung_luang,doubleCrop).
grows_well_in(suphanburi60,thung_luang,doubleCrop).
grows_well_in(khaojowhawmphitsanulok1,thung_luang,doubleCrop).
grows_well_in(san_pah_tawng1,nam_phrae,doubleCrop).
grows_well_in(pathumthani1,nam_phrae,doubleCrop).
grows_well_in(khaojowhawmphitsanulok1,nam_phrae,doubleCrop).
grows_well_in(san_pah_tawng1,ban_pong,doubleCrop).
grows_well_in(pathumthani1,ban_pong,doubleCrop).
grows_well_in(rd2,ban_pong,doubleCrop).
grows_well_in(san_pah_tawng1,pa_tum,doubleCrop).
grows_well_in(suphanburi60,pa_tum,doubleCrop).
grows_well_in(pathumthani1,pa_tum,doubleCrop).
grows_well_in(khaojowhawmsuphanburi,pa_nai,doubleCrop).
grows_well_in(san_pah_tawng1,pa_nai,doubleCrop).
grows_well_in(suphanburi60,pa_nai,doubleCrop).
grows_well_in(khaojowhawmphitsanulok1,mae_pang,doubleCrop).
grows_well_in(san_pah_tawng1,mae_pang,doubleCrop).
grows_well_in(suphanburi60,mae_pang,doubleCrop).
grows_well_in(san_pah_tawng1,mae_waen,doubleCrop).
grows_well_in(suphanburi60,mae_waen,doubleCrop).
grows_well_in(pathumthani1,mae_waen,doubleCrop).
grows_well_in(khaojowhawmsuphanburi,wiang,doubleCrop).
grows_well_in(san_pah_tawng1,wiang,doubleCrop).
grows_well_in(suphanburi60,wiang,doubleCrop).
grows_well_in(khaojowhawmsuphanburi,san_sai,doubleCrop).
grows_well_in(san_pah_tawng1,san_sai,doubleCrop).
grows_well_in(suphanburi60,san_sai,doubleCrop).
grows_well_in(rd39,long_khot,doubleCrop).
grows_well_in(suphanburi60,long_khot,doubleCrop).
grows_well_in(khaojowhawmphitsanulok1,tha_sala,doubleCrop).
grows_well_in(san_pah_tawng1,tha_sala,doubleCrop).
grows_well_in(pathumthani60,pa_daet,doubleCrop).
grows_well_in(san_pah_tawng1,pa_daet,doubleCrop).
grows_well_in(san_pah_tawng1,mae_hia,doubleCrop).
grows_well_in(pathumthani60,san_phisuea,doubleCrop).
grows_well_in(san_pah_tawng1,san_phisuea,doubleCrop).
grows_well_in(khaojowhawmsuphanburi,san_phisuea,doubleCrop).
grows_well_in(san_pah_tawng1,suthep,doubleCrop).
grows_well_in(pathumthani60,nong_hoi,doubleCrop).
grows_well_in(san_pah_tawng1,nong_hoi,doubleCrop).
grows_well_in(san_pah_tawng1,chang_khoeng,doubleCrop).
grows_well_in(san_pah_tawng1,mae_na_chon,doubleCrop).
grows_well_in(rd10,mae_na_chon,doubleCrop).
grows_well_in(san_pah_tawng1,mae_suek,doubleCrop).
grows_well_in(rd10,mae_suek,doubleCrop).
grows_well_in(niawsan_pah_tawng,khi_lek,doubleCrop).
grows_well_in(san_pah_tawng1,khi_lek,doubleCrop).
grows_well_in(pathumthani1,khi_lek,doubleCrop).
grows_well_in(niawsan_pah_tawng,cho_lae,doubleCrop).
grows_well_in(san_pah_tawng1,cho_lae,doubleCrop).
grows_well_in(pathumthani1,cho_lae,doubleCrop).
grows_well_in(niawsan_pah_tawng,ban_pao,doubleCrop).
grows_well_in(san_pah_tawng1,ban_pao,doubleCrop).
grows_well_in(pathumthani1,ban_pao,doubleCrop).
grows_well_in(pathumthani1,mae_taeng,doubleCrop).
grows_well_in(san_pah_tawng1,mae_taeng,doubleCrop).
grows_well_in(niawsan_pah_tawng,mae_ho_phra,doubleCrop).
grows_well_in(san_pah_tawng1,mae_ho_phra,doubleCrop).
grows_well_in(pathumthani1,mae_ho_phra,doubleCrop).
grows_well_in(niawsan_pah_tawng,san_pa_yang,doubleCrop).
grows_well_in(san_pah_tawng1,san_pa_yang,doubleCrop).
grows_well_in(redhawnrice,san_pa_yang,doubleCrop).
grows_well_in(rd4,san_mahaphon,doubleCrop).
grows_well_in(niawsan_pah_tawng,san_mahaphon,doubleCrop).
grows_well_in(san_pah_tawng1,san_mahaphon,doubleCrop).
grows_well_in(niawsan_pah_tawng,inthakhin,doubleCrop).
grows_well_in(san_pah_tawng1,inthakhin,doubleCrop).
grows_well_in(pathumthani1,inthakhin,doubleCrop).
grows_well_in(suphanburi3,khi_lek,doubleCrop).
grows_well_in(san_pah_tawng1,khi_lek,doubleCrop).
grows_well_in(pathumthani1,khi_lek,doubleCrop).
grows_well_in(san_pah_tawng1,don_kaeo,doubleCrop).
grows_well_in(suphanburi3,don_kaeo,doubleCrop).
grows_well_in(san_pah_tawng1,mae_raem,doubleCrop).
grows_well_in(pathumthani1,mae_raem,doubleCrop).
grows_well_in(san_pah_tawng1,mae_sa,doubleCrop).
grows_well_in(pathumthani1,mae_sa,doubleCrop).
grows_well_in(suphanburi3,mae_sa,doubleCrop).
grows_well_in(san_pah_tawng1,rim_tai,doubleCrop).
grows_well_in(pathumthani1,rim_tai,doubleCrop).
grows_well_in(suphanburi2,rim_tai,doubleCrop).
grows_well_in(san_pah_tawng1,rim_nuea,doubleCrop).
grows_well_in(pathumthani1,rim_nuea,doubleCrop).
grows_well_in(phitsanulok2,rim_nuea,doubleCrop).
grows_well_in(san_pah_tawng1,saluang,doubleCrop).
grows_well_in(pathumthani1,saluang,doubleCrop).
grows_well_in(san_pah_tawng1,san_pong,doubleCrop).
grows_well_in(pathumthani1,san_pong,doubleCrop).
grows_well_in(suphanburi1,san_pong,doubleCrop).
grows_well_in(san_pah_tawng1,huai_sai,doubleCrop).
grows_well_in(pathumthani1,huai_sai,doubleCrop).
grows_well_in(suphanburi3,huai_sai,doubleCrop).
grows_well_in(san_pah_tawng1,mueang_kaeo,doubleCrop).
grows_well_in(pathumthani1,mueang_kaeo,doubleCrop).
grows_well_in(suphanburi3,mueang_kaeo,doubleCrop).
grows_well_in(niawsan_pah_tawng,don_pao,doubleCrop).
grows_well_in(san_pah_tawng1,don_pao,doubleCrop).
grows_well_in(japanese_rice,don_pao,doubleCrop).
grows_well_in(niawsan_pah_tawng,thung_pi,doubleCrop).
grows_well_in(san_pah_tawng1,thung_pi,doubleCrop).
grows_well_in(japanese_rice,thung_pi,doubleCrop).
grows_well_in(niawsan_pah_tawng,thung_ruang_thong,doubleCrop).
grows_well_in(san_pah_tawng1,thung_ruang_thong,doubleCrop).
grows_well_in(japanese_rice,thung_ruang_thong,doubleCrop).
grows_well_in(rd10,ban_kat,doubleCrop).
grows_well_in(san_pah_tawng1,ban_kat,doubleCrop).
grows_well_in(japanese_rice,ban_kat,doubleCrop).
grows_well_in(non_sensitive_rice,mae_win,doubleCrop).
grows_well_in(san_pah_tawng1,tha_nuea,doubleCrop).
grows_well_in(san_pah_tawng1,huai_kaeo,doubleCrop).
grows_well_in(san_pah_tawng1,on_klang,doubleCrop).
grows_well_in(san_pah_tawng1,on_nuea,doubleCrop).
grows_well_in(pathumthani1,on_nuea,doubleCrop).
grows_well_in(san_pah_tawng1,tha_ton,doubleCrop).
grows_well_in(non_sensitive_rice,ban_luang,doubleCrop).
grows_well_in(san_pah_tawng1,ban_luang,doubleCrop).
grows_well_in(pathumthani1,ban_luang,doubleCrop).
grows_well_in(san_pah_tawng1,malika,doubleCrop).
grows_well_in(rd14,malika,doubleCrop).
grows_well_in(non_sensitive_rice,malika,doubleCrop).
grows_well_in(san_pah_tawng1,mae_na_wang,doubleCrop).
grows_well_in(suphanburi1,mae_na_wang,doubleCrop).
grows_well_in(non_sensitive_rice,mae_na_wang,doubleCrop).
grows_well_in(san_pah_tawng1,mae_sao,doubleCrop).
grows_well_in(non_sensitive_rice,mae_sao,doubleCrop).
grows_well_in(san_pah_tawng1,mae_ai,doubleCrop).
grows_well_in(rd14,mae_ai,doubleCrop).
grows_well_in(pathumthani1,mae_ai,doubleCrop).
grows_well_in(san_pah_tawng1,san_ton_mue,doubleCrop).
grows_well_in(pathumthani1,san_ton_mue,doubleCrop).
grows_well_in(non_sensitive_rice,san_ton_mue,doubleCrop).
grows_well_in(san_pah_tawng1,yung_moen,doubleCrop).
grows_well_in(san_pah_tawng1,chae_chang,doubleCrop).
grows_well_in(suphanburi1,chae_chang,doubleCrop).
grows_well_in(pathumthani1,chae_chang,doubleCrop).
grows_well_in(san_pah_tawng1,ton_pao,doubleCrop).
grows_well_in(suphanburi1,ton_pao,doubleCrop).
grows_well_in(phitsanulok2,ton_pao,doubleCrop).
grows_well_in(san_pah_tawng1,sai_mun,doubleCrop).
grows_well_in(suphanburi1,sai_mun,doubleCrop).
grows_well_in(pathumthani1,sai_mun,doubleCrop).
grows_well_in(san_pah_tawng1,buak_khang,doubleCrop).
grows_well_in(suphanburi1,buak_khang,doubleCrop).
grows_well_in(phitsanulok2,buak_khang,doubleCrop).
grows_well_in(san_pah_tawng1,mae_pu_kha,doubleCrop).
grows_well_in(suphanburi3,mae_pu_kha,doubleCrop).
grows_well_in(phitsanulok2,mae_pu_kha,doubleCrop).
grows_well_in(san_pah_tawng1,rong_wua_daeng,doubleCrop).
grows_well_in(phitsanulok2,rong_wua_daeng,doubleCrop).
grows_well_in(pathumthani1,rong_wua_daeng,doubleCrop).
grows_well_in(san_pah_tawng1,san_klang,doubleCrop).
grows_well_in(suphanburi1,san_klang,doubleCrop).
grows_well_in(phitsanulok2,san_klang,doubleCrop).
grows_well_in(san_pah_tawng1,san_kamphaeng,doubleCrop).
grows_well_in(suphanburi3,san_kamphaeng,doubleCrop).
grows_well_in(suphanburi1,san_kamphaeng,doubleCrop).
grows_well_in(san_pah_tawng1,huai_sai,doubleCrop).
grows_well_in(phitsanulok2,huai_sai,doubleCrop).
grows_well_in(pathumthani1,huai_sai,doubleCrop).
grows_well_in(san_pah_tawng1,on_tai,doubleCrop).
grows_well_in(phitsanulok2,on_tai,doubleCrop).
grows_well_in(pathumthani1,on_tai,doubleCrop).
grows_well_in(san_pah_tawng1,pa_phai,doubleCrop).
grows_well_in(suphanburi3,pa_phai,doubleCrop).
grows_well_in(pathumthani1,pa_phai,doubleCrop).
grows_well_in(san_pah_tawng1,mueang_len,doubleCrop).
grows_well_in(phitsanulok2,mueang_len,doubleCrop).
grows_well_in(pathumthani1,mueang_len,doubleCrop).
grows_well_in(san_pah_tawng1,mae_faek,doubleCrop).
grows_well_in(suphanburi60,mae_faek,doubleCrop).
grows_well_in(pathumthani1,mae_faek,doubleCrop).
grows_well_in(san_pah_tawng1,mae_faek_mai,doubleCrop).
grows_well_in(niawsan_pah_tawng,mae_faek_mai,doubleCrop).
grows_well_in(pathumthani1,mae_faek_mai,doubleCrop).
grows_well_in(san_pah_tawng1,san_sai_noi,doubleCrop).
grows_well_in(phitsanulok2,san_sai_noi,doubleCrop).
grows_well_in(pathumthani1,san_sai_noi,doubleCrop).
grows_well_in(san_pah_tawng1,san_sai_luang,doubleCrop).
grows_well_in(phitsanulok2,san_sai_luang,doubleCrop).
grows_well_in(pathumthani1,san_sai_luang,doubleCrop).
grows_well_in(san_pah_tawng1,san_na_meng,doubleCrop).
grows_well_in(phitsanulok2,san_na_meng,doubleCrop).
grows_well_in(pathumthani1,san_na_meng,doubleCrop).
grows_well_in(san_pah_tawng1,san_pa_pao,doubleCrop).
grows_well_in(phitsanulok2,san_pa_pao,doubleCrop).
grows_well_in(pathumthani1,san_pa_pao,doubleCrop).
grows_well_in(san_pah_tawng1,san_phranet,doubleCrop).
grows_well_in(niawsan_pah_tawng,san_phranet,doubleCrop).
grows_well_in(pathumthani1,san_phranet,doubleCrop).
grows_well_in(san_pah_tawng1,nong_chom,doubleCrop).
grows_well_in(suphanburi3,nong_chom,doubleCrop).
grows_well_in(pathumthani1,nong_chom,doubleCrop).
grows_well_in(san_pah_tawng1,nong_han,doubleCrop).
grows_well_in(phitsanulok2,nong_han,doubleCrop).
grows_well_in(pathumthani1,nong_han,doubleCrop).
grows_well_in(san_pah_tawng1,nong_yaeng,doubleCrop).
grows_well_in(phitsanulok2,nong_yaeng,doubleCrop).
grows_well_in(pathumthani1,nong_yaeng,doubleCrop).
grows_well_in(san_pah_tawng1,tha_wang_phrao,doubleCrop).
grows_well_in(phitsanulok2,tha_wang_phrao,doubleCrop).
grows_well_in(japanese_rice,tha_wang_phrao,doubleCrop).
grows_well_in(san_pah_tawng1,thung_tom,doubleCrop).
grows_well_in(phitsanulok2,thung_tom,doubleCrop).
grows_well_in(rd39,thung_tom,doubleCrop).
grows_well_in(san_pah_tawng1,thung_satok,doubleCrop).
grows_well_in(suphanburi3,thung_satok,doubleCrop).
grows_well_in(pathumthani1,thung_satok,doubleCrop).
grows_well_in(san_pah_tawng1,nam_bo_luang,doubleCrop).
grows_well_in(rd10,nam_bo_luang,doubleCrop).
grows_well_in(pathumthani1,nam_bo_luang,doubleCrop).
grows_well_in(san_pah_tawng1,ban_klang,doubleCrop).
grows_well_in(rd39,ban_klang,doubleCrop).
grows_well_in(pathumthani1,ban_klang,doubleCrop).
grows_well_in(san_pah_tawng1,ban_mae,doubleCrop).
grows_well_in(khaojowhawmsuphanburi,ban_mae,doubleCrop).
grows_well_in(japanese_rice,ban_mae,doubleCrop).
grows_well_in(san_pah_tawng1,makham_luang,doubleCrop).
grows_well_in(phitsanulok2,makham_luang,doubleCrop).
grows_well_in(pathumthani1,makham_luang,doubleCrop).
grows_well_in(san_pah_tawng1,makhun_wan,doubleCrop).
grows_well_in(japanese_rice,makhun_wan,doubleCrop).
grows_well_in(pathumthani1,makhun_wan,doubleCrop).
grows_well_in(san_pah_tawng1,mae_ka,doubleCrop).
grows_well_in(rd39,mae_ka,doubleCrop).
grows_well_in(pathumthani1,mae_ka,doubleCrop).
grows_well_in(san_pah_tawng1,yu_wa,doubleCrop).
grows_well_in(japanese_rice,yu_wa,doubleCrop).
grows_well_in(pathumthani1,yu_wa,doubleCrop).
grows_well_in(san_pah_tawng1,san_klang,doubleCrop).
grows_well_in(phitsanulok2,san_klang,doubleCrop).
grows_well_in(chainat1,san_klang,doubleCrop).
grows_well_in(niawsan_pah_tawng,khua_mung,doubleCrop).
grows_well_in(suphanburi1,chomphu,doubleCrop).
grows_well_in(niawsan_pah_tawng,chomphu,doubleCrop).
grows_well_in(phitsanulok2,chomphu,doubleCrop).
grows_well_in(suphanburi1,chaiya_sathan,doubleCrop).
grows_well_in(niawsan_pah_tawng,chaiya_sathan,doubleCrop).
grows_well_in(phitsanulok2,chaiya_sathan,doubleCrop).
grows_well_in(suphanburi1,tha_wang_tan,doubleCrop).
grows_well_in(niawsan_pah_tawng,tha_wang_tan,doubleCrop).
grows_well_in(pathumthani1,tha_wang_tan,doubleCrop).
grows_well_in(suphanburi1,pa_bong,doubleCrop).
grows_well_in(niawsan_pah_tawng,pa_bong,doubleCrop).
grows_well_in(phitsanulok2,pa_bong,doubleCrop).
grows_well_in(suphanburi1,yang_noeng,doubleCrop).
grows_well_in(niawsan_pah_tawng,yang_noeng,doubleCrop).
grows_well_in(pathumthani1,yang_noeng,doubleCrop).
grows_well_in(khaojowhawmphitsanulok1,saraphi,doubleCrop).
grows_well_in(suphanburi1,saraphi,doubleCrop).
grows_well_in(phitsanulok2,saraphi,doubleCrop).
grows_well_in(phitsanulok2,nong_phueng,doubleCrop).
grows_well_in(niawsan_pah_tawng,nong_phueng,doubleCrop).
grows_well_in(pathumthani1,nong_phueng,doubleCrop).
grows_well_in(khaojowhawmphitsanulok1,nong_faek,doubleCrop).
grows_well_in(suphanburi1,nong_faek,doubleCrop).
grows_well_in(niawsan_pah_tawng,nong_faek,doubleCrop).
grows_well_in(san_pah_tawng1,khun_khong,doubleCrop).
grows_well_in(suphanburi3,khun_khong,doubleCrop).
grows_well_in(phitsanulok2,khun_khong,doubleCrop).
grows_well_in(san_pah_tawng1,nam_phrae,doubleCrop).
grows_well_in(chainat1,nam_phrae,doubleCrop).
grows_well_in(phitsanulok2,nam_phrae,doubleCrop).
grows_well_in(san_pah_tawng1,ban_waen,doubleCrop).
grows_well_in(suphanburi3,ban_waen,doubleCrop).
grows_well_in(phitsanulok2,ban_waen,doubleCrop).
grows_well_in(san_pah_tawng1,sop_mae_kha,doubleCrop).
grows_well_in(chainat1,sop_mae_kha,doubleCrop).
grows_well_in(phitsanulok2,sop_mae_kha,doubleCrop).
grows_well_in(san_pah_tawng1,san_phak_wan,doubleCrop).
grows_well_in(suphanburi3,san_phak_wan,doubleCrop).
grows_well_in(phitsanulok2,san_phak_wan,doubleCrop).
grows_well_in(san_pah_tawng1,nong_kaeo,doubleCrop).
grows_well_in(suphanburi1,nong_kaeo,doubleCrop).
grows_well_in(chainat1,nong_kaeo,doubleCrop).
grows_well_in(san_pah_tawng1,nong_khwai,doubleCrop).
grows_well_in(suphanburi3,nong_khwai,doubleCrop).
grows_well_in(san_pah_tawng1,nong_tong,doubleCrop).
grows_well_in(suphanburi3,nong_tong,doubleCrop).
grows_well_in(phitsanulok2,nong_tong,doubleCrop).
grows_well_in(san_pah_tawng1,hang_dong,doubleCrop).
grows_well_in(suphanburi3,hang_dong,doubleCrop).
grows_well_in(chainat1,hang_dong,doubleCrop).
grows_well_in(san_pah_tawng1,han_kaeo,doubleCrop).
grows_well_in(chainat1,han_kaeo,doubleCrop).
grows_well_in(chainat2,han_kaeo,doubleCrop).
grows_well_in(khaojowhawmsuphanburi,mon_chong,doubleCrop).
grows_well_in(khaojowhawmsuphanburi,mae_tuen,doubleCrop).
grows_well_in(san_pah_tawng1,mae_tuen,doubleCrop).
grows_well_in(rd7,mae_tuen,doubleCrop).
grows_well_in(pathumthani1,a_kho_ruea,doubleCrop).
grows_well_in(san_pah_tawng1,a_kho_ruea,doubleCrop).
grows_well_in(rd21,a_kho_ruea,doubleCrop).
grows_well_in(pathumthani1,ban_tan,doubleCrop).
grows_well_in(san_pah_tawng1,ban_tan,doubleCrop).
grows_well_in(rd10,ban_tan,doubleCrop).
grows_well_in(pathumthani1,hang_dong,doubleCrop).
grows_well_in(san_pah_tawng1,hang_dong,doubleCrop).
grows_well_in(rd10,hang_dong,doubleCrop).
grows_well_in(pathumthani1,hot,doubleCrop).
grows_well_in(san_pah_tawng1,hot,doubleCrop).
grows_well_in(rd10,hot,doubleCrop).
grows_well_in(jasmine105,kabin,inSeason).
grows_well_in(rd6,kabin,inSeason).
grows_well_in(jasmine105,kaeng_kheng,inSeason).
grows_well_in(rd6,kaeng_kheng,inSeason).
grows_well_in(jasmine105,khao_pun,inSeason).
grows_well_in(rd6,khao_pun,inSeason).
grows_well_in(jasmine105,non_sawang,inSeason).
grows_well_in(rd6,non_sawang,inSeason).
grows_well_in(jasmine105,nong_than_nam,inSeason).
grows_well_in(rd6,nong_than_nam,inSeason).
grows_well_in(jasmine105,kaeng_nuea,inSeason).
grows_well_in(rd6,kaeng_nuea,inSeason).
grows_well_in(rd10,kaeng_nuea,inSeason).
grows_well_in(jasmine105,kham_pom,inSeason).
grows_well_in(rd6,kham_pom,inSeason).
grows_well_in(rd10,kham_pom,inSeason).
grows_well_in(jasmine105,khemarat,inSeason).
grows_well_in(rd6,khemarat,inSeason).
grows_well_in(rd10,khemarat,inSeason).
grows_well_in(jasmine105,chiat,inSeason).
grows_well_in(rd6,chiat,inSeason).
grows_well_in(rd10,chiat,inSeason).
grows_well_in(jasmine105,na_waeng,inSeason).
grows_well_in(rd6,na_waeng,inSeason).
grows_well_in(rd10,na_waeng,inSeason).
grows_well_in(jasmine105,nong_nok_tha,inSeason).
grows_well_in(rd6,nong_nok_tha,inSeason).
grows_well_in(rd10,nong_nok_tha,inSeason).
grows_well_in(jasmine105,nong_phue,inSeason).
grows_well_in(rd6,nong_phue,inSeason).
grows_well_in(rd10,nong_phue,inSeason).
grows_well_in(jasmine105,nong_sim,inSeason).
grows_well_in(rd6,nong_sim,inSeason).
grows_well_in(jasmine105,hua_na,inSeason).
grows_well_in(rd6,hua_na,inSeason).
grows_well_in(rd10,hua_na,inSeason).
grows_well_in(jasmine105,klang_yai,inSeason).
grows_well_in(rd6,klang_yai,inSeason).
grows_well_in(jasmine105,ko_e,inSeason).
grows_well_in(rd6,ko_e,inSeason).
grows_well_in(jasmine105,khueang_nai,inSeason).
grows_well_in(rd6,khueang_nai,inSeason).
grows_well_in(jasmine105,kho_thong,inSeason).
grows_well_in(rd6,kho_thong,inSeason).
grows_well_in(jasmine105,chi_tuan,inSeason).
grows_well_in(rd6,chi_tuan,inSeason).
grows_well_in(jasmine105,daeng_mo,inSeason).
grows_well_in(rd6,daeng_mo,inSeason).
grows_well_in(jasmine105,tha_hai,inSeason).
grows_well_in(rd6,tha_hai,inSeason).
grows_well_in(jasmine105,that_noi,inSeason).
grows_well_in(rd6,that_noi,inSeason).
grows_well_in(jasmine105,na_kham_yai,inSeason).
grows_well_in(rd6,na_kham_yai,inSeason).
grows_well_in(jasmine105,non_rang,inSeason).
grows_well_in(rd6,non_rang,inSeason).
grows_well_in(jasmine105,ban_kok,inSeason).
grows_well_in(rd6,ban_kok,inSeason).
grows_well_in(jasmine105,ban_thai,inSeason).
grows_well_in(rd6,ban_thai,inSeason).
grows_well_in(jasmine105,yang_khi_nok,inSeason).
grows_well_in(rd6,yang_khi_nok,inSeason).
grows_well_in(jasmine105,si_suk,inSeason).
grows_well_in(rd6,si_suk,inSeason).
grows_well_in(jasmine105,sang_tho,inSeason).
grows_well_in(rd6,sang_tho,inSeason).
grows_well_in(jasmine105,sahathat,inSeason).
grows_well_in(rd6,sahathat,inSeason).
grows_well_in(jasmine105,nong_lao,inSeason).
grows_well_in(rd6,nong_lao,inSeason).
grows_well_in(jasmine105,hua_don,inSeason).
grows_well_in(rd6,hua_don,inSeason).
grows_well_in(jasmine105,khong_chiam,inSeason).
grows_well_in(rd6,khong_chiam,inSeason).
grows_well_in(rd15,khong_chiam,inSeason).
grows_well_in(jasmine105,na_pho_klang,inSeason).
grows_well_in(rd6,na_pho_klang,inSeason).
grows_well_in(rd14,na_pho_klang,inSeason).
grows_well_in(jasmine105,nong_saeng_yai,inSeason).
grows_well_in(rd6,nong_saeng_yai,inSeason).
grows_well_in(rd15,nong_saeng_yai,inSeason).
grows_well_in(jasmine105,huai_phai,inSeason).
grows_well_in(rd6,huai_phai,inSeason).
grows_well_in(rd4,huai_phai,inSeason).
grows_well_in(jasmine105,huai_yang,inSeason).
grows_well_in(rd6,huai_yang,inSeason).
grows_well_in(rd15,huai_yang,inSeason).
grows_well_in(jasmine105,kham_hai_yai,inSeason).
grows_well_in(rd6,kham_hai_yai,inSeason).
grows_well_in(rd15,kham_hai_yai,inSeason).
grows_well_in(jasmine105,don_mot_daeng,inSeason).
grows_well_in(rd6,don_mot_daeng,inSeason).
grows_well_in(jasmine105,tha_mueang,inSeason).
grows_well_in(rd6,tha_mueang,inSeason).
grows_well_in(rd15,tha_mueang,inSeason).
grows_well_in(jasmine105,lao_daeng,inSeason).
grows_well_in(rd6,lao_daeng,inSeason).
grows_well_in(jasmine105,klang,inSeason).
grows_well_in(rd6,klang,inSeason).
grows_well_in(jasmine105,kut_prathai,inSeason).
grows_well_in(rd6,kut_prathai,inSeason).
grows_well_in(jasmine105,kaeng,inSeason).
grows_well_in(rd6,kaeng,inSeason).
grows_well_in(jasmine105,kham_khrang,inSeason).
grows_well_in(rd6,kham_khrang,inSeason).
grows_well_in(jasmine105,top_hu,inSeason).
grows_well_in(rd6,top_hu,inSeason).
grows_well_in(jasmine105,tha_pho_si,inSeason).
grows_well_in(rd6,tha_pho_si,inSeason).
grows_well_in(jasmine105,thung_thoeng,inSeason).
grows_well_in(rd6,thung_thoeng,inSeason).
grows_well_in(jasmine105,na_krasaeng,inSeason).
grows_well_in(rd6,na_krasaeng,inSeason).
grows_well_in(jasmine105,na_charoen,inSeason).
grows_well_in(rd6,na_charoen,inSeason).
grows_well_in(jasmine105,na_suang,inSeason).
grows_well_in(rd6,na_suang,inSeason).
grows_well_in(jasmine105,non_sombun,inSeason).
grows_well_in(rd6,non_sombun,inSeason).
grows_well_in(jasmine105,bua_ngam,inSeason).
grows_well_in(rd6,bua_ngam,inSeason).
grows_well_in(jasmine105,pa_mong,inSeason).
grows_well_in(rd6,pa_mong,inSeason).
grows_well_in(jasmine105,phon_ngam,inSeason).
grows_well_in(rd6,phon_ngam,inSeason).
grows_well_in(jasmine105,mueang_det,inSeason).
grows_well_in(rd6,mueang_det,inSeason).
grows_well_in(jasmine105,som_sa_at,inSeason).
grows_well_in(rd6,som_sa_at,inSeason).
grows_well_in(jasmine105,kradian,inSeason).
grows_well_in(rd6,kradian,inSeason).
grows_well_in(rd15,kradian,inSeason).
grows_well_in(jasmine105,kut_ya_luan,inSeason).
grows_well_in(rd6,kut_ya_luan,inSeason).
grows_well_in(rd15,kut_ya_luan,inSeason).
grows_well_in(jasmine105,kusakon,inSeason).
grows_well_in(rd6,kusakon,inSeason).
grows_well_in(rd15,kusakon,inSeason).
grows_well_in(jasmine105,kasem,inSeason).
grows_well_in(rd6,kasem,inSeason).
grows_well_in(rd15,kasem,inSeason).
grows_well_in(jasmine105,kham_pia,inSeason).
grows_well_in(rd6,kham_pia,inSeason).
grows_well_in(rd15,kham_pia,inSeason).
grows_well_in(jasmine105,khulu,inSeason).
grows_well_in(rd6,khulu,inSeason).
grows_well_in(rd15,khulu,inSeason).
grows_well_in(jasmine105,khon_sai,inSeason).
grows_well_in(rd6,khon_sai,inSeason).
grows_well_in(rd15,khon_sai,inSeason).
grows_well_in(jasmine105,kham_charoen,inSeason).
grows_well_in(rd6,kham_charoen,inSeason).
grows_well_in(rd15,kham_charoen,inSeason).
grows_well_in(jasmine105,khok_chan,inSeason).
grows_well_in(rd6,khok_chan,inSeason).
grows_well_in(rd15,khok_chan,inSeason).
grows_well_in(jasmine105,se_pet,inSeason).
grows_well_in(rd6,se_pet,inSeason).
grows_well_in(rd15,se_pet,inSeason).
grows_well_in(jasmine105,trakan,inSeason).
grows_well_in(rd6,trakan,inSeason).
grows_well_in(rd15,trakan,inSeason).
grows_well_in(jasmine105,tak_daet,inSeason).
grows_well_in(rd6,tak_daet,inSeason).
grows_well_in(rd15,tak_daet,inSeason).
grows_well_in(jasmine105,tham_khae,inSeason).
grows_well_in(rd6,tham_khae,inSeason).
grows_well_in(rd15,tham_khae,inSeason).
grows_well_in(jasmine105,tha_luang,inSeason).
grows_well_in(rd6,tha_luang,inSeason).
grows_well_in(rd15,tha_luang,inSeason).
grows_well_in(jasmine105,na_phin,inSeason).
grows_well_in(rd6,na_phin,inSeason).
grows_well_in(rd15,na_phin,inSeason).
grows_well_in(jasmine105,na_samai,inSeason).
grows_well_in(rd6,na_samai,inSeason).
grows_well_in(rd15,na_samai,inSeason).
grows_well_in(jasmine105,non_kung,inSeason).
grows_well_in(rd6,non_kung,inSeason).
grows_well_in(rd15,non_kung,inSeason).
grows_well_in(jasmine105,ban_daeng,inSeason).
grows_well_in(rd6,ban_daeng,inSeason).
grows_well_in(rd15,ban_daeng,inSeason).
grows_well_in(jasmine105,pao,inSeason).
grows_well_in(rd6,pao,inSeason).
grows_well_in(rd15,pao,inSeason).
grows_well_in(jasmine105,saphue,inSeason).
grows_well_in(rd6,saphue,inSeason).
grows_well_in(rd15,saphue,inSeason).
grows_well_in(jasmine105,nong_tao,inSeason).
grows_well_in(rd6,nong_tao,inSeason).
grows_well_in(rd15,nong_tao,inSeason).
grows_well_in(jasmine105,huai_fai_phatthana,inSeason).
grows_well_in(rd6,huai_fai_phatthana,inSeason).
grows_well_in(rd15,huai_fai_phatthana,inSeason).
grows_well_in(jasmine105,lai_thung,inSeason).
grows_well_in(rd6,lai_thung,inSeason).
grows_well_in(jasmine105,kham_wa,inSeason).
grows_well_in(rd6,kham_wa,inSeason).
grows_well_in(rd15,kham_wa,inSeason).
grows_well_in(jasmine105,chik_thoeng,inSeason).
grows_well_in(rd6,chik_thoeng,inSeason).
grows_well_in(rd15,chik_thoeng,inSeason).
grows_well_in(jasmine105,tan_sum,inSeason).
grows_well_in(rd6,tan_sum,inSeason).
grows_well_in(rd15,tan_sum,inSeason).
grows_well_in(jasmine105,na_khai,inSeason).
grows_well_in(rd6,na_khai,inSeason).
grows_well_in(rd15,na_khai,inSeason).
grows_well_in(jasmine105,samrong,inSeason).
grows_well_in(rd6,samrong,inSeason).
grows_well_in(rd15,samrong,inSeason).
grows_well_in(jasmine105,nong_kung,inSeason).
grows_well_in(rd6,nong_kung,inSeason).
grows_well_in(rd15,nong_kung,inSeason).
grows_well_in(jasmine105,kut_ruea,inSeason).
grows_well_in(rd6,kut_ruea,inSeason).
grows_well_in(rd15,kut_ruea,inSeason).
grows_well_in(jasmine105,khok_chamrae,inSeason).
grows_well_in(rd6,khok_chamrae,inSeason).
grows_well_in(rd15,khok_chamrae,inSeason).
grows_well_in(jasmine105,na_kasem,inSeason).
grows_well_in(rd6,na_kasem,inSeason).
grows_well_in(jasmine105,na_hom,inSeason).
grows_well_in(rd6,na_hom,inSeason).
grows_well_in(jasmine105,nong_om,inSeason).
grows_well_in(rd6,nong_om,inSeason).
grows_well_in(rd15,nong_om,inSeason).
grows_well_in(jasmine105,na_chaluai,inSeason).
grows_well_in(rd6,na_chaluai,inSeason).
grows_well_in(rd15,na_chaluai,inSeason).
grows_well_in(jasmine105,non_sombun,inSeason).
grows_well_in(rd6,non_sombun,inSeason).
grows_well_in(rd15,non_sombun,inSeason).
grows_well_in(jasmine105,non_sawan,inSeason).
grows_well_in(rd6,non_sawan,inSeason).
grows_well_in(jasmine105,ban_tum,inSeason).
grows_well_in(rd6,ban_tum,inSeason).
grows_well_in(rd15,ban_tum,inSeason).
grows_well_in(jasmine105,phon_sawan,inSeason).
grows_well_in(rd6,phon_sawan,inSeason).
grows_well_in(rd15,phon_sawan,inSeason).
grows_well_in(jasmine105,sok_saeng,inSeason).
grows_well_in(rd6,sok_saeng,inSeason).
grows_well_in(rd15,sok_saeng,inSeason).
grows_well_in(jasmine105,kong_phon,inSeason).
grows_well_in(rd6,kong_phon,inSeason).
grows_well_in(jasmine105,na_tan,inSeason).
grows_well_in(rd6,na_tan,inSeason).
grows_well_in(rd15,na_tan,inSeason).
grows_well_in(jasmine105,phalan,inSeason).
grows_well_in(rd6,phalan,inSeason).
grows_well_in(jasmine105,phang_khen,inSeason).
grows_well_in(rd6,phang_khen,inSeason).
grows_well_in(jasmine105,na_di,inSeason).
grows_well_in(rd6,na_di,inSeason).
grows_well_in(rd15,na_di,inSeason).
grows_well_in(jasmine105,na_yia,inSeason).
grows_well_in(rd6,na_yia,inSeason).
grows_well_in(rd15,na_yia,inSeason).
grows_well_in(jasmine105,na_rueang,inSeason).
grows_well_in(rd6,na_rueang,inSeason).
grows_well_in(jasmine105,khi_lek,inSeason).
grows_well_in(rd6,khi_lek,inSeason).
grows_well_in(jasmine105,khok_sa_at,inSeason).
grows_well_in(rd6,khok_sa_at,inSeason).
grows_well_in(jasmine105,ta_kao,inSeason).
grows_well_in(rd6,ta_kao,inSeason).
grows_well_in(jasmine105,phaibun,inSeason).
grows_well_in(rd6,phaibun,inSeason).
grows_well_in(jasmine105,kao_kham,inSeason).
grows_well_in(rd6,kao_kham,inSeason).
grows_well_in(rd15,kao_kham,inSeason).
grows_well_in(jasmine105,song,inSeason).
grows_well_in(rd6,song,inSeason).
grows_well_in(rd15,song,inSeason).
grows_well_in(jasmine105,dom_pradit,inSeason).
grows_well_in(rd6,dom_pradit,inSeason).
grows_well_in(rd15,dom_pradit,inSeason).
grows_well_in(jasmine105,bu_pueai,inSeason).
grows_well_in(rd6,bu_pueai,inSeason).
grows_well_in(jasmine105,yang,inSeason).
grows_well_in(rd6,yang,inSeason).
grows_well_in(rd15,yang,inSeason).
grows_well_in(jasmine105,yang_yai,inSeason).
grows_well_in(rd6,yang_yai,inSeason).
grows_well_in(rd15,yang_yai,inSeason).
grows_well_in(jasmine105,si_wichian,inSeason).
grows_well_in(rd6,si_wichian,inSeason).
grows_well_in(jasmine105,kho_laen,inSeason).
grows_well_in(rd6,kho_laen,inSeason).
grows_well_in(rd15,kho_laen,inSeason).
grows_well_in(jasmine105,na_pho,inSeason).
grows_well_in(rd6,na_pho,inSeason).
grows_well_in(rd15,na_pho,inSeason).
grows_well_in(jasmine105,non_kho,inSeason).
grows_well_in(rd6,non_kho,inSeason).
grows_well_in(rd15,non_kho,inSeason).
grows_well_in(jasmine105,bua_ngam,inSeason).
grows_well_in(rd6,bua_ngam,inSeason).
grows_well_in(rd15,bua_ngam,inSeason).
grows_well_in(jasmine105,ban_maet,inSeason).
grows_well_in(rd6,ban_maet,inSeason).
grows_well_in(rd15,ban_maet,inSeason).
grows_well_in(jasmine105,phon_ngam,inSeason).
grows_well_in(rd6,phon_ngam,inSeason).
grows_well_in(rd15,phon_ngam,inSeason).
grows_well_in(jasmine105,nong_sano,inSeason).
grows_well_in(rd6,nong_sano,inSeason).
grows_well_in(rd15,nong_sano,inSeason).
grows_well_in(jasmine105,huai_kha,inSeason).
grows_well_in(rd6,huai_kha,inSeason).
grows_well_in(rd15,huai_kha,inSeason).
grows_well_in(jasmine105,kut_chomphu,inSeason).
grows_well_in(rd6,kut_chomphu,inSeason).
grows_well_in(rd15,kut_chomphu,inSeason).
grows_well_in(jasmine105,don_chik,inSeason).
grows_well_in(rd6,don_chik,inSeason).
grows_well_in(rd15,don_chik,inSeason).
grows_well_in(jasmine105,sai_mun,inSeason).
grows_well_in(rd6,sai_mun,inSeason).
grows_well_in(rd15,sai_mun,inSeason).
grows_well_in(jasmine105,na_pho,inSeason).
grows_well_in(rd6,na_pho,inSeason).
grows_well_in(rd15,na_pho,inSeason).
grows_well_in(jasmine105,non_klang,inSeason).
grows_well_in(rd6,non_klang,inSeason).
grows_well_in(rd15,non_klang,inSeason).
grows_well_in(jasmine105,non_kalong,inSeason).
grows_well_in(rd6,non_kalong,inSeason).
grows_well_in(rd15,non_kalong,inSeason).
grows_well_in(jasmine105,ban_khaem,inSeason).
grows_well_in(rd6,ban_khaem,inSeason).
grows_well_in(rd15,ban_khaem,inSeason).
grows_well_in(jasmine105,phibun,inSeason).
grows_well_in(rd6,phibun,inSeason).
grows_well_in(rd15,phibun,inSeason).
grows_well_in(jasmine105,pho_sai,inSeason).
grows_well_in(rd6,pho_sai,inSeason).
grows_well_in(rd15,pho_sai,inSeason).
grows_well_in(jasmine105,pho_si,inSeason).
grows_well_in(rd6,pho_si,inSeason).
grows_well_in(rd15,pho_si,inSeason).
grows_well_in(jasmine105,rawe,inSeason).
grows_well_in(rd6,rawe,inSeason).
grows_well_in(rd15,rawe,inSeason).
grows_well_in(jasmine105,rai_tai,inSeason).
grows_well_in(rd6,rai_tai,inSeason).
grows_well_in(rd15,rai_tai,inSeason).
grows_well_in(jasmine105,nong_bua_hi,inSeason).
grows_well_in(rd6,nong_bua_hi,inSeason).
grows_well_in(rd15,nong_bua_hi,inSeason).
grows_well_in(jasmine105,ang_sila,inSeason).
grows_well_in(rd6,ang_sila,inSeason).
grows_well_in(rd15,ang_sila,inSeason).
grows_well_in(jasmine105,pho_sai,inSeason).
grows_well_in(rd6,pho_sai,inSeason).
grows_well_in(rd15,pho_sai,inSeason).
grows_well_in(jasmine105,muang_yai,inSeason).
grows_well_in(rd6,muang_yai,inSeason).
grows_well_in(rd15,muang_yai,inSeason).
grows_well_in(jasmine105,song_khon,inSeason).
grows_well_in(rd6,song_khon,inSeason).
grows_well_in(rd15,song_khon,inSeason).
grows_well_in(jasmine105,saraphi,inSeason).
grows_well_in(rd6,saraphi,inSeason).
grows_well_in(rd15,saraphi,inSeason).
grows_well_in(jasmine105,samrong,inSeason).
grows_well_in(rd6,samrong,inSeason).
grows_well_in(rd15,samrong,inSeason).
grows_well_in(jasmine105,lao_ngam,inSeason).
grows_well_in(rd6,lao_ngam,inSeason).
grows_well_in(rd15,lao_ngam,inSeason).
grows_well_in(jasmine105,dum_yai,inSeason).
grows_well_in(rd6,dum_yai,inSeason).
grows_well_in(jasmine105,toei,inSeason).
grows_well_in(rd6,toei,inSeason).
grows_well_in(jasmine105,na_loeng,inSeason).
grows_well_in(rd6,na_loeng,inSeason).
grows_well_in(jasmine105,phai_yai,inSeason).
grows_well_in(rd6,phai_yai,inSeason).
grows_well_in(jasmine105,phon_phaeng,inSeason).
grows_well_in(rd6,phon_phaeng,inSeason).
grows_well_in(jasmine105,muang_sam_sip,inSeason).
grows_well_in(rd6,muang_sam_sip,inSeason).
grows_well_in(jasmine105,yang_yo_phap,inSeason).
grows_well_in(rd6,yang_yo_phap,inSeason).
grows_well_in(rd15,yang_yo_phap,inSeason).
grows_well_in(jasmine105,yang_sak_krapho_lum,inSeason).
grows_well_in(rd6,yang_sak_krapho_lum,inSeason).
grows_well_in(jasmine105,nong_khai_nok,inSeason).
grows_well_in(rd6,nong_khai_nok,inSeason).
grows_well_in(jasmine105,nong_chang_yai,inSeason).
grows_well_in(rd6,nong_chang_yai,inSeason).
grows_well_in(jasmine105,nong_mueang,inSeason).
grows_well_in(rd6,nong_mueang,inSeason).
grows_well_in(rd15,nong_mueang,inSeason).
grows_well_in(jasmine105,nong_lao,inSeason).
grows_well_in(rd6,nong_lao,inSeason).
grows_well_in(jasmine105,nong_hang,inSeason).
grows_well_in(rd6,nong_hang,inSeason).
grows_well_in(jasmine105,lao_bok,inSeason).
grows_well_in(rd6,lao_bok,inSeason).
grows_well_in(jasmine105,krasop,inSeason).
grows_well_in(rd6,krasop,inSeason).
grows_well_in(rd10,krasop,inSeason).
grows_well_in(jasmine105,kut_lat,inSeason).
grows_well_in(rd6,kut_lat,inSeason).
grows_well_in(rd15,kut_lat,inSeason).
grows_well_in(jasmine105,kham_yai,inSeason).
grows_well_in(rd6,kham_yai,inSeason).
grows_well_in(rd15,kham_yai,inSeason).
grows_well_in(jasmine105,khi_lek,inSeason).
grows_well_in(rd6,khi_lek,inSeason).
grows_well_in(rd10,khi_lek,inSeason).
grows_well_in(jasmine105,chaeramae,inSeason).
grows_well_in(rd6,chaeramae,inSeason).
grows_well_in(rd10,chaeramae,inSeason).
grows_well_in(jasmine105,nai_mueang,inSeason).
grows_well_in(rd6,nai_mueang,inSeason).
grows_well_in(jasmine105,pathum,inSeason).
grows_well_in(rd6,pathum,inSeason).
grows_well_in(rd15,pathum,inSeason).
grows_well_in(jasmine105,pa_ao,inSeason).
grows_well_in(rd6,pa_ao,inSeason).
grows_well_in(rd10,pa_ao,inSeason).
grows_well_in(jasmine105,rai_noi,inSeason).
grows_well_in(rd6,rai_noi,inSeason).
grows_well_in(rd10,rai_noi,inSeason).
grows_well_in(jasmine105,nong_khon,inSeason).
grows_well_in(rd6,nong_khon,inSeason).
grows_well_in(rd15,nong_khon,inSeason).
grows_well_in(jasmine105,nong_bo,inSeason).
grows_well_in(rd6,nong_bo,inSeason).
grows_well_in(jasmine105,hua_ruea,inSeason).
grows_well_in(rd6,hua_ruea,inSeason).
grows_well_in(rd15,hua_ruea,inSeason).
grows_well_in(jasmine105,kham_khwang,inSeason).
grows_well_in(rd6,kham_khwang,inSeason).
grows_well_in(rd15,kham_khwang,inSeason).
grows_well_in(jasmine105,kham_nam_sap,inSeason).
grows_well_in(rd6,kham_nam_sap,inSeason).
grows_well_in(jasmine105,khu_mueang,inSeason).
grows_well_in(rd6,khu_mueang,inSeason).
grows_well_in(rd15,khu_mueang,inSeason).
grows_well_in(jasmine105,tha_lat,inSeason).
grows_well_in(rd6,tha_lat,inSeason).
grows_well_in(jasmine105,that,inSeason).
grows_well_in(rd6,that,inSeason).
grows_well_in(rd15,that,inSeason).
grows_well_in(jasmine105,non_phueng,inSeason).
grows_well_in(rd6,non_phueng,inSeason).
grows_well_in(rd15,non_phueng,inSeason).
grows_well_in(jasmine105,non_non,inSeason).
grows_well_in(rd6,non_non,inSeason).
grows_well_in(rd15,non_non,inSeason).
grows_well_in(jasmine105,bung_wai,inSeason).
grows_well_in(rd6,bung_wai,inSeason).
grows_well_in(jasmine105,bung_mai,inSeason).
grows_well_in(rd6,bung_mai,inSeason).
grows_well_in(rd15,bung_mai,inSeason).
grows_well_in(jasmine105,pho_yai,inSeason).
grows_well_in(rd6,pho_yai,inSeason).
grows_well_in(rd15,pho_yai,inSeason).
grows_well_in(jasmine105,mueang_si_khai,inSeason).
grows_well_in(rd6,mueang_si_khai,inSeason).
grows_well_in(rd15,mueang_si_khai,inSeason).
grows_well_in(jasmine105,warin_chamrap,inSeason).
grows_well_in(jasmine105,sa_saming,inSeason).
grows_well_in(rd6,sa_saming,inSeason).
grows_well_in(rd15,sa_saming,inSeason).
grows_well_in(jasmine105,saen_suk,inSeason).
grows_well_in(rd6,saen_suk,inSeason).
grows_well_in(rd15,saen_suk,inSeason).
grows_well_in(jasmine105,nong_kin_phlen,inSeason).
grows_well_in(rd6,nong_kin_phlen,inSeason).
grows_well_in(rd15,nong_kin_phlen,inSeason).
grows_well_in(jasmine105,huai_khayung,inSeason).
grows_well_in(rd6,huai_khayung,inSeason).
grows_well_in(rd15,huai_khayung,inSeason).
grows_well_in(jasmine105,kaeng_kok,inSeason).
grows_well_in(rd6,kaeng_kok,inSeason).
grows_well_in(rd15,kaeng_kok,inSeason).
grows_well_in(jasmine105,kham_lai,inSeason).
grows_well_in(rd6,kham_lai,inSeason).
grows_well_in(rd15,kham_lai,inSeason).
grows_well_in(jasmine105,don_yai,inSeason).
grows_well_in(rd6,don_yai,inSeason).
grows_well_in(rd15,don_yai,inSeason).
grows_well_in(jasmine105,tabai,inSeason).
grows_well_in(rd6,tabai,inSeason).
grows_well_in(rd15,tabai,inSeason).
grows_well_in(jasmine105,na_kham,inSeason).
grows_well_in(rd6,na_kham,inSeason).
grows_well_in(rd15,na_kham,inSeason).
grows_well_in(jasmine105,na_loen,inSeason).
grows_well_in(rd6,na_loen,inSeason).
grows_well_in(rd15,na_loen,inSeason).
grows_well_in(jasmine105,lat_khwai,inSeason).
grows_well_in(rd6,lat_khwai,inSeason).
grows_well_in(rd15,lat_khwai,inSeason).
grows_well_in(jasmine105,warin,inSeason).
grows_well_in(rd6,warin,inSeason).
grows_well_in(rd15,warin,inSeason).
grows_well_in(jasmine105,song_yang,inSeason).
grows_well_in(rd6,song_yang,inSeason).
grows_well_in(rd15,song_yang,inSeason).
grows_well_in(jasmine105,nam_thaeng,inSeason).
grows_well_in(rd6,nam_thaeng,inSeason).
grows_well_in(rd15,nam_thaeng,inSeason).
grows_well_in(jasmine105,ueat_yai,inSeason).
grows_well_in(rd6,ueat_yai,inSeason).
grows_well_in(jasmine105,kaeng_dom,inSeason).
grows_well_in(rd6,kaeng_dom,inSeason).
grows_well_in(jasmine105,tha_chang,inSeason).
grows_well_in(rd6,tha_chang,inSeason).
grows_well_in(rd15,tha_chang,inSeason).
grows_well_in(jasmine105,bung_malaeng,inSeason).
grows_well_in(rd6,bung_malaeng,inSeason).
grows_well_in(rd15,bung_malaeng,inSeason).
grows_well_in(jasmine105,sawang,inSeason).
grows_well_in(rd6,sawang,inSeason).
grows_well_in(rd15,sawang,inSeason).
grows_well_in(jasmine105,kham_pom,inSeason).
grows_well_in(rd6,kham_pom,inSeason).
grows_well_in(rd15,kham_pom,inSeason).
grows_well_in(jasmine105,kho_noi,inSeason).
grows_well_in(rd6,kho_noi,inSeason).
grows_well_in(rd15,kho_noi,inSeason).
grows_well_in(jasmine105,khok_kong,inSeason).
grows_well_in(rd6,khok_kong,inSeason).
grows_well_in(rd15,khok_kong,inSeason).
grows_well_in(jasmine105,khok_sawang,inSeason).
grows_well_in(rd6,khok_sawang,inSeason).
grows_well_in(rd15,khok_sawang,inSeason).
grows_well_in(jasmine105,non_klang,inSeason).
grows_well_in(rd6,non_klang,inSeason).
grows_well_in(rd15,non_klang,inSeason).
grows_well_in(jasmine105,non_kalen,inSeason).
grows_well_in(rd6,non_kalen,inSeason).
grows_well_in(rd15,non_kalen,inSeason).
grows_well_in(jasmine105,bon,inSeason).
grows_well_in(rd6,bon,inSeason).
grows_well_in(rd15,bon,inSeason).
grows_well_in(jasmine105,samrong,inSeason).
grows_well_in(rd6,samrong,inSeason).
grows_well_in(jasmine105,nong_hai,inSeason).
grows_well_in(rd6,nong_hai,inSeason).
grows_well_in(rd15,nong_hai,inSeason).
grows_well_in(jasmine105,khan_rai,inSeason).
grows_well_in(sakonnakhon,khan_rai,inSeason).
grows_well_in(rd15,khan_rai,inSeason).
grows_well_in(sakonnakhon,kham_khuean_kaeo,inSeason).
grows_well_in(rd6,kham_khuean_kaeo,inSeason).
grows_well_in(rd15,kham_khuean_kaeo,inSeason).
grows_well_in(jasmine105,chong_mek,inSeason).
grows_well_in(rd6,chong_mek,inSeason).
grows_well_in(rd15,chong_mek,inSeason).
grows_well_in(jasmine105,nikhom_lam_dom_noi,inSeason).
grows_well_in(sakonnakhon,nikhom_lam_dom_noi,inSeason).
grows_well_in(rd15,nikhom_lam_dom_noi,inSeason).
grows_well_in(jasmine105,non_ko,inSeason).
grows_well_in(sakonnakhon,non_ko,inSeason).
grows_well_in(rd15,non_ko,inSeason).
grows_well_in(jasmine105,fang_kham,inSeason).
grows_well_in(rd6,fang_kham,inSeason).
grows_well_in(rd15,fang_kham,inSeason).
grows_well_in(jasmine105,phaeng_yai,inSeason).
grows_well_in(rd6,phaeng_yai,inSeason).
grows_well_in(jasmine105,phon_mueang,inSeason).
grows_well_in(rd6,phon_mueang,inSeason).
grows_well_in(jasmine105,nong_bok,inSeason).
grows_well_in(rd6,nong_bok,inSeason).
grows_well_in(jasmine105,lao_suea_kok,inSeason).
grows_well_in(rd6,lao_suea_kok,inSeason).
grows_well_in(pathumthani1,kabin,doubleCrop).
grows_well_in(chainat1,kabin,doubleCrop).
grows_well_in(pathumthani1,khao_pun,doubleCrop).
grows_well_in(chainat1,khao_pun,doubleCrop).
grows_well_in(rd10,kaeng_nuea,doubleCrop).
grows_well_in(rd33,kham_pom,doubleCrop).
grows_well_in(rd10,kham_pom,doubleCrop).
grows_well_in(rd33,khemarat,doubleCrop).
grows_well_in(rd33,chiat,doubleCrop).
grows_well_in(rd33,na_waeng,doubleCrop).
grows_well_in(rd10,na_waeng,doubleCrop).
grows_well_in(pathumthani1,nong_phue,doubleCrop).
grows_well_in(suphanburi3,nong_sim,doubleCrop).
grows_well_in(rd10,hua_na,doubleCrop).
grows_well_in(chainat1,klang_yai,doubleCrop).
grows_well_in(chainat1,ko_e,doubleCrop).
grows_well_in(chainat1,khueang_nai,doubleCrop).
grows_well_in(rd33,khueang_nai,doubleCrop).
grows_well_in(rd10,khueang_nai,doubleCrop).
grows_well_in(chainat1,kho_thong,doubleCrop).
grows_well_in(phitsanulok80,kho_thong,doubleCrop).
grows_well_in(pathumthani1,kho_thong,doubleCrop).
grows_well_in(chainat1,chi_tuan,doubleCrop).
grows_well_in(rd33,chi_tuan,doubleCrop).
grows_well_in(pathumthani1,chi_tuan,doubleCrop).
grows_well_in(chainat1,daeng_mo,doubleCrop).
grows_well_in(rd10,daeng_mo,doubleCrop).
grows_well_in(pathumthani1,daeng_mo,doubleCrop).
grows_well_in(chainat1,tha_hai,doubleCrop).
grows_well_in(rd33,tha_hai,doubleCrop).
grows_well_in(pathumthani1,tha_hai,doubleCrop).
grows_well_in(chainat1,that_noi,doubleCrop).
grows_well_in(rd10,that_noi,doubleCrop).
grows_well_in(pathumthani1,that_noi,doubleCrop).
grows_well_in(chainat1,na_kham_yai,doubleCrop).
grows_well_in(rd33,na_kham_yai,doubleCrop).
grows_well_in(pathumthani1,na_kham_yai,doubleCrop).
grows_well_in(chainat1,ban_kok,doubleCrop).
grows_well_in(chainat1,ban_thai,doubleCrop).
grows_well_in(rd33,ban_thai,doubleCrop).
grows_well_in(pathumthani1,ban_thai,doubleCrop).
grows_well_in(chainat1,yang_khi_nok,doubleCrop).
grows_well_in(phitsanulok80,yang_khi_nok,doubleCrop).
grows_well_in(pathumthani1,yang_khi_nok,doubleCrop).
grows_well_in(chainat1,si_suk,doubleCrop).
grows_well_in(chainat1,sang_tho,doubleCrop).
grows_well_in(rd10,sang_tho,doubleCrop).
grows_well_in(pathumthani1,sang_tho,doubleCrop).
grows_well_in(chainat1,sahathat,doubleCrop).
grows_well_in(rd10,sahathat,doubleCrop).
grows_well_in(pathumthani1,sahathat,doubleCrop).
grows_well_in(chainat1,nong_lao,doubleCrop).
grows_well_in(chainat1,hua_don,doubleCrop).
grows_well_in(rd33,hua_don,doubleCrop).
grows_well_in(pathumthani1,hua_don,doubleCrop).
grows_well_in(chainat1,khong_chiam,doubleCrop).
grows_well_in(rd33,khong_chiam,doubleCrop).
grows_well_in(chainat1,na_pho_klang,doubleCrop).
grows_well_in(chainat1,nong_saeng_yai,doubleCrop).
grows_well_in(chainat1,huai_phai,doubleCrop).
grows_well_in(chainat1,kham_hai_yai,doubleCrop).
grows_well_in(chainat1,don_mot_daeng,doubleCrop).
grows_well_in(rd33,don_mot_daeng,doubleCrop).
grows_well_in(rd8,don_mot_daeng,doubleCrop).
grows_well_in(chainat1,tha_mueang,doubleCrop).
grows_well_in(rd33,tha_mueang,doubleCrop).
grows_well_in(rd8,tha_mueang,doubleCrop).
grows_well_in(chainat1,lao_daeng,doubleCrop).
grows_well_in(pathumthani60,lao_daeng,doubleCrop).
grows_well_in(pathumthani1,klang,doubleCrop).
grows_well_in(chainat1,kut_prathai,doubleCrop).
grows_well_in(pathumthani1,kut_prathai,doubleCrop).
grows_well_in(chainat1,kaeng,doubleCrop).
grows_well_in(rd33,kham_khrang,doubleCrop).
grows_well_in(chainat1,kham_khrang,doubleCrop).
grows_well_in(chainat1,top_hu,doubleCrop).
grows_well_in(pathumthani1,top_hu,doubleCrop).
grows_well_in(chainat1,na_krasaeng,doubleCrop).
grows_well_in(chainat1,na_charoen,doubleCrop).
grows_well_in(chainat1,na_suang,doubleCrop).
grows_well_in(pathumthani1,non_sombun,doubleCrop).
grows_well_in(chainat1,pa_mong,doubleCrop).
grows_well_in(chainat1,phon_ngam,doubleCrop).
grows_well_in(pathumthani1,phon_ngam,doubleCrop).
grows_well_in(chainat1,mueang_det,doubleCrop).
grows_well_in(chainat1,som_sa_at,doubleCrop).
grows_well_in(chainat1,kradian,doubleCrop).
grows_well_in(pathumthani1,kradian,doubleCrop).
grows_well_in(pathumthani1,kut_ya_luan,doubleCrop).
grows_well_in(rd33,kut_ya_luan,doubleCrop).
grows_well_in(rd33,kusakon,doubleCrop).
grows_well_in(chainat1,kasem,doubleCrop).
grows_well_in(pathumthani1,kasem,doubleCrop).
grows_well_in(rd33,kasem,doubleCrop).
grows_well_in(chainat1,kham_pia,doubleCrop).
grows_well_in(pathumthani1,kham_pia,doubleCrop).
grows_well_in(rd33,kham_pia,doubleCrop).
grows_well_in(pathumthani1,khulu,doubleCrop).
grows_well_in(chainat1,kham_charoen,doubleCrop).
grows_well_in(chainat1,khok_chan,doubleCrop).
grows_well_in(rd33,se_pet,doubleCrop).
grows_well_in(chainat1,trakan,doubleCrop).
grows_well_in(pathumthani1,trakan,doubleCrop).
grows_well_in(chainat1,tak_daet,doubleCrop).
grows_well_in(rd33,na_phin,doubleCrop).
grows_well_in(chainat1,na_phin,doubleCrop).
grows_well_in(rd10,ban_daeng,doubleCrop).
grows_well_in(pathumthani1,ban_daeng,doubleCrop).
grows_well_in(rd33,saphue,doubleCrop).
grows_well_in(rd10,saphue,doubleCrop).
grows_well_in(pathumthani1,nong_tao,doubleCrop).
grows_well_in(rd13,huai_fai_phatthana,doubleCrop).
grows_well_in(rd33,huai_fai_phatthana,doubleCrop).
grows_well_in(chainat1,huai_fai_phatthana,doubleCrop).
grows_well_in(chainat1,kham_wa,doubleCrop).
grows_well_in(rd10,kham_wa,doubleCrop).
grows_well_in(pathumthani1,kham_wa,doubleCrop).
grows_well_in(chainat1,chik_thoeng,doubleCrop).
grows_well_in(pathumthani1,chik_thoeng,doubleCrop).
grows_well_in(rd33,chik_thoeng,doubleCrop).
grows_well_in(chainat1,tan_sum,doubleCrop).
grows_well_in(pathumthani1,tan_sum,doubleCrop).
grows_well_in(rd33,tan_sum,doubleCrop).
grows_well_in(chainat1,na_khai,doubleCrop).
grows_well_in(pathumthani1,na_khai,doubleCrop).
grows_well_in(rd33,na_khai,doubleCrop).
grows_well_in(chainat1,samrong,doubleCrop).
grows_well_in(chainat1,nong_kung,doubleCrop).
grows_well_in(chainat1,kut_ruea,doubleCrop).
grows_well_in(chainat1,na_chaluai,doubleCrop).
grows_well_in(pathumthani60,na_chaluai,doubleCrop).
grows_well_in(rd33,na_chaluai,doubleCrop).
grows_well_in(chainat1,non_sombun,doubleCrop).
grows_well_in(rd10,non_sombun,doubleCrop).
grows_well_in(chainat1,non_sawan,doubleCrop).
grows_well_in(suphanburi60,non_sawan,doubleCrop).
grows_well_in(chainat1,ban_tum,doubleCrop).
grows_well_in(suphanburi60,ban_tum,doubleCrop).
grows_well_in(rd33,phon_sawan,doubleCrop).
grows_well_in(rd10,phon_sawan,doubleCrop).
grows_well_in(pathumthani60,sok_saeng,doubleCrop).
grows_well_in(rd10,sok_saeng,doubleCrop).
grows_well_in(rd31,kong_phon,doubleCrop).
grows_well_in(rd31,na_tan,doubleCrop).
grows_well_in(rd33,na_tan,doubleCrop).
grows_well_in(rd33,phalan,doubleCrop).
grows_well_in(chainat1,na_di,doubleCrop).
grows_well_in(rd10,na_di,doubleCrop).
grows_well_in(rd8,na_di,doubleCrop).
grows_well_in(rd33,na_yia,doubleCrop).
grows_well_in(rd8,na_yia,doubleCrop).
grows_well_in(pathumthani1,na_yia,doubleCrop).
grows_well_in(pathumthani1,na_rueang,doubleCrop).
grows_well_in(chainat2,khi_lek,doubleCrop).
grows_well_in(chainat1,khi_lek,doubleCrop).
grows_well_in(chainat1,ta_kao,doubleCrop).
grows_well_in(chainat1,phaibun,doubleCrop).
grows_well_in(rd6,phaibun,doubleCrop).
grows_well_in(pathumthani1,song,doubleCrop).
grows_well_in(chainat1,dom_pradit,doubleCrop).
grows_well_in(niawubon2,dom_pradit,doubleCrop).
grows_well_in(niawubon2,bu_pueai,doubleCrop).
grows_well_in(chainat1,yang_yai,doubleCrop).
grows_well_in(chainat1,si_wichian,doubleCrop).
grows_well_in(pathumthani1,kho_laen,doubleCrop).
grows_well_in(chainat1,kho_laen,doubleCrop).
grows_well_in(rd10,kho_laen,doubleCrop).
grows_well_in(chainat1,na_pho,doubleCrop).
grows_well_in(pathumthani1,non_kho,doubleCrop).
grows_well_in(rd33,bua_ngam,doubleCrop).
grows_well_in(rd8,bua_ngam,doubleCrop).
grows_well_in(pathumthani1,bua_ngam,doubleCrop).
grows_well_in(chainat1,ban_maet,doubleCrop).
grows_well_in(rd33,ban_maet,doubleCrop).
grows_well_in(rd4,ban_maet,doubleCrop).
grows_well_in(chainat1,phon_ngam,doubleCrop).
grows_well_in(pathumthani1,nong_sano,doubleCrop).
grows_well_in(chainat1,nong_sano,doubleCrop).
grows_well_in(rd33,nong_sano,doubleCrop).
grows_well_in(chainat1,huai_kha,doubleCrop).
grows_well_in(chainat1,kut_chomphu,doubleCrop).
grows_well_in(rd33,kut_chomphu,doubleCrop).
grows_well_in(suphanburi1,kut_chomphu,doubleCrop).
grows_well_in(chainat1,don_chik,doubleCrop).
grows_well_in(rd33,don_chik,doubleCrop).
grows_well_in(rd10,don_chik,doubleCrop).
grows_well_in(chainat1,sai_mun,doubleCrop).
grows_well_in(rd33,sai_mun,doubleCrop).
grows_well_in(chainat1,na_pho,doubleCrop).
grows_well_in(rd10,na_pho,doubleCrop).
grows_well_in(chainat1,non_klang,doubleCrop).
grows_well_in(rd33,non_klang,doubleCrop).
grows_well_in(suphanburi1,non_klang,doubleCrop).
grows_well_in(chainat1,non_kalong,doubleCrop).
grows_well_in(chainat1,ban_khaem,doubleCrop).
grows_well_in(suphanburi1,ban_khaem,doubleCrop).
grows_well_in(chainat1,pho_sai,doubleCrop).
grows_well_in(rd33,pho_sai,doubleCrop).
grows_well_in(rd10,pho_sai,doubleCrop).
grows_well_in(chainat1,pho_si,doubleCrop).
grows_well_in(rd33,pho_si,doubleCrop).
grows_well_in(chainat1,rawe,doubleCrop).
grows_well_in(chainat1,rai_tai,doubleCrop).
grows_well_in(niawubon2,rai_tai,doubleCrop).
grows_well_in(rd10,rai_tai,doubleCrop).
grows_well_in(chainat1,nong_bua_hi,doubleCrop).
grows_well_in(chainat1,ang_sila,doubleCrop).
grows_well_in(pathumthani1,muang_yai,doubleCrop).
grows_well_in(chainat1,muang_yai,doubleCrop).
grows_well_in(niawsan_pah_tawng,muang_yai,doubleCrop).
grows_well_in(suphanburi1,dum_yai,doubleCrop).
grows_well_in(pathumthani1,dum_yai,doubleCrop).
grows_well_in(chainat1,dum_yai,doubleCrop).
grows_well_in(chainat1,toei,doubleCrop).
grows_well_in(rd10,toei,doubleCrop).
grows_well_in(suphanburi1,na_loeng,doubleCrop).
grows_well_in(chainat1,na_loeng,doubleCrop).
grows_well_in(chainat1,phon_phaeng,doubleCrop).
grows_well_in(suphanburi1,muang_sam_sip,doubleCrop).
grows_well_in(chainat1,muang_sam_sip,doubleCrop).
grows_well_in(pathumthani1,yang_sak_krapho_lum,doubleCrop).
grows_well_in(chainat1,yang_sak_krapho_lum,doubleCrop).
grows_well_in(chainat1,nong_khai_nok,doubleCrop).
grows_well_in(rd10,nong_chang_yai,doubleCrop).
grows_well_in(pathumthani1,nong_chang_yai,doubleCrop).
grows_well_in(chainat1,nong_chang_yai,doubleCrop).
grows_well_in(pathumthani1,nong_lao,doubleCrop).
grows_well_in(pathumthani1,nong_hang,doubleCrop).
grows_well_in(chainat1,nong_hang,doubleCrop).
grows_well_in(rd33,krasop,doubleCrop).
grows_well_in(pathumthani1,krasop,doubleCrop).
grows_well_in(chainat1,krasop,doubleCrop).
grows_well_in(rd33,kut_lat,doubleCrop).
grows_well_in(pathumthani1,kut_lat,doubleCrop).
grows_well_in(chainat1,kut_lat,doubleCrop).
grows_well_in(pathumthani1,kham_yai,doubleCrop).
grows_well_in(chainat1,kham_yai,doubleCrop).
grows_well_in(rd33,khi_lek,doubleCrop).
grows_well_in(pathumthani1,khi_lek,doubleCrop).
grows_well_in(chainat1,khi_lek,doubleCrop).
grows_well_in(rd33,chaeramae,doubleCrop).
grows_well_in(rd10,chaeramae,doubleCrop).
grows_well_in(chainat1,chaeramae,doubleCrop).
grows_well_in(chainat1,pathum,doubleCrop).
grows_well_in(suphanburi1,pa_ao,doubleCrop).
grows_well_in(rd33,pa_ao,doubleCrop).
grows_well_in(chainat1,pa_ao,doubleCrop).
grows_well_in(chainat1,rai_noi,doubleCrop).
grows_well_in(rd10,rai_noi,doubleCrop).
grows_well_in(rd33,nong_khon,doubleCrop).
grows_well_in(chainat1,nong_khon,doubleCrop).
grows_well_in(pathumthani1,nong_bo,doubleCrop).
grows_well_in(rd33,nong_bo,doubleCrop).
grows_well_in(chainat1,nong_bo,doubleCrop).
grows_well_in(pathumthani1,hua_ruea,doubleCrop).
grows_well_in(rd33,hua_ruea,doubleCrop).
grows_well_in(chainat1,hua_ruea,doubleCrop).
grows_well_in(pathumthani1,kham_khwang,doubleCrop).
grows_well_in(chainat1,kham_khwang,doubleCrop).
grows_well_in(rd33,kham_nam_sap,doubleCrop).
grows_well_in(chainat1,kham_nam_sap,doubleCrop).
grows_well_in(pathumthani1,khu_mueang,doubleCrop).
grows_well_in(rd33,khu_mueang,doubleCrop).
grows_well_in(rd10,khu_mueang,doubleCrop).
grows_well_in(chainat1,tha_lat,doubleCrop).
grows_well_in(pathumthani1,tha_lat,doubleCrop).
grows_well_in(pathumthani1,that,doubleCrop).
grows_well_in(niawubon2,that,doubleCrop).
grows_well_in(rd10,that,doubleCrop).
grows_well_in(rd33,non_phueng,doubleCrop).
grows_well_in(chainat1,non_phueng,doubleCrop).
grows_well_in(rd10,non_phueng,doubleCrop).
grows_well_in(rd33,non_non,doubleCrop).
grows_well_in(rd33,bung_wai,doubleCrop).
grows_well_in(rd33,bung_mai,doubleCrop).
grows_well_in(pathumthani1,bung_mai,doubleCrop).
grows_well_in(chainat1,bung_mai,doubleCrop).
grows_well_in(rd33,mueang_si_khai,doubleCrop).
grows_well_in(pathumthani1,mueang_si_khai,doubleCrop).
grows_well_in(chainat1,mueang_si_khai,doubleCrop).
grows_well_in(rd33,sa_saming,doubleCrop).
grows_well_in(pathumthani1,sa_saming,doubleCrop).
grows_well_in(chainat1,sa_saming,doubleCrop).
grows_well_in(rd10,saen_suk,doubleCrop).
grows_well_in(pathumthani1,saen_suk,doubleCrop).
grows_well_in(pathumthani1,nong_kin_phlen,doubleCrop).
grows_well_in(rd33,nong_kin_phlen,doubleCrop).
grows_well_in(rd10,nong_kin_phlen,doubleCrop).
grows_well_in(pathumthani1,huai_khayung,doubleCrop).
grows_well_in(rd33,huai_khayung,doubleCrop).
grows_well_in(chainat1,huai_khayung,doubleCrop).
grows_well_in(suphanburi1,kaeng_kok,doubleCrop).
grows_well_in(rd29,don_yai,doubleCrop).
grows_well_in(rd33,tabai,doubleCrop).
grows_well_in(pathumthani1,na_kham,doubleCrop).
grows_well_in(rd33,na_kham,doubleCrop).
grows_well_in(rd10,na_kham,doubleCrop).
grows_well_in(rd29,song_yang,doubleCrop).
grows_well_in(rd30,ueat_yai,doubleCrop).
grows_well_in(pathumthani1,ueat_yai,doubleCrop).
grows_well_in(rd23,ueat_yai,doubleCrop).
grows_well_in(chainat1,kaeng_dom,doubleCrop).
grows_well_in(pathumthani1,kaeng_dom,doubleCrop).
grows_well_in(rd10,kaeng_dom,doubleCrop).
grows_well_in(chainat1,tha_chang,doubleCrop).
grows_well_in(rd33,tha_chang,doubleCrop).
grows_well_in(rd10,tha_chang,doubleCrop).
grows_well_in(chainat1,bung_malaeng,doubleCrop).
grows_well_in(rd33,bung_malaeng,doubleCrop).
grows_well_in(rd10,bung_malaeng,doubleCrop).
grows_well_in(chainat1,sawang,doubleCrop).
grows_well_in(niawubon2,sawang,doubleCrop).
grows_well_in(rd10,sawang,doubleCrop).
grows_well_in(chainat1,kham_pom,doubleCrop).
grows_well_in(pathumthani1,kho_noi,doubleCrop).
grows_well_in(rd33,kho_noi,doubleCrop).
grows_well_in(chainat1,khok_kong,doubleCrop).
grows_well_in(rd33,khok_kong,doubleCrop).
grows_well_in(chainat1,khok_sawang,doubleCrop).
grows_well_in(suphanburi1,khok_sawang,doubleCrop).
grows_well_in(pathumthani1,non_klang,doubleCrop).
grows_well_in(rd33,non_kalen,doubleCrop).
grows_well_in(chainat1,non_kalen,doubleCrop).
grows_well_in(chainat1,samrong,doubleCrop).
grows_well_in(pathumthani1,nong_hai,doubleCrop).
grows_well_in(chainat1,nong_hai,doubleCrop).
grows_well_in(chainat1,khan_rai,doubleCrop).
grows_well_in(rd33,khan_rai,doubleCrop).
grows_well_in(sakonnakhon,khan_rai,doubleCrop).
grows_well_in(chainat1,kham_khuean_kaeo,doubleCrop).
grows_well_in(rd33,kham_khuean_kaeo,doubleCrop).
grows_well_in(sakonnakhon,nikhom_lam_dom_noi,doubleCrop).
grows_well_in(rd33,nikhom_lam_dom_noi,doubleCrop).
grows_well_in(sakonnakhon,non_ko,doubleCrop).
grows_well_in(chainat1,fang_kham,doubleCrop).
grows_well_in(rd33,fang_kham,doubleCrop).
grows_well_in(sakonnakhon,fang_kham,doubleCrop).
grows_well_in(chainat1,phaeng_yai,doubleCrop).
grows_well_in(pathumthani1,phaeng_yai,doubleCrop).
grows_well_in(chainat1,phon_mueang,doubleCrop).
grows_well_in(chainat1,nong_bok,doubleCrop).
grows_well_in(chainat1,lao_suea_kok,doubleCrop).