:- module(rice_tolerance_with_disease, []).
% tolerance_with(riceName disease).
tolerance_with(rd5,bacterialLeafBlight).
tolerance_with(rd5,riceBlast).
tolerance_with(rd5,riceTungro).
tolerance_with(rd13,riceBlast).
tolerance_with(rd15,brownSpot).
tolerance_with(rd27,riceRaggedStunt).
tolerance_with(rd27,sheathBlight).
tolerance_with(rd35,bacterialLeafBlight).
tolerance_with(rd51,none).
tolerance_with(rd59,none).
tolerance_with(gowruang88,none).
tolerance_with(jasmine105,none).
tolerance_with(khaotahhaeng17,none).
tolerance_with(khaopahkmaw148,none).
tolerance_with(khaojowhawmphitsanulok1,riceBlast).
tolerance_with(khaojowhawmphitsanulok1,bacterialLeafBlight).
tolerance_with(khaojowhawmphitsanulok1,riceRaggedStunt).
tolerance_with(chiangphatthalung,none).
tolerance_with(chumpae60,none).
tolerance_with(queen132,brownSpot).
tolerance_with(queen132,riceTungro).
tolerance_with(ms_mons_4,none).
tolerance_with(saguiwater19,none).
tolerance_with(watertaro43,none).
tolerance_with(pathumthani60,sheathRot).
tolerance_with(pathumthani60,riceRaggedStunt).
tolerance_with(puangrai2,brownSpot).
tolerance_with(phattaling60,none).
tolerance_with(phitsanulok3,riceBlast).
tolerance_with(phitsanulok60_1,bacterialLeafBlight).
tolerance_with(phitsanulok60_1,riceRaggedStunt).
tolerance_with(phitsanulok60_1,sheathRot).
tolerance_with(phitsanulok80,none).
tolerance_with(lookdaengpattani,riceBlast).
tolerance_with(lebnokpattani,none).
tolerance_with(ptnc09002_59,none).
tolerance_with(leuangyai148,brownSpot).
tolerance_with(leuangyai148,bacterialLeafBlight).
tolerance_with(khemtawngphatthalung,bacterialLeafBlight).
tolerance_with(khaoluangsan_pah_twang,none).
tolerance_with(gaenjan,riceRaggedStunt).
tolerance_with(gaenjan,narrowBrownSpot).
tolerance_with(pttc02019_1,none).
tolerance_with(khaogawdiaw35,none).
tolerance_with(cholung97,none).
tolerance_with(khaimodrin3,none).
tolerance_with(rd6,none).
tolerance_with(rd8,brownSpot).
tolerance_with(nongkai80,riceBlast).
tolerance_with(rd16,riceBlast).
tolerance_with(rd18,riceBlast).
tolerance_with(rd20,riceBlast).
tolerance_with(gampai15,riceBlast).
tolerance_with(gampai15,riceTungro).
tolerance_with(hahngyu71,riceBlast).
tolerance_with(hahngyu71,brownSpot).
tolerance_with(mueynawng62m,brownSpot).
tolerance_with(mueynawng62m,riceTungro).
tolerance_with(niawdammor37,none).
tolerance_with(niawkiawngoo8974,riceBlast).
tolerance_with(niawkiawngoo8974,bacterialLeafBlight).
tolerance_with(niawsan_pah_tawng,brownSpot).
tolerance_with(niawsan_pah_tawng,riceBlast).
tolerance_with(niawubon1,riceTungro).
tolerance_with(niawubon2,riceBlast).
tolerance_with(leuangpratew123,bacterialLeafBlight).
tolerance_with(leuangpratew123,riceRaggedStunt).
tolerance_with(ptnc96004_49,none).
tolerance_with(rd1,brownSpot).
tolerance_with(rd3,none).
tolerance_with(rd7,bacterialLeafBlight).
tolerance_with(rd7,riceTungro).
tolerance_with(rd9,riceRaggedStunt).
tolerance_with(rd11,riceBlast).
tolerance_with(rd11,brownSpot).
tolerance_with(rd21,riceRaggedStunt).
tolerance_with(rd21,bacterialLeafBlight).
tolerance_with(rd23,bacterialLeafBlight).
tolerance_with(rd23,riceRaggedStunt).
tolerance_with(rd25,bacterialLeafBlight).
tolerance_with(rd25,riceRaggedStunt).
tolerance_with(rd29,bacterialLeafBlight).
tolerance_with(rd31,bacterialLeafBlight).
tolerance_with(rd31,brownSpot).
tolerance_with(rd31,dirtyPanicle).
tolerance_with(rd33,riceBlast).
tolerance_with(rd37,riceBlast).
tolerance_with(rd37,bacterialLeafBlight).
tolerance_with(rd39,riceBlast).
tolerance_with(rd39,bacterialLeafBlight).
tolerance_with(rd41,none).
tolerance_with(rd43,riceBlast).
tolerance_with(rd47,riceBlast).
tolerance_with(rd49,riceBlast).
tolerance_with(rd53,none).
tolerance_with(rd55,riceBlast).
tolerance_with(rd55,bacterialLeafBlight).
tolerance_with(rd57,none).
tolerance_with(rd61,none).
tolerance_with(rd63,none).
tolerance_with(khaojowhawmkhlongluang1,riceBlast).
tolerance_with(khaojowhawmkhlongluang1,bacterialLeafBlight).
tolerance_with(khaojowhawmsuphanburi,bacterialLeafBlight).
tolerance_with(chainat1,riceRaggedStunt).
tolerance_with(chainat1,riceBlast).
tolerance_with(chainat2,none).
tolerance_with(pathumthani1,none).
tolerance_with(bangtaen,riceBlast).
tolerance_with(patthalung,none).
tolerance_with(phitsanulok2,none).
tolerance_with(phitsanulok60_2,sheathRot).
tolerance_with(phitsanulok60_2,riceBlast).
tolerance_with(phitsanulok60_2,bacterialLeafBlight).
tolerance_with(suphanburi1,riceBlast).
tolerance_with(suphanburi1,bacterialLeafBlightriceRaggedStunt).
tolerance_with(suphanburi1,riceTungro).
tolerance_with(suphanburi2,riceBlast).
tolerance_with(suphanburi2,bacterialLeafBlight).
tolerance_with(suphanburi2,riceRaggedStunt).
tolerance_with(suphanburi2,riceTungro).
tolerance_with(suphanburi3,riceBlast).
tolerance_with(suphanburi3,bacterialLeafBlight).
tolerance_with(suphanburi60,riceTungro).
tolerance_with(suphanburi60,riceBlast).
tolerance_with(suphanburi90,riceBlast).
tolerance_with(suphanburi90,bacterialLeafBlight).
tolerance_with(suphanburi90,riceRaggedStunt).
tolerance_with(suphanburi90,riceTungro).
tolerance_with(surin1,riceBlast).
tolerance_with(surin1,bacterialLeafBlight).
tolerance_with(rd2,brownSpot).
tolerance_with(rd2,riceTungro).
tolerance_with(rd4,none).
tolerance_with(rd10,none).
tolerance_with(rd14,riceBlast).
tolerance_with(rd14,bacterialLeafBlight).
tolerance_with(rd_maejo2,none).
tolerance_with(phrae1,bacterialLeafBlight).
tolerance_with(phrae1,riceRaggedStunt).
tolerance_with(sakonnakhon,none).
tolerance_with(san_pah_tawng1,riceBlast).
tolerance_with(san_pah_tawng1,bacterialLeafBlight).
tolerance_with(tapowgaew161,brownSpot).
tolerance_with(nahngcha_lawng,riceBlast).
tolerance_with(nahngcha_lawng,brownSpot).
tolerance_with(pingaew56,none).
tolerance_with(plaingahmprachinburi,riceBlast).
tolerance_with(lebmeunahng111,brownSpot).
tolerance_with(khaobahnnah432,none).
tolerance_with(rd19,bacterialLeafBlight).
tolerance_with(rd45,none).
tolerance_with(hantra60,riceBlast).
tolerance_with(prachinburi1,riceBlast).
tolerance_with(prachinburi1,bacterialLeafStreak).
tolerance_with(prachinburi2,riceBlast).
tolerance_with(prachinburi2,bacterialLeafBlight).
tolerance_with(ayutthaya1,riceBlast).
tolerance_with(ayutthaya1,bacterialLeafBlight).
tolerance_with(ayutthaya1,riceTungro).
tolerance_with(rd17,bacterialLeafBlight).
tolerance_with(goomeuangluang,riceBlast).
tolerance_with(goomeuangluang,brownSpot).
tolerance_with(goomeuangluang,narrowBrownSpot).
tolerance_with(khaopongkrai,riceBlast).
tolerance_with(khaopongkrai,bacterialLeafBlight).
tolerance_with(jowhaw,riceBlast).
tolerance_with(jowhaw,gallDwarf).
tolerance_with(sewmaejan,riceBlast).
tolerance_with(dawkpa_yawm,riceBlast).
tolerance_with(dawkpa_yawm,brownSpot).
tolerance_with(dawkpa_yawm,narrowBrownSpot).
tolerance_with(namroo,dirtyPanicle).
tolerance_with(namroo,riceBlast).
tolerance_with(jowlisawsan_pah_tawng,riceBlast).
tolerance_with(jowkhaochiangmai,none).
tolerance_with(leumpua,none).
tolerance_with(redhawnrice,riceBlast).
tolerance_with(sangyodphattalung,none).
tolerance_with(redroserice,none).
tolerance_with(khao_yipundoa1,none).
tolerance_with(khao_yipundoa2,none).
tolerance_with(samerng1,none).
tolerance_with(samerng2,none).
tolerance_with(cp304,riceBlast).
tolerance_with(rdh1,none).
tolerance_with(rdp3,riceBlast).
tolerance_with(phrae60,none).
tolerance_with(fahng60,none).
