:- module(rice_tolerance_with_insect, []).
# tolerance_with(riceName,insect).
tolerance_with(rd5,none).
tolerance_with(rd13,none).
tolerance_with(rd15,none).
tolerance_with(rd27,none).
tolerance_with(rd35,none).
tolerance_with(rd51,none).
tolerance_with(rd59,none).
tolerance_with(gowruang88,greenRiceLeafHopper).
tolerance_with(jasmine105,greenRiceLeafHopper).
tolerance_with(khaotahhaeng17,riceGallMidge).
tolerance_with(khaopahkmaw148,none).
tolerance_with(khaojowhawmphitsanulok1,none).
tolerance_with(chiangphatthalung,none).
tolerance_with(chumpae60,brownPlantHopper).
tolerance_with(chumpae60,greenRiceLeafHopper).
tolerance_with(chumpae60,whiteBackedPlantHopper).
tolerance_with(queen132,greenRiceLeafHopper).
tolerance_with(ms_mons_4,none).
tolerance_with(saguiwater19,none).
tolerance_with(watertaro43,none).
tolerance_with(pathumthani60,none).
tolerance_with(puangrai2,greenRiceLeafHopper).
tolerance_with(phattaling60,none).
tolerance_with(phitsanulok3,none).
tolerance_with(phitsanulok60_1,riceGallMidge).
tolerance_with(phitsanulok80,none).
tolerance_with(lookdaengpattani,none).
tolerance_with(lebnokpattani,none).
tolerance_with(ptnc09002_59,none).
tolerance_with(leuangyai148,none).
tolerance_with(khemtawngphatthalung,none).
tolerance_with(khaoluangsan_pah_twang,none).
tolerance_with(gaenjan,greenRiceLeafHopper).
tolerance_with(pttc02019_1,none).
tolerance_with(khaogawdiaw35,none).
tolerance_with(cholung97,none).
tolerance_with(khaimodrin3,none).
tolerance_with(rd6,none).
tolerance_with(rd8,none).
tolerance_with(nongkai80,none).
tolerance_with(rd16,none).
tolerance_with(rd18,none).
tolerance_with(rd20,none).
tolerance_with(gampai15,none).
tolerance_with(hahngyu71,none).
tolerance_with(mueynawng62m,riceGallMidge).
tolerance_with(niawdammor37,none).
tolerance_with(niawkiawngoo8974,none).
tolerance_with(niawsan_pah_tawng,none).
tolerance_with(niawubon1,none).
tolerance_with(niawubon2,none).
tolerance_with(leuangpratew123,none).
tolerance_with(ptnc96004_49,none).
tolerance_with(rd1,none).
tolerance_with(rd3,greenRiceLeafHopper).
tolerance_with(rd7,greenRiceLeafHopper).
tolerance_with(rd9,none).
tolerance_with(rd11,none).
tolerance_with(rd21,none).
tolerance_with(rd23,none).
tolerance_with(rd25,brownPlantHopper).
tolerance_with(rd25,stemBorer).
tolerance_with(rd29,brownPlantHopper).
tolerance_with(rd31,brownPlantHopper).
tolerance_with(rd31,whiteBackedPlantHopper).
tolerance_with(rd33,none).
tolerance_with(rd37,whiteBackedPlantHopper).
tolerance_with(rd39,none).
tolerance_with(rd41,none).
tolerance_with(rd43,brownPlantHopper).
tolerance_with(rd47,none).
tolerance_with(rd49,brownPlantHopper).
tolerance_with(rd53,riceGallMidge).
tolerance_with(rd55,none).
tolerance_with(rd57,none).
tolerance_with(rd61,brownPlantHopper).
tolerance_with(rd61,whiteBackedPlantHopper).
tolerance_with(rd63,brownPlantHopper).
tolerance_with(khaojowhawmkhlongluang1,whiteBackedPlantHopper).
tolerance_with(khaojowhawmsuphanburi,whiteBackedPlantHopper).
tolerance_with(chainat1,brownPlantHopper).
tolerance_with(chainat1,whiteBackedPlantHopper).
tolerance_with(chainat2,brownPlantHopper).
tolerance_with(pathumthani1,brownPlantHopper).
tolerance_with(pathumthani1,whiteBackedPlantHopper).
tolerance_with(bangtaen,brownPlantHopper).
tolerance_with(bangtaen,greenRiceLeafHopper).
tolerance_with(patthalung,none).
tolerance_with(phitsanulok2,brownPlantHopper).
tolerance_with(phitsanulok2,whiteBackedPlantHopper).
tolerance_with(phitsanulok2,greenRiceLeafHopper).
tolerance_with(phitsanulok60_2,brownPlantHopper).
tolerance_with(suphanburi1,brownPlantHopper).
tolerance_with(suphanburi1,whiteBackedPlantHopper).
tolerance_with(suphanburi2,brownPlantHopper).
tolerance_with(suphanburi3,brownPlantHopper).
tolerance_with(suphanburi60,brownPlantHopper).
tolerance_with(suphanburi60,greenRiceLeafHopper).
tolerance_with(suphanburi90,brownPlantHopper).
tolerance_with(suphanburi90,greenRiceLeafHopper).
tolerance_with(surin1,none).
tolerance_with(rd2,greenRiceLeafHopper).
tolerance_with(rd4,riceGallMidge).
tolerance_with(rd4,brownPlantHopper).
tolerance_with(rd4,greenRiceLeafHopper).
tolerance_with(rd10,none).
tolerance_with(rd14,none).
tolerance_with(rd_maejo2,none).
tolerance_with(phrae1,brownPlantHopper).
tolerance_with(sakonnakhon,none).
tolerance_with(san_pah_tawng1,none).
tolerance_with(tapowgaew161,none).
tolerance_with(nahngcha_lawng,none).
tolerance_with(pingaew56,none).
tolerance_with(plaingahmprachinburi,none).
tolerance_with(lebmeunahng111,none).
tolerance_with(khaobahnnah432,none).
tolerance_with(rd19,none).
tolerance_with(rd45,none).
tolerance_with(hantra60,none).
tolerance_with(prachinburi1,stemBorer).
tolerance_with(prachinburi2,none).
tolerance_with(prachinburi2,none).
tolerance_with(ayutthaya1,none).
tolerance_with(ayutthaya1,none).
tolerance_with(rd17,none).
tolerance_with(goomeuangluang,none).
tolerance_with(khaopongkrai,none).
tolerance_with(jowhaw,none).
tolerance_with(sewmaejan,none).
tolerance_with(dawkpa_yawm,none).
tolerance_with(namroo,none).
tolerance_with(jowlisawsan_pah_tawng,none).
tolerance_with(jowkhaochiangmai,none).
tolerance_with(leumpua,none).
tolerance_with(redhawnrice,brownPlantHopper).
tolerance_with(sangyodphattalung,none).
tolerance_with(redroserice,none).
tolerance_with(khao_yipundoa1,none).
tolerance_with(khao_yipundoa2,none).
tolerance_with(samerng1,none).
tolerance_with(samerng2,none).
tolerance_with(cp304,none).
tolerance_with(rdh1,none).
tolerance_with(rdp3,whiteBackedPlantHopper).
tolerance_with(samerng1,none).
tolerance_with(samerng2,none).
tolerance_with(phrae60,none).
tolerance_with(fahng60,none).