:- module(rice_fact, []).
rice(rd5).
rice(rd13).
rice(rd15).
rice(rd27).
rice(rd35).
rice(rd51).
rice(rd59).
rice(gowruang88).
rice(jasmine105).
rice(khaotahhaeng17).
rice(khaopahkmaw148).
rice(khaojowhawmphitsanulok1).
rice(chiangphatthalung).
rice(chumpae60).
rice(queen132).
rice(ms_mons_4).
rice(saguiwater19).
rice(watertaro43).
rice(pathumthani60).
rice(puangrai2).
rice(phattaling60).
rice(phitsanulok3).
rice(phitsanulok601).
rice(phitsanulok80).
rice(lookdaengpattani).
rice(lebnokpattani).
rice(ptnc0900259).
rice(leuangyai148).
rice(khemtawngphatthalung).
rice(khaoluangsanpahtwang).
rice(gaenjan).
rice(pttc020191).
rice(khaogawdiaw35).
rice(cholung97).
rice(khaimodrin3).
rice(rd6).
rice(rd8).
rice(nongkai80).
rice(rd16).
rice(rd18).
rice(rd20).
rice(gampai15).
rice(hahngyu71).
rice(mueynawng62m).
rice(niawdammor37).
rice(niawkiawngoo8974).
rice(niawsanpahtawng).
rice(niawubon1).
rice(niawubon2).
rice(leuangpratew123).
rice(ptnc9600449).
rice(rd1).
rice(rd3).
rice(rd7).
rice(rd9).
rice(rd11).
rice(rd21).
rice(rd23).
rice(rd25).
rice(rd29).
rice(rd31).
rice(rd33).
rice(rd37).
rice(rd39).
rice(rd41).
rice(rd43).
rice(rd47).
rice(rd49).
rice(rd53).
rice(rd55).
rice(rd57).
rice(rd61).
rice(rd63).
rice(khaojowhawmkhlongluang1).
rice(khaojowhawmsuphanburi).
rice(chainat1).
rice(chainat2).
rice(pathumthani1).
rice(bangtaen).
rice(patthalung).
rice(phitsanulok2).
rice(phitsanulok602).
rice(suphanburi1).
rice(suphanburi2).
rice(suphanburi3).
rice(suphanburi60).
rice(suphanburi90).
rice(surin1).
rice(rd2).
rice(rd4).
rice(rd10).
rice(rd14).
rice(rdmaejo2).
rice(phrae1).
rice(sakonnakhon).
rice(sanpahtawng1).
rice(tapowgaew161).
rice(nahngchalawng).
rice(pingaew56).
rice(plaingahmprachinburi).
rice(lebmeunahng111).
rice(khaobahnnah432).
rice(rd19).
rice(rd45).
rice(hantra60).
rice(prachinburi1).
rice(prachinburi2).
rice(ayutthaya1).
rice(ayutthaya1).
rice(rd17).
rice(goomeuangluang).
rice(khaopongkrai).
rice(jowhaw).
rice(sewmaejan).
rice(dawkpayawm).
rice(namroo).
rice(jowlisawsanpahtawng).
rice(jowkhaochiangmai).
rice(leumpua).
rice(r258).
rice(redhawnrice).
rice(sangyodphattalung).
rice(redroserice).
rice(khaoyipundoa1).
rice(khaoyipundoa2).
rice(samerng1).
rice(samerng2).
rice(cp304).
rice(rdh1).
rice(rdp3).
rice(samerng1).
rice(samerng2).
rice(phrae60).
rice(fahng60).
