:- module(rice_properties, []).
% has_property(riceName,riceType,yield,photoPeriod,specialCase).
has_properties(rd5,nonGlutinous,567,sensitivity,none).
has_properties(rd13,nonGlutinous,450,sensitivity,none).
has_properties(rd15,nonGlutinous,560,sensitivity,none).
has_properties(rd27,nonGlutinous,600,sensitivity,none).
has_properties(rd35,nonGlutinous,650,sensitivity,none).
has_properties(rd51,nonGlutinous,536,sensitivity,none).
has_properties(rd59,nonGlutinous,624,sensitivity,none).
has_properties(gowruang88,nonGlutinous,420,sensitivity,none).
has_properties(jasmine105,nonGlutinous,363,sensitivity,none).
has_properties(khaotahhaeng17,nonGlutinous,473,sensitivity,none).
has_properties(khaopahkmaw148,nonGlutinous,415,sensitivity,none).
has_properties(khaojowhawmphitsanulok1,nonGlutinous,579,sensitivity,none).
has_properties(chiangphatthalung,nonGlutinous,470,sensitivity,none).
has_properties(chumpae60,nonGlutinous,564,sensitivity,none).
has_properties(queen132,nonGlutinous,486,sensitivity,none).
has_properties(ms_mons_4,nonGlutinous,436,sensitivity,none).
has_properties(saguiwater19,nonGlutinous,499,sensitivity,none).
has_properties(watertaro43,nonGlutinous,450,sensitivity,none).
has_properties(pathumthani60,nonGlutinous,517,sensitivity,none).
has_properties(puangrai2,nonGlutinous,437,sensitivity,none).
has_properties(phattaling60,nonGlutinous,457,sensitivity,none).
has_properties(phitsanulok3,nonGlutinous,604,sensitivity,none).
has_properties(phitsanulok60_1,nonGlutinous,550,sensitivity,none).
has_properties(phitsanulok80,nonGlutinous,637,sensitivity,none).
has_properties(lookdaengpattani,nonGlutinous,418,sensitivity,none).
has_properties(lebnokpattani,nonGlutinous,480,sensitivity,none).
has_properties(ptnc09002_59,nonGlutinous,390,sensitivity,none).
has_properties(leuangyai148,nonGlutinous,548,sensitivity,none).
has_properties(khemtawngphatthalung,nonGlutinous,529,sensitivity,none).
has_properties(khaoluangsan_pah_twang,nonGlutinous,582,sensitivity,none).
has_properties(gaenjan,nonGlutinous,660,sensitivity,none).
has_properties(pttc02019_1,nonGlutinous,812,sensitivity,none).
has_properties(khaogawdiaw35,nonGlutinous,500,sensitivity,none).
has_properties(cholung97,nonGlutinous,564,sensitivity,none).
has_properties(khaimodrin3,nonGlutinous,436,sensitivity,none).
has_properties(rd6,glutinous,666,sensitivity,none).
has_properties(rd8,glutinous,585,sensitivity,none).
has_properties(nongkai80,glutinous,472,sensitivity,none).
has_properties(rd16,glutinous,633,sensitivity,none).
has_properties(rd18,glutinous,609,sensitivity,none).
has_properties(rd20,glutinous,498,sensitivity,none).
has_properties(gampai15,glutinous,569,sensitivity,none).
has_properties(hahngyu71,glutinous,506,sensitivity,none).
has_properties(mueynawng62m,glutinous,540,sensitivity,none).
has_properties(niawdammor37,glutinous,378,sensitivity,none).
has_properties(niawkiawngoo8974,glutinous,427.5,sensitivity,none).
has_properties(niawsan_pah_tawng,glutinous,526,sensitivity,none).
has_properties(niawubon1,glutinous,660,sensitivity,none).
has_properties(niawubon2,glutinous,463,sensitivity,none).
has_properties(leuangpratew123,glutinous,414,sensitivity,none).
has_properties(ptnc96004_49,glutinous,0,sensitivity,none).
has_properties(rd1,nonGlutinous,742,nonSensitivity,none).
has_properties(rd3,nonGlutinous,667,nonSensitivity,none).
has_properties(rd7,nonGlutinous,672,nonSensitivity,none).
has_properties(rd9,nonGlutinous,657,nonSensitivity,none).
has_properties(rd11,nonGlutinous,700,nonSensitivity,none).
has_properties(rd21,nonGlutinous,700,nonSensitivity,none).
has_properties(rd23,nonGlutinous,800,nonSensitivity,none).
has_properties(rd25,nonGlutinous,650,nonSensitivity,none).
has_properties(rd29,nonGlutinous,876,nonSensitivity,none).
has_properties(rd31,nonGlutinous,745,nonSensitivity,indirectSeedling).
has_properties(rd31,nonGlutinous,738,nonSensitivity,wetDirectSeedling).
has_properties(rd33,nonGlutinous,493,nonSensitivity,none).
has_properties(rd37,nonGlutinous,602,nonSensitivity,none).
has_properties(rd39,nonGlutinous,577,nonSensitivity,none).
has_properties(rd41,nonGlutinous,722,nonSensitivity,none).
has_properties(rd43,nonGlutinous,561,nonSensitivity,none).
has_properties(rd47,nonGlutinous,793,nonSensitivity,none).
has_properties(rd49,nonGlutinous,733,nonSensitivity,none).
has_properties(rd53,nonGlutinous,999,nonSensitivity,none).
has_properties(rd55,nonGlutinous,825,nonSensitivity,none).
has_properties(rd57,nonGlutinous,714,nonSensitivity,none).
has_properties(rd61,nonGlutinous,1004,nonSensitivity,none).
has_properties(rd63,nonGlutinous,667,nonSensitivity,none).
has_properties(khaojowhawmkhlongluang1,nonGlutinous,650,nonSensitivity,inSeason).
has_properties(khaojowhawmkhlongluang1,nonGlutinous,591,nonSensitivity,doubleCrop).
has_properties(khaojowhawmsuphanburi,nonGlutinous,582,nonSensitivity,doubleCrop).
has_properties(khaojowhawmsuphanburi,nonGlutinous,673,nonSensitivity,inSeason).
has_properties(chainat1,nonGlutinous,740,nonSensitivity,none).
has_properties(chainat2,nonGlutinous,657,nonSensitivity,none).
has_properties(pathumthani1,nonGlutinous,712,nonSensitivity,none).
has_properties(bangtaen,nonGlutinous,705,nonSensitivity,inSeason).
has_properties(bangtaen,nonGlutinous,827,nonSensitivity,doubleCrop).
has_properties(patthalung,nonGlutinous,714,nonSensitivity,wetDirectSeedling).
has_properties(phitsanulok2,nonGlutinous,807,nonSensitivity,none).
has_properties(phitsanulok60_2,nonGlutinous,740,nonSensitivity,none).
has_properties(suphanburi1,nonGlutinous,806,nonSensitivity,none).
has_properties(suphanburi2,nonGlutinous,700,nonSensitivity,none).
has_properties(suphanburi3,nonGlutinous,772,nonSensitivity,none).
has_properties(suphanburi60,nonGlutinous,700,nonSensitivity,none).
has_properties(suphanburi90,nonGlutinous,600,nonSensitivity,none).
has_properties(surin1,nonGlutinous,718,nonSensitivity,none).
has_properties(rd2,glutinous,766,nonSensitivity,none).
has_properties(rd4,glutinous,573,nonSensitivity,none).
has_properties(rd10,glutinous,660,nonSensitivity,none).
has_properties(rd14,glutinous,666,nonSensitivity,none).
has_properties(rd_maejo2,glutinous,865,nonSensitivity,none).
has_properties(phrae1,glutinous,685,nonSensitivity,none).
has_properties(sakonnakhon,glutinous,467,nonSensitivity,none).
has_properties(san_pah_tawng1,glutinous,630,nonSensitivity,none).
has_properties(tapowgaew161,nonGlutinous,350,sensitivity,none).
has_properties(nahngcha_lawng,glutinous,394,sensitivity,none).
has_properties(pingaew56,nonGlutinous,362,sensitivity,none).
has_properties(plaingahmprachinburi,nonGlutinous,380,sensitivity,none).
has_properties(lebmeunahng111,nonGlutinous,328,sensitivity,none).
has_properties(khaobahnnah432,nonGlutinous,449,sensitivity,none).
has_properties(rd19,nonGlutinous,570,sensitivity,none).
has_properties(rd45,nonGlutinous,520,sensitivity,none).
has_properties(hantra60,nonGlutinous,425,sensitivity,none).
has_properties(prachinburi1,nonGlutinous,450,sensitivity,none).
has_properties(prachinburi2,nonGlutinous,846,sensitivity,waterLevel25cm).
has_properties(prachinburi2,nonGlutinous,590,sensitivity,waterLevel100cm).
has_properties(ayutthaya1,nonGlutinous,546,sensitivity,waterLevel100cm).
has_properties(ayutthaya1,nonGlutinous,845,sensitivity,waterLevel25cm).
has_properties(rd17,nonGlutinous,645,nonSensitivity,none).
has_properties(goomeuangluang,nonGlutinous,240,sensitivity,none).
has_properties(khaopongkrai,glutinous,243,sensitivity,none).
has_properties(jowhaw,nonGlutinous,210,sensitivity,none).
has_properties(sewmaejan,glutinous,456,sensitivity,none).
has_properties(dawkpa_yawm,nonGlutinous,250,sensitivity,none).
has_properties(namroo,nonGlutinous,247,sensitivity,none).
has_properties(jowlisawsan_pah_tawng,nonGlutinous,391,sensitivity,none).
has_properties(jowkhaochiangmai,nonGlutinous,369.5,sensitivity,none).
has_properties(leumpua,glutinous,0,sensitivity,none).
has_properties(redhawnrice,nonGlutinous,643,sensitivity,none).
has_properties(sangyodphattalung,nonGlutinous,330,sensitivity,none).
has_properties(redroserice,nonGlutinous,750,nonSensitivity,none).
has_properties(khao_yipundoa1,japanese,718,none,none).
has_properties(khao_yipundoa2,japanese,707,none,none).
has_properties(samerng1,barley,270,none,riceTypeBarley).
has_properties(samerng2,barley,300,none,riceTypeBarley).
has_properties(cp304,mixed,938,none,none).
has_properties(rdh1,mixed,1006,none,none).
has_properties(rdp3,nonGlutinous,1415,none,none).
has_properties(samerng1,wheat,330,none,riceTypeWheat).
has_properties(samerng2,wheat,450,none,riceTypeWheat).
has_properties(phrae60,wheat,285,none,none).
has_properties(fahng60,wheat,280,none,none).
