:- module(rice_vulnerable_to_insect, []).
% vulnerable_to(riceName,insect).
vulnerable_to(rd5,brownPlantHopper).
vulnerable_to(rd13,none).
vulnerable_to(rd15,riceGallMidge).
vulnerable_to(rd15,brownPlantHopper).
vulnerable_to(rd15,stemBorer).
vulnerable_to(rd27,brownPlantHopper).
vulnerable_to(rd35,none).
vulnerable_to(rd51,brownPlantHopper).
vulnerable_to(rd59,none).
vulnerable_to(gowruang88,brownPlantHopper).
vulnerable_to(gowruang88,riceGallMidge).
vulnerable_to(jasmine105,brownPlantHopper).
vulnerable_to(jasmine105,greenRiceLeafHopper).
vulnerable_to(jasmine105,stemBorer).
vulnerable_to(khaotahhaeng17,brownPlantHopper).
vulnerable_to(khaotahhaeng17,greenRiceLeafHopper).
vulnerable_to(khaotahhaeng17,stemBorer).
vulnerable_to(khaopahkmaw148,brownPlantHopper).
vulnerable_to(khaojowhawmphitsanulok1,brownPlantHopper).
vulnerable_to(khaojowhawmphitsanulok1,greenRiceLeafHopper).
vulnerable_to(chiangphatthalung,none).
vulnerable_to(chumpae60,none).
vulnerable_to(queen132,brownPlantHopper).
vulnerable_to(queen132,stemBorer).
vulnerable_to(ms_mons_4,brownPlantHopper).
vulnerable_to(saguiwater19,riceGallMidge).
vulnerable_to(watertaro43,none).
vulnerable_to(pathumthani60,brownPlantHopper).
vulnerable_to(pathumthani60,stemBorer).
vulnerable_to(puangrai2,brownPlantHopper).
vulnerable_to(puangrai2,riceGallMidge).
vulnerable_to(phattaling60,none).
vulnerable_to(phitsanulok3,riceGallMidge).
vulnerable_to(phitsanulok3,brownPlantHopper).
vulnerable_to(phitsanulok60_1,none).
vulnerable_to(phitsanulok80,brownPlantHopper).
vulnerable_to(lookdaengpattani,brownPlantHopper).
vulnerable_to(lookdaengpattani,riceGallMidge).
vulnerable_to(lebnokpattani,none).
vulnerable_to(ptnc09002_59,none).
vulnerable_to(leuangyai148,brownPlantHopper).
vulnerable_to(leuangyai148,riceGallMidge).
vulnerable_to(khemtawngphatthalung,none).
vulnerable_to(khaoluangsan_pah_twang,riceGallMidge).
vulnerable_to(gaenjan,brownPlantHopper).
vulnerable_to(pttc02019_1,brownPlantHopper).
vulnerable_to(khaogawdiaw35,brownPlantHopper).
vulnerable_to(cholung97,brownPlantHopper).
vulnerable_to(khaimodrin3,none).
vulnerable_to(rd6,brownPlantHopper).
vulnerable_to(rd6,riceGallMidge).
vulnerable_to(rd8,brownPlantHopper).
vulnerable_to(rd8,riceGallMidge).
vulnerable_to(nongkai80,brownPlantHopper).
vulnerable_to(rd16,riceGallMidge).
vulnerable_to(rd16,brownPlantHopper).
vulnerable_to(rd16,whiteBackedPlantHopper).
vulnerable_to(rd18,none).
vulnerable_to(rd20,none).
vulnerable_to(gampai15,riceGallMidge).
vulnerable_to(gampai15,brownPlantHopper).
vulnerable_to(hahngyu71,brownPlantHopper).
vulnerable_to(hahngyu71,riceGallMidge).
vulnerable_to(mueynawng62m,brownPlantHopper).
vulnerable_to(niawdammor37,none).
vulnerable_to(niawkiawngoo8974,whiteBackedPlantHopper).
vulnerable_to(niawsan_pah_tawng,brownPlantHopper).
vulnerable_to(niawsan_pah_tawng,riceGallMidge).
vulnerable_to(niawubon1,none).
vulnerable_to(niawubon2,brownPlantHopper).
vulnerable_to(leuangpratew123,brownPlantHopper).
vulnerable_to(leuangpratew123,greenRiceLeafHopper).
vulnerable_to(leuangpratew123,stemBorer).
vulnerable_to(ptnc96004_49,none).
vulnerable_to(rd1,brownPlantHopper).
vulnerable_to(rd1,greenRiceLeafHopper).
vulnerable_to(rd1,stemBorer).
vulnerable_to(rd1,riceGallMidge).
vulnerable_to(rd3,brownPlantHopper).
vulnerable_to(rd3,greenRiceLeafHopper).
vulnerable_to(rd3,stemBorer).
vulnerable_to(rd3,riceGallMidge).
vulnerable_to(rd7,brownPlantHopper).
vulnerable_to(rd7,greenRiceLeafHopper).
vulnerable_to(rd7,riceGallMidge).
vulnerable_to(rd9,brownPlantHopper).
vulnerable_to(rd9,greenRiceLeafHopper).
vulnerable_to(rd9,riceGallMidge).
vulnerable_to(rd11,brownPlantHopper).
vulnerable_to(rd11,greenRiceLeafHopper).
vulnerable_to(rd11,stemBorer).
vulnerable_to(rd11,riceGallMidge).
vulnerable_to(rd21,stemBorer).
vulnerable_to(rd23,none).
vulnerable_to(rd25,none).
vulnerable_to(rd29,none).
vulnerable_to(rd31,none).
vulnerable_to(rd33,brownPlantHopper).
vulnerable_to(rd37,brownPlantHopper).
vulnerable_to(rd39,riceGallMidge).
vulnerable_to(rd39,whiteBackedPlantHopper).
vulnerable_to(rd39,brownPlantHopper).
vulnerable_to(rd41,brownPlantHopper).
vulnerable_to(rd43,none).
vulnerable_to(rd47,brownPlantHopper).
vulnerable_to(rd49,none).
vulnerable_to(rd53,none).
vulnerable_to(rd55,brownPlantHopper).
vulnerable_to(rd57,none).
vulnerable_to(rd61,none).
vulnerable_to(rd63,none).
vulnerable_to(khaojowhawmkhlongluang1,brownPlantHopper).
vulnerable_to(khaojowhawmkhlongluang1,greenRiceLeafHopper).
vulnerable_to(khaojowhawmsuphanburi,brownPlantHopper).
vulnerable_to(chainat1,none).
vulnerable_to(chainat2,riceGallMidge).
vulnerable_to(pathumthani1,greenRiceLeafHopper).
vulnerable_to(bangtaen,brownPlantHopper).
vulnerable_to(patthalung,brownPlantHopper).
vulnerable_to(phitsanulok2,riceGallMidge).
vulnerable_to(phitsanulok60_2,none).
vulnerable_to(suphanburi1,none).
vulnerable_to(suphanburi2,none).
vulnerable_to(suphanburi3,none).
vulnerable_to(suphanburi60,none).
vulnerable_to(suphanburi90,none).
vulnerable_to(surin1,brownPlantHopper).
vulnerable_to(rd2,brownPlantHopper).
vulnerable_to(rd2,riceGallMidge).
vulnerable_to(rd4,none).
vulnerable_to(rd10,none).
vulnerable_to(rd14,riceGallMidge).
vulnerable_to(rd14,brownPlantHopper).
vulnerable_to(rd14,whiteBackedPlantHopper).
vulnerable_to(rd_maejo2,none).
vulnerable_to(phrae1,whiteBackedPlantHopper).
vulnerable_to(phrae1,riceGallMidge).
vulnerable_to(sakonnakhon,brownPlantHopper).
vulnerable_to(san_pah_tawng1,riceGallMidge).
vulnerable_to(tapowgaew161,brownPlantHopper).
vulnerable_to(tapowgaew161,riceGallMidge).
vulnerable_to(nahngcha_lawng,brownPlantHopper).
vulnerable_to(nahngcha_lawng,riceGallMidge).
vulnerable_to(pingaew56,brownPlantHopper).
vulnerable_to(pingaew56,greenRiceLeafHopper).
vulnerable_to(pingaew56,stemBorer).
vulnerable_to(pingaew56,riceGallMidge).
vulnerable_to(plaingahmprachinburi,brownPlantHopper).
vulnerable_to(plaingahmprachinburi,greenRiceLeafHopper).
vulnerable_to(lebmeunahng111,brownPlantHopper).
vulnerable_to(lebmeunahng111,riceGallMidge).
vulnerable_to(khaobahnnah432,brownPlantHopper).
vulnerable_to(rd19,brownPlantHopper).
vulnerable_to(rd45,brownPlantHopper).
vulnerable_to(hantra60,brownPlantHopper).
vulnerable_to(hantra60,greenRiceLeafHopper).
vulnerable_to(hantra60,riceGallMidge).
vulnerable_to(prachinburi1,greenRiceLeafHopper).
vulnerable_to(prachinburi1,brownPlantHopper).
vulnerable_to(prachinburi2,greenRiceLeafHopper).
vulnerable_to(prachinburi2,brownPlantHopper).
vulnerable_to(prachinburi2,none).
vulnerable_to(ayutthaya1,none).
vulnerable_to(ayutthaya1,brownPlantHopper).
vulnerable_to(rd17,none).
vulnerable_to(goomeuangluang,brownPlantHopper).
vulnerable_to(goomeuangluang,riceGallMidge).
vulnerable_to(khaopongkrai,riceGallMidge).
vulnerable_to(khaopongkrai,brownPlantHopper).
vulnerable_to(jowhaw,riceGallMidge).
vulnerable_to(sewmaejan,none).
vulnerable_to(dawkpa_yawm,brownPlantHopper).
vulnerable_to(namroo,whiteBackedPlantHopper).
vulnerable_to(jowlisawsan_pah_tawng,whiteBackedPlantHopper).
vulnerable_to(jowkhaochiangmai,brownPlantHopper).
vulnerable_to(jowkhaochiangmai,whiteBackedPlantHopper).
vulnerable_to(leumpua,brownPlantHopper).
vulnerable_to(leumpua,riceGallMidge).
vulnerable_to(redhawnrice,none).
vulnerable_to(sangyodphattalung,none).
vulnerable_to(redroserice,brownPlantHopper).
vulnerable_to(khao_yipundoa1,brownPlantHopper).
vulnerable_to(khao_yipundoa1,greenRiceLeafHopper).
vulnerable_to(khao_yipundoa1,whiteBackedPlantHopper).
vulnerable_to(khao_yipundoa2,brownPlantHopper).
vulnerable_to(khao_yipundoa2,greenRiceLeafHopper).
vulnerable_to(khao_yipundoa2,whiteBackedPlantHopper).
vulnerable_to(samerng1,none).
vulnerable_to(samerng2,none).
vulnerable_to(cp304,brownPlantHopper).
vulnerable_to(rdh1,brownPlantHopper).
vulnerable_to(rdp3,brownPlantHopper).
vulnerable_to(samerng1,none).
vulnerable_to(samerng2,none).
vulnerable_to(phrae60,none).
vulnerable_to(fahng60,none).
