:- module(rice_ecosystem, []).
# suitable_with(riceName,ecosystem).
suitable_with(rd5,lowland).
suitable_with(rd13,lowland).
suitable_with(rd15,lowland).
suitable_with(rd27,lowland).
suitable_with(rd35,lowland).
suitable_with(rd51,lowland).
suitable_with(rd59,lowland).
suitable_with(gowruang88,lowland).
suitable_with(jasmine105,lowland).
suitable_with(khaotahhaeng17,lowland).
suitable_with(khaopahkmaw148,lowland).
suitable_with(khaojowhawmphitsanulok1,lowland).
suitable_with(chiangphatthalung,lowland).
suitable_with(chumpae60,lowland).
suitable_with(queen132,lowland).
suitable_with(ms_mons_4,lowland).
suitable_with(saguiwater19,lowland).
suitable_with(watertaro43,lowland).
suitable_with(pathumthani60,lowland).
suitable_with(puangrai2,lowland).
suitable_with(phattaling60,lowland).
suitable_with(phitsanulok3,lowland).
suitable_with(phitsanulok60_1,lowland).
suitable_with(phitsanulok80,lowland).
suitable_with(lookdaengpattani,lowland).
suitable_with(lebnokpattani,lowland).
suitable_with(ptnc09002_59,lowland).
suitable_with(leuangyai148,lowland).
suitable_with(khemtawngphatthalung,lowland).
suitable_with(khaoluangsan_pah_twang,lowland).
suitable_with(gaenjan,lowland).
suitable_with(pttc02019_1,lowland).
suitable_with(khaogawdiaw35,lowland).
suitable_with(cholung97,lowland).
suitable_with(khaimodrin3,lowland).
suitable_with(rd6,lowland).
suitable_with(rd8,lowland).
suitable_with(nongkai80,lowland).
suitable_with(rd16,lowland).
suitable_with(rd18,lowland).
suitable_with(rd20,lowland).
suitable_with(gampai15,lowland).
suitable_with(hahngyu71,lowland).
suitable_with(mueynawng62m,lowland).
suitable_with(niawdammor37,lowland).
suitable_with(niawkiawngoo8974,lowland).
suitable_with(niawsan_pah_tawng,lowland).
suitable_with(niawubon1,lowland).
suitable_with(niawubon2,lowland).
suitable_with(leuangpratew123,lowland).
suitable_with(ptnc96004_49,lowland).
suitable_with(rd1,lowland).
suitable_with(rd3,lowland).
suitable_with(rd7,lowland).
suitable_with(rd9,lowland).
suitable_with(rd11,lowland).
suitable_with(rd21,lowland).
suitable_with(rd23,lowland).
suitable_with(rd25,lowland).
suitable_with(rd29,lowland).
suitable_with(rd31,lowland).
suitable_with(rd33,lowland).
suitable_with(rd37,lowland).
suitable_with(rd39,lowland).
suitable_with(rd41,lowland).
suitable_with(rd43,lowland).
suitable_with(rd47,lowland).
suitable_with(rd49,lowland).
suitable_with(rd53,lowland).
suitable_with(rd55,lowland).
suitable_with(rd57,lowland).
suitable_with(rd61,lowland).
suitable_with(rd63,lowland).
suitable_with(khaojowhawmkhlongluang1,lowland).
suitable_with(khaojowhawmsuphanburi,lowland).
suitable_with(chainat1,lowland).
suitable_with(chainat2,lowland).
suitable_with(pathumthani1,lowland).
suitable_with(bangtaen,lowland).
suitable_with(patthalung,lowland).
suitable_with(phitsanulok2,lowland).
suitable_with(phitsanulok60_2,lowland).
suitable_with(suphanburi1,lowland).
suitable_with(suphanburi2,lowland).
suitable_with(suphanburi3,lowland).
suitable_with(suphanburi60,lowland).
suitable_with(suphanburi90,lowland).
suitable_with(surin1,lowland).
suitable_with(rd2,lowland).
suitable_with(rd4,lowland).
suitable_with(rd10,lowland).
suitable_with(rd14,lowland).
suitable_with(rd_maejo2,lowland).
suitable_with(phrae1,lowland).
suitable_with(sakonnakhon,lowland).
suitable_with(san_pah_tawng1,lowland).
suitable_with(tapowgaew161,floating).
suitable_with(nahngcha_lawng,floating).
suitable_with(pingaew56,floating).
suitable_with(plaingahmprachinburi,floating).
suitable_with(lebmeunahng111,floating).
suitable_with(khaobahnnah432,floating).
suitable_with(rd19,deepWaterFlooding).
suitable_with(rd45,deepWaterFlooding).
suitable_with(hantra60,deepWaterFlooding).
suitable_with(prachinburi1,deepWaterFlooding).
suitable_with(prachinburi2,deepWaterFlooding).
suitable_with(ayutthaya1,deepWaterFlooding).
suitable_with(rd17,deepWaterFlooding).
suitable_with(goomeuangluang,upland).
suitable_with(khaopongkrai,upland).
suitable_with(jowhaw,upland).
suitable_with(sewmaejan,upland).
suitable_with(dawkpa_yawm,upland).
suitable_with(namroo,upland).
suitable_with(jowlisawsan_pah_tawng,upland).
suitable_with(jowkhaochiangmai,upland).
suitable_with(leumpua,upland).
suitable_with(redhawnrice,none).
suitable_with(sangyodphattalung,none).
suitable_with(redroserice,none).
suitable_with(khao_yipundoa1,none).
suitable_with(khao_yipundoa2,none).
suitable_with(samerng1,none).
suitable_with(samerng2,none).
suitable_with(cp304,none).
suitable_with(rdh1,none).
suitable_with(rdp3,none).
suitable_with(phrae60,none).
suitable_with(fahng60,none).