:- module(rice_vulnerable_to_disease, []).
% vulnerable_to(riceName,disease).
vulnerable_to(rd5,riceRaggedStunt).
vulnerable_to(rd5,brownSpot).
vulnerable_to(rd13,bacterialLeafBlight).
vulnerable_to(rd15,bacterialLeafBlight).
vulnerable_to(rd15,riceBlast).
vulnerable_to(rd27,bacterialLeafBlight).
vulnerable_to(rd27,riceTungro).
vulnerable_to(rd35,none).
vulnerable_to(rd51,none).
vulnerable_to(rd59,none).
vulnerable_to(gowruang88,riceBlast).
vulnerable_to(gowruang88,riceTungro).
vulnerable_to(jasmine105,riceBlast).
vulnerable_to(jasmine105,riceTungro).
vulnerable_to(jasmine105,bacterialLeafBlight).
vulnerable_to(jasmine105,riceRaggedStunt).
vulnerable_to(khaotahhaeng17,riceBlast).
vulnerable_to(khaotahhaeng17,riceTungro).
vulnerable_to(khaotahhaeng17,bacterialLeafBlight).
vulnerable_to(khaotahhaeng17,riceRaggedStunt).
vulnerable_to(khaopahkmaw148,riceTungro).
vulnerable_to(khaopahkmaw148,bacterialLeafBlight).
vulnerable_to(khaopahkmaw148,riceRaggedStunt).
vulnerable_to(khaojowhawmphitsanulok1,riceTungro).
vulnerable_to(chiangphatthalung,riceBlast).
vulnerable_to(chumpae60,riceBlast).
vulnerable_to(chumpae60,bacterialLeafBlight).
vulnerable_to(queen132,riceBlast).
vulnerable_to(queen132,riceRaggedStunt).
vulnerable_to(ms_mons_4,riceBlast).
vulnerable_to(ms_mons_4,riceTungro).
vulnerable_to(ms_mons_4,bacterialLeafBlight).
vulnerable_to(saguiwater19,riceBlast).
vulnerable_to(saguiwater19,brownSpot).
vulnerable_to(saguiwater19,bacterialLeafBlight).
vulnerable_to(saguiwater19,riceTungro).
vulnerable_to(watertaro43,none).
vulnerable_to(pathumthani60,riceBlast).
vulnerable_to(pathumthani60,riceTungro).
vulnerable_to(pathumthani60,bacterialLeafBlight).
vulnerable_to(puangrai2,none).
vulnerable_to(phattaling60,none).
vulnerable_to(phitsanulok3,bacterialLeafBlight).
vulnerable_to(phitsanulok60_1,riceBlast).
vulnerable_to(phitsanulok60_1,riceTungro).
vulnerable_to(phitsanulok80,riceBlast).
vulnerable_to(phitsanulok80,bacterialLeafBlight).
vulnerable_to(lookdaengpattani,bacterialLeafBlight).
vulnerable_to(lebnokpattani,riceBlast).
vulnerable_to(ptnc09002_59,none).
vulnerable_to(leuangyai148,riceBlast).
vulnerable_to(leuangyai148,riceTungro).
vulnerable_to(khemtawngphatthalung,riceBlast).
vulnerable_to(khaoluangsan_pah_twang,none).
vulnerable_to(gaenjan,none).
vulnerable_to(pttc02019_1,riceBlast).
vulnerable_to(pttc02019_1,bacterialLeafBlight).
vulnerable_to(khaogawdiaw35,riceBlast).
vulnerable_to(khaogawdiaw35,bacterialLeafBlight).
vulnerable_to(cholung97,riceBlast).
vulnerable_to(khaimodrin3,riceBlast).
vulnerable_to(rd6,bacterialLeafBlight).
vulnerable_to(rd6,riceBlast).
vulnerable_to(rd8,bacterialLeafBlight).
vulnerable_to(nongkai80,bacterialLeafBlight).
vulnerable_to(rd16,bacterialLeafBlight).
vulnerable_to(rd18,none).
vulnerable_to(rd20,none).
vulnerable_to(gampai15,bacterialLeafBlight).
vulnerable_to(hahngyu71,bacterialLeafBlight).
vulnerable_to(hahngyu71,riceTungro).
vulnerable_to(mueynawng62m,riceBlast).
vulnerable_to(mueynawng62m,bacterialLeafBlight).
vulnerable_to(niawdammor37,none).
vulnerable_to(niawkiawngoo8974,none).
vulnerable_to(niawsan_pah_tawng,bacterialLeafBlight).
vulnerable_to(niawsan_pah_tawng,riceTungro).
vulnerable_to(niawubon1,riceBlast).
vulnerable_to(niawubon2,bacterialLeafBlight).
vulnerable_to(leuangpratew123,riceBlastriceTungro).
vulnerable_to(leuangpratew123,grassyStunt).
vulnerable_to(ptnc96004_49,riceBlast).
vulnerable_to(ptnc96004_49,bacterialLeafBlight).
vulnerable_to(rd1,bacterialLeafBlight).
vulnerable_to(rd1,riceRaggedStunt).
vulnerable_to(rd1,narrowBrownSpot).
vulnerable_to(rd1,riceBlast).
vulnerable_to(rd3,bacterialLeafBlight).
vulnerable_to(rd3,riceRaggedStunt).
vulnerable_to(rd3,narrowBrownSpot).
vulnerable_to(rd3,riceBlast).
vulnerable_to(rd7,riceRaggedStunt).
vulnerable_to(rd7,riceBlast).
vulnerable_to(rd9,bacterialLeafBlight).
vulnerable_to(rd9,dirtyPanicle).
vulnerable_to(rd9,riceBlast).
vulnerable_to(rd11,bacterialLeafBlight).
vulnerable_to(rd11,riceRaggedStunt).
vulnerable_to(rd11,narrowBrownSpot).
vulnerable_to(rd11,riceTungro).
vulnerable_to(rd11,bacterialLeafStreak).
vulnerable_to(rd21,riceTungro).
vulnerable_to(rd21,sheathBlight).
vulnerable_to(rd21,riceBlast).
vulnerable_to(rd23,riceTungro).
vulnerable_to(rd23,riceBlast).
vulnerable_to(rd25,riceTungro).
vulnerable_to(rd25,riceBlast).
vulnerable_to(rd29,none).
vulnerable_to(rd31,riceBlast).
vulnerable_to(rd31,riceRaggedStunt).
vulnerable_to(rd31,riceTungro).
vulnerable_to(rd33,bacterialLeafBlight).
vulnerable_to(rd37,none).
vulnerable_to(rd39,none).
vulnerable_to(rd41,bacterialLeafBlight).
vulnerable_to(rd43,none).
vulnerable_to(rd47,bacterialLeafBlight).
vulnerable_to(rd49,none).
vulnerable_to(rd53,none).
vulnerable_to(rd55,none).
vulnerable_to(rd57,none).
vulnerable_to(rd61,none).
vulnerable_to(rd63,none).
vulnerable_to(khaojowhawmkhlongluang1,none).
vulnerable_to(khaojowhawmsuphanburi,riceBlast).
vulnerable_to(chainat1,riceTungro).
vulnerable_to(chainat1,bacterialLeafBlight).
vulnerable_to(chainat1,bacterialLeafStreak).
vulnerable_to(chainat2,riceTungro).
vulnerable_to(chainat2,bacterialLeafBlight).
vulnerable_to(chainat2,riceBlast).
vulnerable_to(pathumthani1,riceRaggedStunt).
vulnerable_to(pathumthani1,riceTungro).
vulnerable_to(bangtaen,sheathBlight).
vulnerable_to(bangtaen,riceBlast).
vulnerable_to(patthalung,none).
vulnerable_to(phitsanulok2,riceBlast).
vulnerable_to(phitsanulok2,riceRaggedStunt).
vulnerable_to(phitsanulok60_2,sheathBlight).
vulnerable_to(suphanburi1,dirtyPanicle).
vulnerable_to(suphanburi1,narrowBrownSpot).
vulnerable_to(suphanburi2,narrowBrownSpot).
vulnerable_to(suphanburi2,sheathRot).
vulnerable_to(suphanburi3,riceTungro).
vulnerable_to(suphanburi3,brownSpot).
vulnerable_to(suphanburi60,brownSpot).
vulnerable_to(suphanburi60,sheathBlight).
vulnerable_to(suphanburi90,narrowBrownSpot).
vulnerable_to(surin1,none).
vulnerable_to(rd2,bacterialLeafBlight).
vulnerable_to(rd2,riceBlast).
vulnerable_to(rd4,riceBlast).
vulnerable_to(rd4,bacterialLeafBlight).
vulnerable_to(rd10,none).
vulnerable_to(rd14,none).
vulnerable_to(rd_maejo2,none).
vulnerable_to(phrae1,none).
vulnerable_to(sakonnakhon,riceBlast).
vulnerable_to(sakonnakhon,bacterialLeafBlight).
vulnerable_to(san_pah_tawng1,riceTungro).
vulnerable_to(tapowgaew161,bacterialLeafBlight).
vulnerable_to(tapowgaew161,riceBlast).
vulnerable_to(tapowgaew161,riceTungro).
vulnerable_to(tapowgaew161,riceRaggedStunt).
vulnerable_to(nahngcha_lawng,bacterialLeafBlight).
vulnerable_to(nahngcha_lawng,riceTungro).
vulnerable_to(pingaew56,bacterialLeafBlight).
vulnerable_to(pingaew56,riceBlast).
vulnerable_to(pingaew56,riceTungro).
vulnerable_to(pingaew56,sheathRot).
vulnerable_to(pingaew56,riceRaggedStunt).
vulnerable_to(plaingahmprachinburi,riceRaggedStunt).
vulnerable_to(plaingahmprachinburi,riceTungro).
vulnerable_to(lebmeunahng111,riceBlast).
vulnerable_to(lebmeunahng111,bacterialLeafBlight).
vulnerable_to(lebmeunahng111,riceTungro).
vulnerable_to(khaobahnnah432,bacterialLeafBlight).
vulnerable_to(rd19,none).
vulnerable_to(rd45,riceBlast).
vulnerable_to(hantra60,riceTungro).
vulnerable_to(hantra60,bacterialLeafBlight).
vulnerable_to(prachinburi1,riceTungro).
vulnerable_to(prachinburi2,riceTungro).
vulnerable_to(prachinburi2,none).
vulnerable_to(ayutthaya1,none).
vulnerable_to(rd17,bacterialLeafBlight).
vulnerable_to(rd17,leafScald).
vulnerable_to(goomeuangluang,riceTungro).
vulnerable_to(goomeuangluang,riceRaggedStunt).
vulnerable_to(goomeuangluang,grassyStunt).
vulnerable_to(goomeuangluang,gallDwarf).
vulnerable_to(khaopongkrai,bacterialLeafBlight).
vulnerable_to(khaopongkrai,riceTungro).
vulnerable_to(khaopongkrai,riceRaggedStunt).
vulnerable_to(khaopongkrai,grassyStunt).
vulnerable_to(jowhaw,none).
vulnerable_to(sewmaejan,bacterialLeafBlightleafScald).
vulnerable_to(dawkpa_yawm,bacterialLeafBlight).
vulnerable_to(dawkpa_yawm,riceTungro).
vulnerable_to(dawkpa_yawm,riceRaggedStunt).
vulnerable_to(dawkpa_yawm,grassyStunt).
vulnerable_to(dawkpa_yawm,gallDwarf).
vulnerable_to(namroo,none).
vulnerable_to(jowlisawsan_pah_tawng,none).
vulnerable_to(jowkhaochiangmai,riceBlast).
vulnerable_to(jowkhaochiangmai,bacterialLeafBlight).
vulnerable_to(leumpua,bacterialLeafBlight).
vulnerable_to(leumpua,riceTungro).
vulnerable_to(leumpua,riceRaggedStunt).
vulnerable_to(leumpua,grassyStunt).
vulnerable_to(leumpua,gallDwarf).
vulnerable_to(redhawnrice,riceTungro).
vulnerable_to(redhawnrice,bacterialLeafBlight).
vulnerable_to(redhawnrice,bacterialLeafStreak).
vulnerable_to(sangyodphattalung,riceBlast).
vulnerable_to(redroserice,riceBlast).
vulnerable_to(redroserice,bacterialLeafBlight).
vulnerable_to(khao_yipundoa1,riceBlast).
vulnerable_to(khao_yipundoa1,bacterialLeafBlight).
vulnerable_to(khao_yipundoa1,riceTungro).
vulnerable_to(khao_yipundoa2,riceBlast).
vulnerable_to(khao_yipundoa2,bacterialLeafBlight).
vulnerable_to(khao_yipundoa2,riceTungro).
vulnerable_to(samerng1,brownSpot).
vulnerable_to(samerng1,riceBlast).
vulnerable_to(samerng2,brownSpot).
vulnerable_to(samerng2,riceBlast).
vulnerable_to(cp304,bacterialLeafBlight).
vulnerable_to(cp304,riceRaggedStunt).
vulnerable_to(cp304,narrowBrownSpot).
vulnerable_to(cp304,riceTungro).
vulnerable_to(cp304,riceBlast).
vulnerable_to(rdh1,bacterialLeafBlight).
vulnerable_to(rdh1,riceBlast).
vulnerable_to(rdp3,bacterialLeafBlight).
vulnerable_to(samerng1,none).
vulnerable_to(samerng2,none).
vulnerable_to(phrae60,none).
vulnerable_to(fahng60,none).
