:- module(rice_class, []).
% is_instance_of(riceName, rice).
is_instance_of(rd5,rice).
is_instance_of(rd13,rice).
is_instance_of(rd15,rice).
is_instance_of(rd27,rice).
is_instance_of(rd35,rice).
is_instance_of(rd51,rice).
is_instance_of(rd59,rice).
is_instance_of(gowruang88,rice).
is_instance_of(jasmine105,rice).
is_instance_of(khaotahhaeng17,rice).
is_instance_of(khaopahkmaw148,rice).
is_instance_of(khaojowhawmphitsanulok1,rice).
is_instance_of(chiangphatthalung,rice).
is_instance_of(chumpae60,rice).
is_instance_of(queen132,rice).
is_instance_of(ms_mons_4,rice).
is_instance_of(saguiwater19,rice).
is_instance_of(watertaro43,rice).
is_instance_of(pathumthani60,rice).
is_instance_of(puangrai2,rice).
is_instance_of(phattaling60,rice).
is_instance_of(phitsanulok3,rice).
is_instance_of(phitsanulok60_1,rice).
is_instance_of(phitsanulok80,rice).
is_instance_of(lookdaengpattani,rice).
is_instance_of(lebnokpattani,rice).
is_instance_of(ptnc09002_59,rice).
is_instance_of(leuangyai148,rice).
is_instance_of(khemtawngphatthalung,rice).
is_instance_of(khaoluangsan_pah_twang,rice).
is_instance_of(gaenjan,rice).
is_instance_of(pttc02019_1,rice).
is_instance_of(khaogawdiaw35,rice).
is_instance_of(cholung97,rice).
is_instance_of(khaimodrin3,rice).
is_instance_of(rd6,rice).
is_instance_of(rd8,rice).
is_instance_of(nongkai80,rice).
is_instance_of(rd16,rice).
is_instance_of(rd18,rice).
is_instance_of(rd20,rice).
is_instance_of(gampai15,rice).
is_instance_of(hahngyu71,rice).
is_instance_of(mueynawng62m,rice).
is_instance_of(niawdammor37,rice).
is_instance_of(niawkiawngoo8974,rice).
is_instance_of(niawsan_pah_tawng,rice).
is_instance_of(niawubon1,rice).
is_instance_of(niawubon2,rice).
is_instance_of(leuangpratew123,rice).
is_instance_of(ptnc96004_49,rice).
is_instance_of(rd1,rice).
is_instance_of(rd3,rice).
is_instance_of(rd7,rice).
is_instance_of(rd9,rice).
is_instance_of(rd11,rice).
is_instance_of(rd21,rice).
is_instance_of(rd23,rice).
is_instance_of(rd25,rice).
is_instance_of(rd29,rice).
is_instance_of(rd31,rice).
is_instance_of(rd33,rice).
is_instance_of(rd37,rice).
is_instance_of(rd39,rice).
is_instance_of(rd41,rice).
is_instance_of(rd43,rice).
is_instance_of(rd47,rice).
is_instance_of(rd49,rice).
is_instance_of(rd53,rice).
is_instance_of(rd55,rice).
is_instance_of(rd57,rice).
is_instance_of(rd61,rice).
is_instance_of(rd63,rice).
is_instance_of(khaojowhawmkhlongluang1,rice).
is_instance_of(khaojowhawmsuphanburi,rice).
is_instance_of(chainat1,rice).
is_instance_of(chainat2,rice).
is_instance_of(pathumthani1,rice).
is_instance_of(bangtaen,rice).
is_instance_of(patthalung,rice).
is_instance_of(phitsanulok2,rice).
is_instance_of(phitsanulok60_2,rice).
is_instance_of(suphanburi1,rice).
is_instance_of(suphanburi2,rice).
is_instance_of(suphanburi3,rice).
is_instance_of(suphanburi60,rice).
is_instance_of(suphanburi90,rice).
is_instance_of(surin1,rice).
is_instance_of(rd2,rice).
is_instance_of(rd4,rice).
is_instance_of(rd10,rice).
is_instance_of(rd14,rice).
is_instance_of(rd_maejo2,rice).
is_instance_of(phrae1,rice).
is_instance_of(sakonnakhon,rice).
is_instance_of(san_pah_tawng1,rice).
is_instance_of(tapowgaew161,rice).
is_instance_of(nahngcha_lawng,rice).
is_instance_of(pingaew56,rice).
is_instance_of(plaingahmprachinburi,rice).
is_instance_of(lebmeunahng111,rice).
is_instance_of(khaobahnnah432,rice).
is_instance_of(rd19,rice).
is_instance_of(rd45,rice).
is_instance_of(hantra60,rice).
is_instance_of(prachinburi1,rice).
is_instance_of(prachinburi2,rice).
is_instance_of(ayutthaya1,rice).
is_instance_of(rd17,rice).
is_instance_of(goomeuangluang,rice).
is_instance_of(khaopongkrai,rice).
is_instance_of(jowhaw,rice).
is_instance_of(sewmaejan,rice).
is_instance_of(dawkpa_yawm,rice).
is_instance_of(namroo,rice).
is_instance_of(jowlisawsan_pah_tawng,rice).
is_instance_of(jowkhaochiangmai,rice).
is_instance_of(leumpua,rice).
is_instance_of(redhawnrice,rice).
is_instance_of(sangyodphattalung,rice).
is_instance_of(redroserice,rice).
is_instance_of(khao_yipundoa1,rice).
is_instance_of(khao_yipundoa2,rice).
is_instance_of(samerng1,rice).
is_instance_of(samerng2,rice).
is_instance_of(cp304,rice).
is_instance_of(rdh1,rice).
is_instance_of(rdp3,rice).
is_instance_of(phrae60,rice).
is_instance_of(fahng60,rice).