:- module(soilgroup_class, []).
# is_instance_of(soilGroupName,soilGroup).
is_instance_of(krabi,soilGroup).
is_instance_of(kantang,soilGroup).
is_instance_of(kabDaeng,soilGroup).
is_instance_of(khambong,soilGroup).
is_instance_of(kamphaengSaen,soilGroup).
is_instance_of(kulaRonghai,soilGroup).
is_instance_of(koYai,soilGroup).
is_instance_of(klaeng,soilGroup).
is_instance_of(khaoKhat,soilGroup).
is_instance_of(khaoYoi,soilGroup).
is_instance_of(khlongKhut,soilGroup).
is_instance_of(khlongChak,soilGroup).
is_instance_of(khlongTeng,soilGroup).
is_instance_of(khlongThom,soilGroup).
is_instance_of(khlongNokKrathung,soilGroup).
is_instance_of(khuanKaLong,soilGroup).
is_instance_of(khoHong,soilGroup).
is_instance_of(khokKrathiam,soilGroup).
is_instance_of(khokKloi,soilGroup).
is_instance_of(khokKhain,soilGroup).
is_instance_of(korat,soilGroup).
is_instance_of(chatturat,soilGroup).
is_instance_of(chakkarat,soilGroup).
is_instance_of(chanTuk,soilGroup).
is_instance_of(chalong,soilGroup).
is_instance_of(chachoengsao,soilGroup).
is_instance_of(chonBuri,soilGroup).
is_instance_of(chongKae,soilGroup).
is_instance_of(chaAm,soilGroup).
is_instance_of(chaiBadan,soilGroup).
is_instance_of(chumphon,soilGroup).
is_instance_of(chumphonBuri,soilGroup).
is_instance_of(chumPhuang,soilGroup).
is_instance_of(chumsaeng,soilGroup).
is_instance_of(chiangKhong,soilGroup).
is_instance_of(chiangKhan,soilGroup).
is_instance_of(chiangRai,soilGroup).
is_instance_of(chiangSaen,soilGroup).
is_instance_of(chiangMai,soilGroup).
is_instance_of(chianYai,soilGroup).
is_instance_of(chokChai,soilGroup).
is_instance_of(dongTakhian,soilGroup).
is_instance_of(dongYangEn,soilGroup).
is_instance_of(dongLan,soilGroup).
is_instance_of(donChedi,soilGroup).
is_instance_of(donMuang,soilGroup).
is_instance_of(donRai,soilGroup).
is_instance_of(doiPui,soilGroup).
is_instance_of(danKhunThot,soilGroup).
is_instance_of(danSai,soilGroup).
is_instance_of(doemBang,soilGroup).
is_instance_of(thonSai,soilGroup).
is_instance_of(trang,soilGroup).
is_instance_of(trat,soilGroup).
is_instance_of(thakuaThung,soilGroup).
is_instance_of(taphanHin,soilGroup).
is_instance_of(thaKhun,soilGroup).
is_instance_of(takhli,soilGroup).
is_instance_of(saiKhao,soilGroup).
is_instance_of(thaKhwang,soilGroup).
is_instance_of(thaChin,soilGroup).
is_instance_of(thaChang,soilGroup).
is_instance_of(thaSae,soilGroup).
is_instance_of(thaTum,soilGroup).
is_instance_of(thaPhon,soilGroup).
is_instance_of(thaMuang,soilGroup).
is_instance_of(thaiMuang,soilGroup).
is_instance_of(thaYang,soilGroup).
is_instance_of(thaRua,soilGroup).
is_instance_of(thaLi,soilGroup).
is_instance_of(thaSala,soilGroup).
is_instance_of(thaMai,soilGroup).
is_instance_of(thaUthen,soilGroup).
is_instance_of(thungKai,soilGroup).
is_instance_of(thungWa,soilGroup).
is_instance_of(saiNgam,soilGroup).
is_instance_of(thanyaburi,soilGroup).
is_instance_of(thatPhanom,soilGroup).
is_instance_of(nakhonPathom,soilGroup).
is_instance_of(nakhonPhanom,soilGroup).
is_instance_of(nakhonSawan,soilGroup).
is_instance_of(narathiwat,soilGroup).
is_instance_of(naThawi,soilGroup).
is_instance_of(naThon,soilGroup).
is_instance_of(naTham,soilGroup).
is_instance_of(nan,soilGroup).
is_instance_of(namKrachi,soilGroup).
is_instance_of(namChun,soilGroup).
is_instance_of(namDuk,soilGroup).
is_instance_of(namPhong,soilGroup).
is_instance_of(namLen,soilGroup).
is_instance_of(borabu,soilGroup).
is_instance_of(boThai,soilGroup).
is_instance_of(bangkok,soilGroup).
is_instance_of(bangKhen,soilGroup).
is_instance_of(bangNara,soilGroup).
is_instance_of(bangnamPrieo,soilGroup).
is_instance_of(bangPakong,soilGroup).
is_instance_of(bangPhae,soilGroup).
is_instance_of(bangMunNak,soilGroup).
is_instance_of(bangLen,soilGroup).
is_instance_of(bacho,soilGroup).
is_instance_of(banChong,soilGroup).
is_instance_of(banThon,soilGroup).
is_instance_of(banBung,soilGroup).
is_instance_of(banPhai,soilGroup).
is_instance_of(banPhot,soilGroup).
is_instance_of(banMi,soilGroup).
is_instance_of(bungChanang,soilGroup).
is_instance_of(bunthrik,soilGroup).
is_instance_of(buriRam,soilGroup).
is_instance_of(padangBesar,soilGroup).
is_instance_of(pathiu,soilGroup).
is_instance_of(pakChan,soilGroup).
is_instance_of(pakChong,soilGroup).
is_instance_of(pakTho,soilGroup).
is_instance_of(pongThong,soilGroup).
is_instance_of(pongNamRon,soilGroup).
is_instance_of(phakKat,soilGroup).
is_instance_of(fangDaeng,soilGroup).
is_instance_of(phato,soilGroup).
is_instance_of(phayomNgam,soilGroup).
is_instance_of(phayao,soilGroup).
is_instance_of(phawong,soilGroup).
is_instance_of(pga,soilGroup).
is_instance_of(patthaya,soilGroup).
is_instance_of(phatthalung,soilGroup).
is_instance_of(phan,soilGroup).
is_instance_of(phanThong,soilGroup).
is_instance_of(phimai,soilGroup).
is_instance_of(phetchaburi,soilGroup).
is_instance_of(phetchabun,soilGroup).
is_instance_of(phen,soilGroup).
is_instance_of(phonNgam,soilGroup).
is_instance_of(phonPhisai,soilGroup).
is_instance_of(phuket,soilGroup).
is_instance_of(phuSana,soilGroup).
is_instance_of(manorom,soilGroup).
is_instance_of(muakLek,soilGroup).
is_instance_of(mahaPhot,soilGroup).
is_instance_of(mahaSarakham,soilGroup).
is_instance_of(makham,soilGroup).
is_instance_of(munoh,soilGroup).
is_instance_of(maeTaeng,soilGroup).
is_instance_of(maeTha,soilGroup).
is_instance_of(maeRim,soilGroup).
is_instance_of(maeSai,soilGroup).
is_instance_of(maiKhao,soilGroup).
is_instance_of(yasothon,soilGroup).
is_instance_of(yala,soilGroup).
is_instance_of(yangTalat,soilGroup).
is_instance_of(yanTaKao,soilGroup).
is_instance_of(yi_ngo,soilGroup).
is_instance_of(roiEt,soilGroup).
is_instance_of(rangae,soilGroup).
is_instance_of(ranong,soilGroup).
is_instance_of(rayong,soilGroup).
is_instance_of(rangsit,soilGroup).
is_instance_of(ratchaburi,soilGroup).
is_instance_of(ruso,soilGroup).
is_instance_of(renu,soilGroup).
is_instance_of(lopBuri,soilGroup).
is_instance_of(laNgu,soilGroup).
is_instance_of(lahan,soilGroup).
is_instance_of(latYa,soilGroup).
is_instance_of(lamKaen,soilGroup).
is_instance_of(kamNarai,soilGroup).
is_instance_of(lampang,soilGroup).
is_instance_of(lamPhuLa,soilGroup).
is_instance_of(lamSonthi,soilGroup).
is_instance_of(li,soilGroup).
is_instance_of(loei,soilGroup).
is_instance_of(wangChomphu,soilGroup).
is_instance_of(wangTong,soilGroup).
is_instance_of(wangSaphung,soilGroup).
is_instance_of(wangHai,soilGroup).
is_instance_of(watthana,soilGroup).
is_instance_of(wanPriang,soilGroup).
is_instance_of(warin,soilGroup).
is_instance_of(wichianBuri,soilGroup).
is_instance_of(visai,soilGroup).
is_instance_of(siThep,soilGroup).
is_instance_of(siSongKhram,soilGroup).
is_instance_of(sakon,soilGroup).
is_instance_of(songkhla,soilGroup).
is_instance_of(satuk,soilGroup).
is_instance_of(satun,soilGroup).
is_instance_of(sopPrap,soilGroup).
is_instance_of(samoThod,soilGroup).
is_instance_of(samutPrakan,soilGroup).
is_instance_of(sapphaya,soilGroup).
is_instance_of(saraburi,soilGroup).
is_instance_of(sawi,soilGroup).
is_instance_of(sadao,soilGroup).
is_instance_of(saThon,soilGroup).
is_instance_of(sattahip,soilGroup).
is_instance_of(sanSai,soilGroup).
is_instance_of(sanPaTong,soilGroup).
is_instance_of(saiBuri,soilGroup).
is_instance_of(singBuri,soilGroup).
is_instance_of(siKhiu,soilGroup).
is_instance_of(siThon,soilGroup).
is_instance_of(surin,soilGroup).
is_instance_of(sungaiGolok,soilGroup).
is_instance_of(sungaiPadi,soilGroup).
is_instance_of(sungNoen,soilGroup).
is_instance_of(sena,soilGroup).
is_instance_of(nongKae,soilGroup).
is_instance_of(nongKhla,soilGroup).
is_instance_of(nongBon,soilGroup).
is_instance_of(nongMot,soilGroup).
is_instance_of(lomKao,soilGroup).
is_instance_of(lomSak,soilGroup).
is_instance_of(langSuan,soilGroup).
is_instance_of(huaiPong,soilGroup).
is_instance_of(huaiYot,soilGroup).
is_instance_of(huaHin,soilGroup).
is_instance_of(hangChat,soilGroup).
is_instance_of(hangDong,soilGroup).
is_instance_of(hatYai,soilGroup).
is_instance_of(hinKong,soilGroup).
is_instance_of(hupKrapong,soilGroup).
is_instance_of(ongkharak,soilGroup).
is_instance_of(on,soilGroup).
is_instance_of(ayutthaya,soilGroup).
is_instance_of(aoLuk,soilGroup).
is_instance_of(udon,soilGroup).
is_instance_of(uttaradit,soilGroup).
is_instance_of(ubon,soilGroup).
is_instance_of(oLamChiak,soilGroup).
is_instance_of(kamphangPet,soilGroup).