:- module(sub_district_class, []).
% is_part_of(sub_districtName,districtName).
is_part_of(chaem_luang,kanlayaniwatthana).
is_part_of(khuang_pao,chom_thong).
is_part_of(doi_kaeo,chom_thong).
is_part_of(ban_pae,chom_thong).
is_part_of(ban_luang,chom_thong).
is_part_of(mae_soi,chom_thong).
is_part_of(sop_tia,chom_thong).
is_part_of(chiang_dao,chom_thong).
is_part_of(thung_khao_phuang,chom_thong).
is_part_of(ping_khong,chom_thong).
is_part_of(mueang_khong,chom_thong).
is_part_of(mueang_ngai,chom_thong).
is_part_of(mueang_na,chom_thong).
is_part_of(mae_na,chom_thong).
is_part_of(pong_tam,chai_prakan).
is_part_of(mae_thalop,chai_prakan).
is_part_of(si_dong_yen,chai_prakan).
is_part_of(nong_bua,chai_prakan).
is_part_of(doi_tao,doi_tao).
is_part_of(tha_duea,doi_tao).
is_part_of(ban_aen,doi_tao).
is_part_of(pong_thung,doi_tao).
is_part_of(muet_ka,doi_tao).
is_part_of(choeng_doi,doi_saket).
is_part_of(talat_khwan,doi_saket).
is_part_of(talat_yai,doi_saket).
is_part_of(thep_sadet,doi_saket).
is_part_of(pa_pong,doi_saket).
is_part_of(pa_miang,doi_saket).
is_part_of(pa_lan,doi_saket).
is_part_of(mae_khue,doi_saket).
is_part_of(mae_pong,doi_saket).
is_part_of(mae_hoi_ngoen,doi_saket).
is_part_of(luang_nuea,doi_saket).
is_part_of(sa_nga_ban,doi_saket).
is_part_of(san_pu_loei,doi_saket).
is_part_of(samran_rat,doi_saket).
is_part_of(doi_lo,doi_saket).
is_part_of(yang_khram,doi_saket).
is_part_of(song_khwae,doi_saket).
is_part_of(santi_suk,doi_saket).
is_part_of(pong_nam_ron,fang).
is_part_of(mon_pin,fang).
is_part_of(mae_kha,fang).
is_part_of(mae_ngon,fang).
is_part_of(mae_sun,fang).
is_part_of(wiang,fang).
is_part_of(san_sai,fang).
is_part_of(khuean_phak,phrao).
is_part_of(thung_luang,phrao).
is_part_of(nam_phrae,phrao).
is_part_of(ban_pong,phrao).
is_part_of(pa_tum,phrao).
is_part_of(pa_nai,phrao).
is_part_of(mae_pang,phrao).
is_part_of(mae_waen,phrao).
is_part_of(wiang,phrao).
is_part_of(san_sai,phrao).
is_part_of(long_khot,phrao).
is_part_of(tha_sala,mueang_chiang_mai).
is_part_of(pa_daet,mueang_chiang_mai).
is_part_of(mae_hia,mueang_chiang_mai).
is_part_of(san_phisuea,mueang_chiang_mai).
is_part_of(suthep,mueang_chiang_mai).
is_part_of(nong_hoi,mueang_chiang_mai).
is_part_of(kong_khaek,mae_chaem).
is_part_of(chang_khoeng,mae_chaem).
is_part_of(tha_pha,mae_chaem).
is_part_of(ban_thap,mae_chaem).
is_part_of(pang_hin_fon,mae_chaem).
is_part_of(mae_na_chon,mae_chaem).
is_part_of(mae_suek,mae_chaem).
is_part_of(kuet_chang,mae_taeng).
is_part_of(khi_lek,mae_taeng).
is_part_of(cho_lae,mae_taeng).
is_part_of(ban_chang,mae_taeng).
is_part_of(ban_pao,mae_taeng).
is_part_of(pa_pae,mae_taeng).
is_part_of(mueang_kai,mae_taeng).
is_part_of(mae_taeng,mae_taeng).
is_part_of(mae_ho_phra,mae_taeng).
is_part_of(sop_poeng,mae_taeng).
is_part_of(san_pa_yang,mae_taeng).
is_part_of(san_mahaphon,mae_taeng).
is_part_of(inthakhin,mae_taeng).
is_part_of(khi_lek,mae_rim).
is_part_of(don_kaeo,mae_rim).
is_part_of(pong_yaeng,mae_rim).
is_part_of(mae_raem,mae_rim).
is_part_of(mae_sa,mae_rim).
is_part_of(rim_tai,mae_rim).
is_part_of(rim_nuea,mae_rim).
is_part_of(saluang,mae_rim).
is_part_of(san_pong,mae_rim).
is_part_of(huai_sai,mae_rim).
is_part_of(mueang_kaeo,mae_rim).
is_part_of(don_pao,mae_wang).
is_part_of(thung_pi,mae_wang).
is_part_of(thung_ruang_thong,mae_wang).
is_part_of(ban_kat,mae_wang).
is_part_of(mae_win,mae_wang).
is_part_of(tha_nuea,mae_on).
is_part_of(ban_sahakon,mae_on).
is_part_of(mae_tha,mae_on).
is_part_of(huai_kaeo,mae_on).
is_part_of(on_klang,mae_on).
is_part_of(on_nuea,mae_on).
is_part_of(tha_ton,mae_ai).
is_part_of(ban_luang,mae_ai).
is_part_of(malika,mae_ai).
is_part_of(mae_na_wang,mae_ai).
is_part_of(mae_sao,mae_ai).
is_part_of(mae_ai,mae_ai).
is_part_of(san_ton_mue,mae_ai).
is_part_of(piang_luang,wiang_haeng).
is_part_of(mueang_haeng,wiang_haeng).
is_part_of(saen_hai,wiang_haeng).
is_part_of(bo_kaeo,samoeng).
is_part_of(mae_sap,samoeng).
is_part_of(yung_moen,samoeng).
is_part_of(samoeng_tai,samoeng).
is_part_of(samoeng_nuea,samoeng).
is_part_of(chae_chang,san_kamphaeng).
is_part_of(ton_pao,san_kamphaeng).
is_part_of(sai_mun,san_kamphaeng).
is_part_of(buak_khang,san_kamphaeng).
is_part_of(mae_pu_kha,san_kamphaeng).
is_part_of(rong_wua_daeng,san_kamphaeng).
is_part_of(san_klang,san_kamphaeng).
is_part_of(san_kamphaeng,san_kamphaeng).
is_part_of(huai_sai,san_kamphaeng).
is_part_of(on_tai,san_kamphaeng).
is_part_of(pa_phai,san_sai).
is_part_of(mueang_len,san_sai).
is_part_of(mae_faek,san_sai).
is_part_of(mae_faek_mai,san_sai).
is_part_of(san_sai_noi,san_sai).
is_part_of(san_sai_luang,san_sai).
is_part_of(san_na_meng,san_sai).
is_part_of(san_pa_pao,san_sai).
is_part_of(san_phranet,san_sai).
is_part_of(nong_chom,san_sai).
is_part_of(nong_han,san_sai).
is_part_of(nong_yaeng,san_sai).
is_part_of(tha_wang_phrao,san_pa_tong).
is_part_of(thung_tom,san_pa_tong).
is_part_of(thung_satok,san_pa_tong).
is_part_of(nam_bo_luang,san_pa_tong).
is_part_of(ban_klang,san_pa_tong).
is_part_of(ban_mae,san_pa_tong).
is_part_of(makham_luang,san_pa_tong).
is_part_of(makhun_wan,san_pa_tong).
is_part_of(mae_ka,san_pa_tong).
is_part_of(yu_wa,san_pa_tong).
is_part_of(san_klang,san_pa_tong).
is_part_of(khua_mung,saraphi).
is_part_of(chomphu,saraphi).
is_part_of(chaiya_sathan,saraphi).
is_part_of(don_kaeo,saraphi).
is_part_of(tha_wang_tan,saraphi).
is_part_of(pa_bong,saraphi).
is_part_of(yang_noeng,saraphi).
is_part_of(saraphi,saraphi).
is_part_of(nong_phueng,saraphi).
is_part_of(nong_faek,saraphi).
is_part_of(khun_khong,hang_dong).
is_part_of(nam_phrae,hang_dong).
is_part_of(ban_pong,hang_dong).
is_part_of(ban_waen,hang_dong).
is_part_of(sop_mae_kha,hang_dong).
is_part_of(san_phak_wan,hang_dong).
is_part_of(nong_kaeo,hang_dong).
is_part_of(nong_khwai,hang_dong).
is_part_of(nong_tong,hang_dong).
is_part_of(hang_dong,hang_dong).
is_part_of(han_kaeo,hang_dong).
is_part_of(na_kian,omkoi).
is_part_of(mon_chong,omkoi).
is_part_of(mae_tuen,omkoi).
is_part_of(yang_piang,omkoi).
is_part_of(sop_khong,omkoi).
is_part_of(omkoi,omkoi).
is_part_of(bo_sali,hot).
is_part_of(bo_luang,hot).
is_part_of(ban_tan,hot).
is_part_of(hang_dong,hot).
is_part_of(hot,hot).
is_part_of(chiang_dao,chiang_dao).
is_part_of(mueang_ngai,chiang_dao).
is_part_of(mae_na,chiang_dao).
is_part_of(bong_tan,doi_tao).
is_part_of(doi_lo,doi_lo).
is_part_of(yang_khram,doi_lo).
is_part_of(song_khwae,doi_lo).
is_part_of(santi_suk,doi_lo).
is_part_of(a_kho_ruea,hot).
is_part_of(kabin,kut_khaopun).
is_part_of(kaeng_kheng,kut_khaopun).
is_part_of(khao_pun,kut_khaopun).
is_part_of(non_sawang,kut_khaopun).
is_part_of(nong_than_nam,kut_khaopun).
is_part_of(kaeng_nuea,khemarat).
is_part_of(kham_pom,khemarat).
is_part_of(khemarat,khemarat).
is_part_of(chiat,khemarat).
is_part_of(na_waeng,khemarat).
is_part_of(nong_nok_tha,khemarat).
is_part_of(nong_phue,khemarat).
is_part_of(nong_sim,khemarat).
is_part_of(hua_na,khemarat).
is_part_of(klang_yai,khueang_nai).
is_part_of(ko_e,khueang_nai).
is_part_of(khueang_nai,khueang_nai).
is_part_of(kho_thong,khueang_nai).
is_part_of(chi_tuan,khueang_nai).
is_part_of(daeng_mo,khueang_nai).
is_part_of(tha_hai,khueang_nai).
is_part_of(that_noi,khueang_nai).
is_part_of(na_kham_yai,khueang_nai).
is_part_of(non_rang,khueang_nai).
is_part_of(ban_kok,khueang_nai).
is_part_of(ban_thai,khueang_nai).
is_part_of(yang_khi_nok,khueang_nai).
is_part_of(si_suk,khueang_nai).
is_part_of(sang_tho,khueang_nai).
is_part_of(sahathat,khueang_nai).
is_part_of(nong_lao,khueang_nai).
is_part_of(hua_don,khueang_nai).
is_part_of(khong_chiam,khong_chiam).
is_part_of(na_pho_klang,khong_chiam).
is_part_of(nong_saeng_yai,khong_chiam).
is_part_of(huai_phai,khong_chiam).
is_part_of(huai_yang,khong_chiam).
is_part_of(kham_hai_yai,don_mot_daeng).
is_part_of(don_mot_daeng,don_mot_daeng).
is_part_of(tha_mueang,don_mot_daeng).
is_part_of(lao_daeng,don_mot_daeng).
is_part_of(klang,det_udom).
is_part_of(kut_prathai,det_udom).
is_part_of(kaeng,det_udom).
is_part_of(kham_khrang,det_udom).
is_part_of(top_hu,det_udom).
is_part_of(tha_pho_si,det_udom).
is_part_of(thung_thoeng,det_udom).
is_part_of(na_krasaeng,det_udom).
is_part_of(na_charoen,det_udom).
is_part_of(na_suang,det_udom).
is_part_of(non_sombun,det_udom).
is_part_of(bua_ngam,det_udom).
is_part_of(pa_mong,det_udom).
is_part_of(phon_ngam,det_udom).
is_part_of(mueang_det,det_udom).
is_part_of(som_sa_at,det_udom).
is_part_of(kradian,trakan_phuet_phon).
is_part_of(kut_ya_luan,trakan_phuet_phon).
is_part_of(kusakon,trakan_phuet_phon).
is_part_of(kasem,trakan_phuet_phon).
is_part_of(kham_pia,trakan_phuet_phon).
is_part_of(khulu,trakan_phuet_phon).
is_part_of(khon_sai,trakan_phuet_phon).
is_part_of(kham_charoen,trakan_phuet_phon).
is_part_of(khok_chan,trakan_phuet_phon).
is_part_of(se_pet,trakan_phuet_phon).
is_part_of(trakan,trakan_phuet_phon).
is_part_of(tak_daet,trakan_phuet_phon).
is_part_of(tham_khae,trakan_phuet_phon).
is_part_of(tha_luang,trakan_phuet_phon).
is_part_of(na_phin,trakan_phuet_phon).
is_part_of(na_samai,trakan_phuet_phon).
is_part_of(non_kung,trakan_phuet_phon).
is_part_of(ban_daeng,trakan_phuet_phon).
is_part_of(pao,trakan_phuet_phon).
is_part_of(saphue,trakan_phuet_phon).
is_part_of(nong_tao,trakan_phuet_phon).
is_part_of(huai_fai_phatthana,trakan_phuet_phon).
is_part_of(lai_thung,trakan_phuet_phon).
is_part_of(kham_wa,trakan_phuet_phon).
is_part_of(chik_thoeng,trakan_phuet_phon).
is_part_of(tan_sum,trakan_phuet_phon).
is_part_of(na_khai,trakan_phuet_phon).
is_part_of(samrong,trakan_phuet_phon).
is_part_of(nong_kung,trakan_phuet_phon).
is_part_of(kut_ruea,thung_si_udom).
is_part_of(khok_chamrae,thung_si_udom).
is_part_of(na_kasem,thung_si_udom).
is_part_of(na_hom,thung_si_udom).
is_part_of(nong_om,thung_si_udom).
is_part_of(na_chaluai,na_chaluai).
is_part_of(non_sombun,na_chaluai).
is_part_of(non_sawan,na_chaluai).
is_part_of(ban_tum,na_chaluai).
is_part_of(phon_sawan,na_chaluai).
is_part_of(sok_saeng,na_chaluai).
is_part_of(kong_phon,na_tan).
is_part_of(na_tan,na_tan).
is_part_of(phalan,na_tan).
is_part_of(phang_khen,na_tan).
is_part_of(na_di,na_yia).
is_part_of(na_yia,na_yia).
is_part_of(na_rueang,na_yia).
is_part_of(khi_lek,nam_khun).
is_part_of(khok_sa_at,nam_khun).
is_part_of(ta_kao,nam_khun).
is_part_of(phaibun,nam_khun).
is_part_of(kao_kham,nam_yuen).
is_part_of(song,nam_yuen).
is_part_of(dom_pradit,nam_yuen).
is_part_of(bu_pueai,nam_yuen).
is_part_of(yang,nam_yuen).
is_part_of(yang_yai,nam_yuen).
is_part_of(si_wichian,nam_yuen).
is_part_of(kho_laen,boontharik).
is_part_of(na_pho,boontharik).
is_part_of(non_kho,boontharik).
is_part_of(bua_ngam,boontharik).
is_part_of(ban_maet,boontharik).
is_part_of(phon_ngam,boontharik).
is_part_of(nong_sano,boontharik).
is_part_of(huai_kha,boontharik).
is_part_of(kut_chomphu,phibun_mangsahan).
is_part_of(don_chik,phibun_mangsahan).
is_part_of(sai_mun,phibun_mangsahan).
is_part_of(na_pho,phibun_mangsahan).
is_part_of(non_klang,phibun_mangsahan).
is_part_of(non_kalong,phibun_mangsahan).
is_part_of(ban_khaem,phibun_mangsahan).
is_part_of(phibun,phibun_mangsahan).
is_part_of(pho_sai,phibun_mangsahan).
is_part_of(pho_si,phibun_mangsahan).
is_part_of(rawe,phibun_mangsahan).
is_part_of(rai_tai,phibun_mangsahan).
is_part_of(nong_bua_hi,phibun_mangsahan).
is_part_of(ang_sila,phibun_mangsahan).
is_part_of(pho_sai,pho_sai).
is_part_of(muang_yai,pho_sai).
is_part_of(song_khon,pho_sai).
is_part_of(saraphi,pho_sai).
is_part_of(samrong,pho_sai).
is_part_of(lao_ngam,pho_sai).
is_part_of(dum_yai,muang_sam_sip).
is_part_of(toei,muang_sam_sip).
is_part_of(na_loeng,muang_sam_sip).
is_part_of(phai_yai,muang_sam_sip).
is_part_of(phon_phaeng,muang_sam_sip).
is_part_of(muang_sam_sip,muang_sam_sip).
is_part_of(yang_yo_phap,muang_sam_sip).
is_part_of(yang_sak_krapho_lum,muang_sam_sip).
is_part_of(nong_khai_nok,muang_sam_sip).
is_part_of(nong_chang_yai,muang_sam_sip).
is_part_of(nong_mueang,muang_sam_sip).
is_part_of(nong_lao,muang_sam_sip).
is_part_of(nong_hang,muang_sam_sip).
is_part_of(lao_bok,muang_sam_sip).
is_part_of(krasop,mueang_ubon_ratchathani).
is_part_of(kut_lat,mueang_ubon_ratchathani).
is_part_of(kham_yai,mueang_ubon_ratchathani).
is_part_of(khi_lek,mueang_ubon_ratchathani).
is_part_of(chaeramae,mueang_ubon_ratchathani).
is_part_of(nai_mueang,mueang_ubon_ratchathani).
is_part_of(pathum,mueang_ubon_ratchathani).
is_part_of(pa_ao,mueang_ubon_ratchathani).
is_part_of(rai_noi,mueang_ubon_ratchathani).
is_part_of(nong_khon,mueang_ubon_ratchathani).
is_part_of(nong_bo,mueang_ubon_ratchathani).
is_part_of(hua_ruea,mueang_ubon_ratchathani).
is_part_of(kham_khwang,warin_chamrap).
is_part_of(kham_nam_sap,warin_chamrap).
is_part_of(khu_mueang,warin_chamrap).
is_part_of(tha_lat,warin_chamrap).
is_part_of(that,warin_chamrap).
is_part_of(non_phueng,warin_chamrap).
is_part_of(non_non,warin_chamrap).
is_part_of(bung_wai,warin_chamrap).
is_part_of(bung_mai,warin_chamrap).
is_part_of(pho_yai,warin_chamrap).
is_part_of(mueang_si_khai,warin_chamrap).
is_part_of(warin_chamrap,warin_chamrap).
is_part_of(sa_saming,warin_chamrap).
is_part_of(saen_suk,warin_chamrap).
is_part_of(nong_kin_phlen,warin_chamrap).
is_part_of(huai_khayung,warin_chamrap).
is_part_of(kaeng_kok,si_mueang_mai).
is_part_of(kham_lai,si_mueang_mai).
is_part_of(don_yai,si_mueang_mai).
is_part_of(tabai,si_mueang_mai).
is_part_of(na_kham,si_mueang_mai).
is_part_of(na_loen,si_mueang_mai).
is_part_of(lat_khwai,si_mueang_mai).
is_part_of(warin,si_mueang_mai).
is_part_of(song_yang,si_mueang_mai).
is_part_of(nam_thaeng,si_mueang_mai).
is_part_of(ueat_yai,si_mueang_mai).
is_part_of(kaeng_dom,sawang_wirawong).
is_part_of(tha_chang,sawang_wirawong).
is_part_of(bung_malaeng,sawang_wirawong).
is_part_of(sawang,sawang_wirawong).
is_part_of(kham_pom,samrong).
is_part_of(kho_noi,samrong).
is_part_of(khok_kong,samrong).
is_part_of(khok_sawang,samrong).
is_part_of(non_klang,samrong).
is_part_of(non_kalen,samrong).
is_part_of(bon,samrong).
is_part_of(samrong,samrong).
is_part_of(nong_hai,samrong).
is_part_of(khan_rai,sirindhorn).
is_part_of(kham_khuean_kaeo,sirindhorn).
is_part_of(chong_mek,sirindhorn).
is_part_of(nikhom_lam_dom_noi,sirindhorn).
is_part_of(non_ko,sirindhorn).
is_part_of(fang_kham,sirindhorn).
is_part_of(phaeng_yai,lao_suea_kok).
is_part_of(phon_mueang,lao_suea_kok).
is_part_of(nong_bok,lao_suea_kok).
is_part_of(lao_suea_kok,lao_suea_kok).
is_part_of(kham_wa,tan_sum).
is_part_of(chik_thoeng,tan_sum).
is_part_of(tan_sum,tan_sum).
is_part_of(na_khai,tan_sum).
is_part_of(samrong,tan_sum).
is_part_of(nong_kung,tan_sum).