:- module(sub_district_class, []).
% is_part_of(sub_districtName,districtName).
is_part_of(chaem_luang,kanlayaniwatthana).
is_part_of(khuang_pao,chom_thong).
is_part_of(doi_kaeo,chom_thong).
is_part_of(ban_pae,chom_thong).
is_part_of(ban_luang,chom_thong).
is_part_of(mae_soi,chom_thong).
is_part_of(sop_tia,chom_thong).
is_part_of(chiang_dao,chom_thong).
is_part_of(thung_khao_phuang,chom_thong).
is_part_of(ping_khong,chom_thong).
is_part_of(mueang_khong,chom_thong).
is_part_of(mueang_ngai,chom_thong).
is_part_of(mueang_na,chom_thong).
is_part_of(mae_na,chom_thong).
is_part_of(pong_tam,chai_prakan).
is_part_of(mae_thalop,chai_prakan).
is_part_of(si_dong_yen,chai_prakan).
is_part_of(nong_bua,chai_prakan).
is_part_of(doi_tao,doi_tao).
is_part_of(tha_duea,doi_tao).
is_part_of(ban_aen,doi_tao).
is_part_of(pong_thung,doi_tao).
is_part_of(muet_ka,doi_tao).
is_part_of(choeng_doi,doi_saket).
is_part_of(talat_khwan,doi_saket).
is_part_of(talat_yai,doi_saket).
is_part_of(thep_sadet,doi_saket).
is_part_of(pa_pong,doi_saket).
is_part_of(pa_miang,doi_saket).
is_part_of(pa_lan,doi_saket).
is_part_of(mae_khue,doi_saket).
is_part_of(mae_pong,doi_saket).
is_part_of(mae_hoi_ngoen,doi_saket).
is_part_of(luang_nuea,doi_saket).
is_part_of(sa_nga_ban,doi_saket).
is_part_of(san_pu_loei,doi_saket).
is_part_of(samran_rat,doi_saket).
is_part_of(doi_lo,doi_saket).
is_part_of(yang_khram,doi_saket).
is_part_of(song_khwae,doi_saket).
is_part_of(santi_suk,doi_saket).
is_part_of(pong_nam_ron,fang).
is_part_of(mon_pin,fang).
is_part_of(mae_kha,fang).
is_part_of(mae_ngon,fang).
is_part_of(mae_sun,fang).
is_part_of(wiang,fang).
is_part_of(san_sai,fang).
is_part_of(khuean_phak,phrao).
is_part_of(thung_luang,phrao).
is_part_of(nam_phrae,phrao).
is_part_of(ban_pong,phrao).
is_part_of(pa_tum,phrao).
is_part_of(pa_nai,phrao).
is_part_of(mae_pang,phrao).
is_part_of(mae_waen,phrao).
is_part_of(wiang,phrao).
is_part_of(san_sai,phrao).
is_part_of(long_khot,phrao).
is_part_of(tha_sala,mueang_chiang_mai).
is_part_of(pa_daet,mueang_chiang_mai).
is_part_of(mae_hia,mueang_chiang_mai).
is_part_of(san_phisuea,mueang_chiang_mai).
is_part_of(suthep,mueang_chiang_mai).
is_part_of(nong_hoi,mueang_chiang_mai).
is_part_of(kong_khaek,mae_chaem).
is_part_of(chang_khoeng,mae_chaem).
is_part_of(tha_pha,mae_chaem).
is_part_of(ban_thap,mae_chaem).
is_part_of(pang_hin_fon,mae_chaem).
is_part_of(mae_na_chon,mae_chaem).
is_part_of(mae_suek,mae_chaem).
is_part_of(kuet_chang,mae_taeng).
is_part_of(khi_lek,mae_taeng).
is_part_of(cho_lae,mae_taeng).
is_part_of(ban_chang,mae_taeng).
is_part_of(ban_pao,mae_taeng).
is_part_of(pa_pae,mae_taeng).
is_part_of(mueang_kai,mae_taeng).
is_part_of(mae_taeng,mae_taeng).
is_part_of(mae_ho_phra,mae_taeng).
is_part_of(sop_poeng,mae_taeng).
is_part_of(san_pa_yang,mae_taeng).
is_part_of(san_mahaphon,mae_taeng).
is_part_of(inthakhin,mae_taeng).
is_part_of(khi_lek,mae_rim).
is_part_of(don_kaeo,mae_rim).
is_part_of(pong_yaeng,mae_rim).
is_part_of(mae_raem,mae_rim).
is_part_of(mae_sa,mae_rim).
is_part_of(rim_tai,mae_rim).
is_part_of(rim_nuea,mae_rim).
is_part_of(saluang,mae_rim).
is_part_of(san_pong,mae_rim).
is_part_of(huai_sai,mae_rim).
is_part_of(mueang_kaeo,mae_rim).
is_part_of(don_pao,mae_wang).
is_part_of(thung_pi,mae_wang).
is_part_of(thung_ruang_thong,mae_wang).
is_part_of(ban_kat,mae_wang).
is_part_of(mae_win,mae_wang).
is_part_of(tha_nuea,mae_on).
is_part_of(ban_sahakon,mae_on).
is_part_of(mae_tha,mae_on).
is_part_of(huai_kaeo,mae_on).
is_part_of(on_klang,mae_on).
is_part_of(on_nuea,mae_on).
is_part_of(tha_ton,mae_ai).
is_part_of(ban_luang,mae_ai).
is_part_of(malika,mae_ai).
is_part_of(mae_na_wang,mae_ai).
is_part_of(mae_sao,mae_ai).
is_part_of(mae_ai,mae_ai).
is_part_of(san_ton_mue,mae_ai).
is_part_of(piang_luang,wiang_haeng).
is_part_of(mueang_haeng,wiang_haeng).
is_part_of(saen_hai,wiang_haeng).
is_part_of(bo_kaeo,samoeng).
is_part_of(mae_sap,samoeng).
is_part_of(yung_moen,samoeng).
is_part_of(samoeng_tai,samoeng).
is_part_of(samoeng_nuea,samoeng).
is_part_of(chae_chang,san_kamphaeng).
is_part_of(ton_pao,san_kamphaeng).
is_part_of(sai_mun,san_kamphaeng).
is_part_of(buak_khang,san_kamphaeng).
is_part_of(mae_pu_kha,san_kamphaeng).
is_part_of(rong_wua_daeng,san_kamphaeng).
is_part_of(san_klang,san_kamphaeng).
is_part_of(san_kamphaeng,san_kamphaeng).
is_part_of(huai_sai,san_kamphaeng).
is_part_of(on_tai,san_kamphaeng).
is_part_of(pa_phai,san_sai).
is_part_of(mueang_len,san_sai).
is_part_of(mae_faek,san_sai).
is_part_of(mae_faek_mai,san_sai).
is_part_of(san_sai_noi,san_sai).
is_part_of(san_sai_luang,san_sai).
is_part_of(san_na_meng,san_sai).
is_part_of(san_pa_pao,san_sai).
is_part_of(san_phranet,san_sai).
is_part_of(nong_chom,san_sai).
is_part_of(nong_han,san_sai).
is_part_of(nong_yaeng,san_sai).
is_part_of(tha_wang_phrao,san_pa_tong).
is_part_of(thung_tom,san_pa_tong).
is_part_of(thung_satok,san_pa_tong).
is_part_of(nam_bo_luang,san_pa_tong).
is_part_of(ban_klang,san_pa_tong).
is_part_of(ban_mae,san_pa_tong).
is_part_of(makham_luang,san_pa_tong).
is_part_of(makhun_wan,san_pa_tong).
is_part_of(mae_ka,san_pa_tong).
is_part_of(yu_wa,san_pa_tong).
is_part_of(san_klang,san_pa_tong).
is_part_of(khua_mung,saraphi).
is_part_of(chomphu,saraphi).
is_part_of(chaiya_sathan,saraphi).
is_part_of(don_kaeo,saraphi).
is_part_of(tha_wang_tan,saraphi).
is_part_of(pa_bong,saraphi).
is_part_of(yang_noeng,saraphi).
is_part_of(saraphi,saraphi).
is_part_of(nong_phueng,saraphi).
is_part_of(nong_faek,saraphi).
is_part_of(khun_khong,hang_dong).
is_part_of(nam_phrae,hang_dong).
is_part_of(ban_pong,hang_dong).
is_part_of(ban_waen,hang_dong).
is_part_of(sop_mae_kha,hang_dong).
is_part_of(san_phak_wan,hang_dong).
is_part_of(nong_kaeo,hang_dong).
is_part_of(nong_khwai,hang_dong).
is_part_of(nong_tong,hang_dong).
is_part_of(hang_dong,hang_dong).
is_part_of(han_kaeo,hang_dong).
is_part_of(na_kian,omkoi).
is_part_of(mon_chong,omkoi).
is_part_of(mae_tuen,omkoi).
is_part_of(yang_piang,omkoi).
is_part_of(sop_khong,omkoi).
is_part_of(omkoi,omkoi).
is_part_of(bo_sali,hot).
is_part_of(bo_luang,hot).
is_part_of(ban_tan,hot).
is_part_of(hang_dong,hot).
is_part_of(hot,hot).
is_part_of(chiang_dao,chiang_dao).
is_part_of(mueang_ngai,chiang_dao).
is_part_of(mae_na,chiang_dao).
is_part_of(bong_tan,doi_tao).
is_part_of(doi_lo,doi_lo).
is_part_of(yang_khram,doi_lo).
is_part_of(song_khwae,doi_lo).
is_part_of(santi_suk,doi_lo).
is_part_of(a_kho_ruea,hot).
is_part_of(kabin,kut_khaopun).
is_part_of(kaeng_kheng,kut_khaopun).
is_part_of(khao_pun,kut_khaopun).
is_part_of(non_sawang,kut_khaopun).
is_part_of(nong_than_nam,kut_khaopun).
is_part_of(kaeng_nuea,khemarat).
is_part_of(kham_pom,khemarat).
is_part_of(khemarat,khemarat).
is_part_of(chiat,khemarat).
is_part_of(na_waeng,khemarat).
is_part_of(nong_nok_tha,khemarat).
is_part_of(nong_phue,khemarat).
is_part_of(nong_sim,khemarat).
is_part_of(hua_na,khemarat).
is_part_of(klang_yai,khueang_nai).
is_part_of(ko_e,khueang_nai).
is_part_of(khueang_nai,khueang_nai).
is_part_of(kho_thong,khueang_nai).
is_part_of(chi_tuan,khueang_nai).
is_part_of(daeng_mo,khueang_nai).
is_part_of(tha_hai,khueang_nai).
is_part_of(that_noi,khueang_nai).
is_part_of(na_kham_yai,khueang_nai).
is_part_of(non_rang,khueang_nai).
is_part_of(ban_kok,khueang_nai).
is_part_of(ban_thai,khueang_nai).
is_part_of(yang_khi_nok,khueang_nai).
is_part_of(si_suk,khueang_nai).
is_part_of(sang_tho,khueang_nai).
is_part_of(sahathat,khueang_nai).
is_part_of(nong_lao,khueang_nai).
is_part_of(hua_don,khueang_nai).
is_part_of(khong_chiam,khong_chiam).
is_part_of(na_pho_klang,khong_chiam).
is_part_of(nong_saeng_yai,khong_chiam).
is_part_of(huai_phai,khong_chiam).
is_part_of(huai_yang,khong_chiam).
is_part_of(kham_hai_yai,don_mot_daeng).
is_part_of(don_mot_daeng,don_mot_daeng).
is_part_of(tha_mueang,don_mot_daeng).
is_part_of(lao_daeng,don_mot_daeng).
is_part_of(klang,det_udom).
is_part_of(kut_prathai,det_udom).
is_part_of(kaeng,det_udom).
is_part_of(kham_khrang,det_udom).
is_part_of(top_hu,det_udom).
is_part_of(tha_pho_si,det_udom).
is_part_of(thung_thoeng,det_udom).
is_part_of(na_krasaeng,det_udom).
is_part_of(na_charoen,det_udom).
is_part_of(na_suang,det_udom).
is_part_of(non_sombun,det_udom).
is_part_of(bua_ngam,det_udom).
is_part_of(pa_mong,det_udom).
is_part_of(phon_ngam,det_udom).
is_part_of(mueang_det,det_udom).
is_part_of(som_sa_at,det_udom).
is_part_of(kradian,trakan_phuet_phon).
is_part_of(kut_ya_luan,trakan_phuet_phon).
is_part_of(kusakon,trakan_phuet_phon).
is_part_of(kasem,trakan_phuet_phon).
is_part_of(kham_pia,trakan_phuet_phon).
is_part_of(khulu,trakan_phuet_phon).
is_part_of(khon_sai,trakan_phuet_phon).
is_part_of(kham_charoen,trakan_phuet_phon).
is_part_of(khok_chan,trakan_phuet_phon).
is_part_of(se_pet,trakan_phuet_phon).
is_part_of(trakan,trakan_phuet_phon).
is_part_of(tak_daet,trakan_phuet_phon).
is_part_of(tham_khae,trakan_phuet_phon).
is_part_of(tha_luang,trakan_phuet_phon).
is_part_of(na_phin,trakan_phuet_phon).
is_part_of(na_samai,trakan_phuet_phon).
is_part_of(non_kung,trakan_phuet_phon).
is_part_of(ban_daeng,trakan_phuet_phon).
is_part_of(pao,trakan_phuet_phon).
is_part_of(saphue,trakan_phuet_phon).
is_part_of(nong_tao,trakan_phuet_phon).
is_part_of(huai_fai_phatthana,trakan_phuet_phon).
is_part_of(lai_thung,trakan_phuet_phon).
is_part_of(kham_wa,trakan_phuet_phon).
is_part_of(chik_thoeng,trakan_phuet_phon).
is_part_of(tan_sum,trakan_phuet_phon).
is_part_of(na_khai,trakan_phuet_phon).
is_part_of(samrong,trakan_phuet_phon).
is_part_of(nong_kung,trakan_phuet_phon).
is_part_of(kut_ruea,thung_si_udom).
is_part_of(khok_chamrae,thung_si_udom).
is_part_of(na_kasem,thung_si_udom).
is_part_of(na_hom,thung_si_udom).
is_part_of(nong_om,thung_si_udom).
is_part_of(na_chaluai,na_chaluai).
is_part_of(non_sombun,na_chaluai).
is_part_of(non_sawan,na_chaluai).
is_part_of(ban_tum,na_chaluai).
is_part_of(phon_sawan,na_chaluai).
is_part_of(sok_saeng,na_chaluai).
is_part_of(kong_phon,na_tan).
is_part_of(na_tan,na_tan).
is_part_of(phalan,na_tan).
is_part_of(phang_khen,na_tan).
is_part_of(na_di,na_yia).
is_part_of(na_yia,na_yia).
is_part_of(na_rueang,na_yia).
is_part_of(khi_lek,nam_khun).
is_part_of(khok_sa_at,nam_khun).
is_part_of(ta_kao,nam_khun).
is_part_of(phaibun,nam_khun).
is_part_of(kao_kham,nam_yuen).
is_part_of(song,nam_yuen).
is_part_of(dom_pradit,nam_yuen).
is_part_of(bu_pueai,nam_yuen).
is_part_of(yang,nam_yuen).
is_part_of(yang_yai,nam_yuen).
is_part_of(si_wichian,nam_yuen).
is_part_of(kho_laen,boontharik).
is_part_of(na_pho,boontharik).
is_part_of(non_kho,boontharik).
is_part_of(bua_ngam,boontharik).
is_part_of(ban_maet,boontharik).
is_part_of(phon_ngam,boontharik).
is_part_of(nong_sano,boontharik).
is_part_of(huai_kha,boontharik).
is_part_of(kut_chomphu,phibun_mangsahan).
is_part_of(don_chik,phibun_mangsahan).
is_part_of(sai_mun,phibun_mangsahan).
is_part_of(na_pho,phibun_mangsahan).
is_part_of(non_klang,phibun_mangsahan).
is_part_of(non_kalong,phibun_mangsahan).
is_part_of(ban_khaem,phibun_mangsahan).
is_part_of(phibun,phibun_mangsahan).
is_part_of(pho_sai,phibun_mangsahan).
is_part_of(pho_si,phibun_mangsahan).
is_part_of(rawe,phibun_mangsahan).
is_part_of(rai_tai,phibun_mangsahan).
is_part_of(nong_bua_hi,phibun_mangsahan).
is_part_of(ang_sila,phibun_mangsahan).
is_part_of(pho_sai,pho_sai).
is_part_of(muang_yai,pho_sai).
is_part_of(song_khon,pho_sai).
is_part_of(saraphi,pho_sai).
is_part_of(samrong,pho_sai).
is_part_of(lao_ngam,pho_sai).
is_part_of(dum_yai,muang_sam_sip).
is_part_of(toei,muang_sam_sip).
is_part_of(na_loeng,muang_sam_sip).
is_part_of(phai_yai,muang_sam_sip).
is_part_of(phon_phaeng,muang_sam_sip).
is_part_of(muang_sam_sip,muang_sam_sip).
is_part_of(yang_yo_phap,muang_sam_sip).
is_part_of(yang_sak_krapho_lum,muang_sam_sip).
is_part_of(nong_khai_nok,muang_sam_sip).
is_part_of(nong_chang_yai,muang_sam_sip).
is_part_of(nong_mueang,muang_sam_sip).
is_part_of(nong_lao,muang_sam_sip).
is_part_of(nong_hang,muang_sam_sip).
is_part_of(lao_bok,muang_sam_sip).
is_part_of(krasop,mueang_ubon_ratchathani).
is_part_of(kut_lat,mueang_ubon_ratchathani).
is_part_of(kham_yai,mueang_ubon_ratchathani).
is_part_of(khi_lek,mueang_ubon_ratchathani).
is_part_of(chaeramae,mueang_ubon_ratchathani).
is_part_of(nai_mueang,mueang_ubon_ratchathani).
is_part_of(pathum,mueang_ubon_ratchathani).
is_part_of(pa_ao,mueang_ubon_ratchathani).
is_part_of(rai_noi,mueang_ubon_ratchathani).
is_part_of(nong_khon,mueang_ubon_ratchathani).
is_part_of(nong_bo,mueang_ubon_ratchathani).
is_part_of(hua_ruea,mueang_ubon_ratchathani).
is_part_of(kham_khwang,warin_chamrap).
is_part_of(kham_nam_sap,warin_chamrap).
is_part_of(khu_mueang,warin_chamrap).
is_part_of(tha_lat,warin_chamrap).
is_part_of(that,warin_chamrap).
is_part_of(non_phueng,warin_chamrap).
is_part_of(non_non,warin_chamrap).
is_part_of(bung_wai,warin_chamrap).
is_part_of(bung_mai,warin_chamrap).
is_part_of(pho_yai,warin_chamrap).
is_part_of(mueang_si_khai,warin_chamrap).
is_part_of(warin_chamrap,warin_chamrap).
is_part_of(sa_saming,warin_chamrap).
is_part_of(saen_suk,warin_chamrap).
is_part_of(nong_kin_phlen,warin_chamrap).
is_part_of(huai_khayung,warin_chamrap).
is_part_of(kaeng_kok,si_mueang_mai).
is_part_of(kham_lai,si_mueang_mai).
is_part_of(don_yai,si_mueang_mai).
is_part_of(tabai,si_mueang_mai).
is_part_of(na_kham,si_mueang_mai).
is_part_of(na_loen,si_mueang_mai).
is_part_of(lat_khwai,si_mueang_mai).
is_part_of(warin,si_mueang_mai).
is_part_of(song_yang,si_mueang_mai).
is_part_of(nam_thaeng,si_mueang_mai).
is_part_of(ueat_yai,si_mueang_mai).
is_part_of(kaeng_dom,sawang_wirawong).
is_part_of(tha_chang,sawang_wirawong).
is_part_of(bung_malaeng,sawang_wirawong).
is_part_of(sawang,sawang_wirawong).
is_part_of(kham_pom,samrong).
is_part_of(kho_noi,samrong).
is_part_of(khok_kong,samrong).
is_part_of(khok_sawang,samrong).
is_part_of(non_klang,samrong).
is_part_of(non_kalen,samrong).
is_part_of(bon,samrong).
is_part_of(samrong,samrong).
is_part_of(nong_hai,samrong).
is_part_of(khan_rai,sirindhorn).
is_part_of(kham_khuean_kaeo,sirindhorn).
is_part_of(chong_mek,sirindhorn).
is_part_of(nikhom_lam_dom_noi,sirindhorn).
is_part_of(non_ko,sirindhorn).
is_part_of(fang_kham,sirindhorn).
is_part_of(phaeng_yai,lao_suea_kok).
is_part_of(phon_mueang,lao_suea_kok).
is_part_of(nong_bok,lao_suea_kok).
is_part_of(lao_suea_kok,lao_suea_kok).
is_part_of(kham_wa,tan_sum).
is_part_of(chik_thoeng,tan_sum).
is_part_of(tan_sum,tan_sum).
is_part_of(na_khai,tan_sum).
is_part_of(samrong,tan_sum).
is_part_of(nong_kung,tan_sum).
% Suphanburi and Surin
is_part_of(don_chedi,don_chedi).
is_part_of(thale_bok,don_chedi).
is_part_of(rai_rot,don_chedi).
is_part_of(sa_krachom,don_chedi).
is_part_of(nong_sarai,don_chedi).
is_part_of(dan_chang,dan_chang).
is_part_of(nikhom_krasiao,dan_chang).
is_part_of(wang_khan,dan_chang).
is_part_of(nong_makha_mong,dan_chang).
is_part_of(huai_khamin,dan_chang).
is_part_of(ong_phra,dan_chang).
is_part_of(khao_din,doem_bang_nang_buat).
is_part_of(khao_phra,doem_bang_nang_buat).
is_part_of(khok_chang,doem_bang_nang_buat).
is_part_of(doem_bang,doem_bang_nang_buat).
is_part_of(thung_khli,doem_bang_nang_buat).
is_part_of(nang_buat,doem_bang_nang_buat).
is_part_of(bo_kru,doem_bang_nang_buat).
is_part_of(pak_nam,doem_bang_nang_buat).
is_part_of(pa_sakae,doem_bang_nang_buat).
is_part_of(yang_non,doem_bang_nang_buat).
is_part_of(wang_si_rat,doem_bang_nang_buat).
is_part_of(nong_krathum,doem_bang_nang_buat).
is_part_of(hua_khao,doem_bang_nang_buat).
is_part_of(hua_na,doem_bang_nang_buat).
is_part_of(kritsana,bang_pla_ma).
is_part_of(khok_khram,bang_pla_ma).
is_part_of(chorakhe_yai,bang_pla_ma).
is_part_of(takha,bang_pla_ma).
is_part_of(bang_pla_ma,bang_pla_ma).
is_part_of(bang_yai,bang_pla_ma).
is_part_of(ban_laem,bang_pla_ma).
is_part_of(phai_kong_din,bang_pla_ma).
is_part_of(makham_lom,bang_pla_ma).
is_part_of(wang_nam_yen,bang_pla_ma).
is_part_of(wat_dao,bang_pla_ma).
is_part_of(wat_bot,bang_pla_ma).
is_part_of(sali,bang_pla_ma).
is_part_of(ongkharak,bang_pla_ma).
is_part_of(khok_kho_thao,mueang_saphan_buri).
is_part_of(don_kamyan,mueang_saphan_buri).
is_part_of(don_tan,mueang_saphan_buri).
is_part_of(don_pho_thong,mueang_saphan_buri).
is_part_of(don_masang,mueang_saphan_buri).
is_part_of(taling_chan,mueang_saphan_buri).
is_part_of(thap_ti_lek,mueang_saphan_buri).
is_part_of(tha_phi_liang,mueang_saphan_buri).
is_part_of(tha_rahat,mueang_saphan_buri).
is_part_of(bang_kung,mueang_saphan_buri).
is_part_of(ban_pho,mueang_saphan_buri).
is_part_of(phai_khwang,mueang_saphan_buri).
is_part_of(phihan_daeng,mueang_saphan_buri).
is_part_of(pho_phraya,mueang_saphan_buri).
is_part_of(rua_yai,mueang_saphan_buri).
is_part_of(sala_khao,mueang_saphan_buri).
is_part_of(sanam_khli,mueang_saphan_buri).
is_part_of(sanam_chai,mueang_saphan_buri).
is_part_of(sa_kaeo,mueang_saphan_buri).
is_part_of(suan_taeng,mueang_saphan_buri).
is_part_of(don_pru,si_prachan).
is_part_of(bang_ngam,si_prachan).
is_part_of(ban_krang,si_prachan).
is_part_of(plai_na,si_prachan).
is_part_of(mot_daeng,si_prachan).
is_part_of(wang_nam_sap,si_prachan).
is_part_of(wang_yang,si_prachan).
is_part_of(wang_wa,si_prachan).
is_part_of(si_prachan,si_prachan).
is_part_of(don_manao,song_phi_nong).
is_part_of(ton_tan,song_phi_nong).
is_part_of(thung_khok,song_phi_nong).
is_part_of(noen_phraprang,song_phi_nong).
is_part_of(bo_suphan,song_phi_nong).
is_part_of(bang_takhian,song_phi_nong).
is_part_of(bang_ta_then,song_phi_nong).
is_part_of(bang_phlap,song_phi_nong).
is_part_of(bang_len,song_phi_nong).
is_part_of(ban_kum,song_phi_nong).
is_part_of(ban_chang,song_phi_nong).
is_part_of(si_samran,song_phi_nong).
is_part_of(song_phi_nong,song_phi_nong).
is_part_of(nong_bo,song_phi_nong).
is_part_of(hua_pho,song_phi_nong).
is_part_of(krasiao,sam_chuk).
is_part_of(ban_siao,sam_chuk).
is_part_of(wang_luek,sam_chuk).
is_part_of(sam_chuk,sam_chuk).
is_part_of(nong_phak_nak,sam_chuk).
is_part_of(nong_sadao,sam_chuk).
is_part_of(chaeng_ngam,nong_ya_sai).
is_part_of(thap_luang,nong_ya_sai).
is_part_of(nong_kham,nong_ya_sai).
is_part_of(nong_pho,nong_ya_sai).
is_part_of(nong_ratchawat,nong_ya_sai).
is_part_of(nong_ya_sai,nong_ya_sai).
is_part_of(krachan,u_thong).
is_part_of(chorakhe_sam_phan,u_thong).
is_part_of(chedi,u_thong).
is_part_of(don_kha,u_thong).
is_part_of(don_makluea,u_thong).
is_part_of(ban_khong,u_thong).
is_part_of(ban_don,u_thong).
is_part_of(phlapphla_chai,u_thong).
is_part_of(yung_thalai,u_thong).
is_part_of(sa_phang_lan,u_thong).
is_part_of(sa_yai_som,u_thong).
is_part_of(nong_ong,u_thong).
is_part_of(u_thong,u_thong).
is_part_of(nai_mueang,mueang_surin).
is_part_of(tang_chai,mueang_surin).
is_part_of(phia_ram,mueang_surin).
is_part_of(na_di,mueang_surin).
is_part_of(tha_sawang,mueang_surin).
is_part_of(salak_dai,mueang_surin).
is_part_of(ta_ong,mueang_surin).
is_part_of(samrong,mueang_surin).
is_part_of(kae_yai,mueang_surin).
is_part_of(nok_mueang,mueang_surin).
is_part_of(kho_kho,mueang_surin).
is_part_of(sawat,mueang_surin).
is_part_of(chaniang,mueang_surin).
is_part_of(then_mi,mueang_surin).
is_part_of(na_bua,mueang_surin).
is_part_of(mueang_thi,mueang_surin).
is_part_of(ram,mueang_surin).
is_part_of(bu_ruesi,mueang_surin).
is_part_of(trasaeng,mueang_surin).
is_part_of(salaeng_phan,mueang_surin).
is_part_of(ka_ko,mueang_surin).
is_part_of(chumphon_buri,chumphon_buri).
is_part_of(na_nong_phai,chumphon_buri).
is_part_of(phrai_khla,chumphon_buri).
is_part_of(si_narong,chumphon_buri).
is_part_of(yawuek,chumphon_buri).
is_part_of(mueang_bua,chumphon_buri).
is_part_of(sa_khut,chumphon_buri).
is_part_of(krabueang,chumphon_buri).
is_part_of(nong_ruea,chumphon_buri).
is_part_of(tha_tum,tha_tum).
is_part_of(krapho,tha_tum).
is_part_of(phrom_thep,tha_tum).
is_part_of(phon_khrok,tha_tum).
is_part_of(mueang_kae,tha_tum).
is_part_of(ba,tha_tum).
is_part_of(nong_bua,tha_tum).
is_part_of(bua_khok,tha_tum).
is_part_of(nong_methi,tha_tum).
is_part_of(thung_kula,tha_tum).
is_part_of(chom_phra,chom_phra).
is_part_of(mueang_lueng,chom_phra).
is_part_of(krahat,chom_phra).
is_part_of(bu_kraeng,chom_phra).
is_part_of(nong_sanit,chom_phra).
is_part_of(ban_phue,chom_phra).
is_part_of(lum_rawi,chom_phra).
is_part_of(chum_saeng,chom_phra).
is_part_of(pen_suk,chom_phra).
is_part_of(kang_aen,prasat).
is_part_of(thamo,prasat).
is_part_of(phrai,prasat).
is_part_of(prue,prasat).
is_part_of(thung_mon,prasat).
is_part_of(ta_bao,prasat).
is_part_of(nong_yai,prasat).
is_part_of(khok_yang,prasat).
is_part_of(khok_sa_at,prasat).
is_part_of(ban_sai,prasat).
is_part_of(chok_na_sam,prasat).
is_part_of(chue_phloeng,prasat).
is_part_of(prasat_thanong,prasat).
is_part_of(tani,prasat).
is_part_of(ban_phluang,prasat).
is_part_of(kantuat_ramuan,prasat).
is_part_of(samut,prasat).
is_part_of(prathat_bu,prasat).
is_part_of(kap_choeng,kap_choeng).
is_part_of(khu_tan,kap_choeng).
is_part_of(dan,kap_choeng).
is_part_of(naeng_mut,kap_choeng).
is_part_of(khok_takhian,kap_choeng).
is_part_of(takhian,kap_choeng).
is_part_of(kut_kha_khim,rattanaburi).
is_part_of(kae,rattanaburi).
is_part_of(don_raet,rattanaburi).
is_part_of(thap_yai,rattanaburi).
is_part_of(that,rattanaburi).
is_part_of(nam_khiao,rattanaburi).
is_part_of(boet,rattanaburi).
is_part_of(phai,rattanaburi).
is_part_of(yang_sawang,rattanaburi).
is_part_of(rattana_buri,rattanaburi).
is_part_of(nong_bua_thong,rattanaburi).
is_part_of(nong_bua_ban,rattanaburi).
is_part_of(sanom,sanom).
is_part_of(phon_ko,sanom).
is_part_of(nong_rakhang,sanom).
is_part_of(na_nuan,sanom).
is_part_of(khaen,sanom).
is_part_of(hua_ngua,sanom).
is_part_of(nong_i_yo,sanom).
is_part_of(ra_ngaeng,sikhoraphum).
is_part_of(truem,sikhoraphum).
is_part_of(charaphat,sikhoraphum).
is_part_of(yang,sikhoraphum).
is_part_of(tlae,sikhoraphum).
is_part_of(nong_bua,sikhoraphum).
is_part_of(khalamae,sikhoraphum).
is_part_of(nong_lek,sikhoraphum).
is_part_of(nong_khwao,sikhoraphum).
is_part_of(chang_pi,sikhoraphum).
is_part_of(kut_wai,sikhoraphum).
is_part_of(khwao_yai,sikhoraphum).
is_part_of(na_rung,sikhoraphum).
is_part_of(trom_phrai,sikhoraphum).
is_part_of(phak_mai,sikhoraphum).
is_part_of(krathiam,sangkha).
is_part_of(khon_taek,sangkha).
is_part_of(dom,sangkha).
is_part_of(ta_khong,sangkha).
is_part_of(tatum,sangkha).
is_part_of(thapthan,sangkha).
is_part_of(thep_raksa,sangkha).
is_part_of(ban_chan,sangkha).
is_part_of(ban_chop,sangkha).
is_part_of(phra_kaeo,sangkha).
is_part_of(sakat,sangkha).
is_part_of(sangkha,sangkha).
is_part_of(chok_nuea,lamduan).
is_part_of(trapiang_tia,lamduan).
is_part_of(tramdom,lamduan).
is_part_of(lamduan,lamduan).
is_part_of(u_lok,lamduan).
is_part_of(kra_om,samrong_thap).
is_part_of(ko_kaeo,samrong_thap).
is_part_of(pradu,samrong_thap).
is_part_of(si_suk,samrong_thap).
is_part_of(sano,samrong_thap).
is_part_of(samrong_thap,samrong_thap).
is_part_of(samet,samrong_thap).
is_part_of(nong_phai_lom,samrong_thap).
is_part_of(nong_ha,samrong_thap).
is_part_of(muen_si,samrong_thap).
is_part_of(charat,buachet).
is_part_of(ta_wang,buachet).
is_part_of(bua_chet,buachet).
is_part_of(sadao,buachet).
is_part_of(samphao_lun,buachet).
is_part_of(a_phon,buachet).
is_part_of(khok_klang,phanom_dong_rak).
is_part_of(chik_daek,phanom_dong_rak).
is_part_of(ta_miang,phanom_dong_rak).
is_part_of(bak_dai,phanom_dong_rak).
is_part_of(chaen_waen,si_narong).
is_part_of(narong,si_narong).
is_part_of(truat,si_narong).
is_part_of(si_suk,si_narong).
is_part_of(nong_waeng,si_narong).
is_part_of(ta_kuk,khwao_sinarin).
is_part_of(khewa_sinarin,khwao_sinarin).
is_part_of(ban_rae,khwao_sinarin).
is_part_of(bueng,khwao_sinarin).
is_part_of(prasat_thong,khwao_sinarin).
is_part_of(kham_phong,non_narai).
is_part_of(non,non_narai).
is_part_of(rawiang,non_narai).
is_part_of(nong_thep,non_narai).
is_part_of(nong_luang,non_narai).